-- ==========================================================================
-- LetzRyd Partner App — Complete Database Schema Script
-- Contains 9 App Tables + 10 Raw Automation Pipeline Target Tables
-- ==========================================================================


-- TABLE: app_drivers
CREATE TABLE IF NOT EXISTS app_drivers (
    app_driver_id                    SERIAL                    PRIMARY KEY,
    driver_id                        INTEGER                   NULL,
    operator_id                      INTEGER                   NULL,
    full_name                        VARCHAR(150)              NULL,
    phone                            VARCHAR(15)               NULL UNIQUE,
    profile_photo_url                TEXT                      NULL,
    initials                         VARCHAR(5)                NULL,
    driver_code                      VARCHAR(30)               NULL,
    aadhar_number                    VARCHAR(20)               NULL,
    blood_group                      VARCHAR(5)                NULL,
    dob                              DATE                      NULL,
    address                          TEXT                      NULL,
    joined_date                      DATE                      NULL,
    emergency_name                   VARCHAR(150)              NULL,
    emergency_relation               VARCHAR(50)               NULL,
    emergency_phone                  VARCHAR(15)               NULL,
    dl_number                        VARCHAR(50)               NULL,
    dl_expiry                        DATE                      NULL,
    current_vehicle_id               INTEGER                   NULL,
    current_allocation_id            INTEGER                   NULL,
    vehicle_reg_number               VARCHAR(20)               NULL,
    vehicle_make                     VARCHAR(50)               NULL,
    vehicle_model                    VARCHAR(50)               NULL,
    vehicle_variant                  VARCHAR(50)               NULL,
    vehicle_year                     SMALLINT                  NULL,
    vehicle_color                    VARCHAR(50)               NULL,
    vehicle_fuel_type                VARCHAR(20)               NULL,
    vehicle_odometer_km              INTEGER                   NULL,
    vehicle_allocated_from           DATE                      NULL,
    vehicle_daily_rate               NUMERIC(10,2)             NULL,
    rc_number                        VARCHAR(50)               NULL,
    rc_expiry                        DATE                      NULL,
    insurance_number                 VARCHAR(50)               NULL,
    insurance_expiry                 DATE                      NULL,
    permit_type                      VARCHAR(50)               NULL,
    permit_number                    VARCHAR(50)               NULL,
    permit_expiry                    DATE                      NULL,
    fitness_number                   VARCHAR(50)               NULL,
    fitness_expiry                   DATE                      NULL,
    puc_expiry                       DATE                      NULL,
    doc_last_updated                 DATE                      NULL,
    deposit_total_req                NUMERIC(10,2)             NULL,
    deposit_paid                     NUMERIC(10,2)             NULL,
    deposit_pending                  NUMERIC(10,2)             NULL,
    deposit_next_due                 DATE                      NULL,
    joining_fee_agreed               NUMERIC(10,2)             NULL,
    joining_fee_paid                 NUMERIC(10,2)             NULL,
    cumulative_owed                  NUMERIC(12,2)             NULL,
    assigned_manager_name            VARCHAR(150)              NULL,
    assigned_manager_phone           VARCHAR(15)               NULL,
    incentive_trips_target           INTEGER                   NULL,
    incentive_reward_amt             NUMERIC(10,2)             NULL,
    referral_code                    VARCHAR(30)               NULL UNIQUE,
    referral_reward_amt              NUMERIC(10,2)             NULL,
    contract_terms_url               TEXT                      NULL,
    upi_id                           VARCHAR(100)              NULL,
    bank_account_last4               VARCHAR(4)                NULL,
    password_hash                    VARCHAR(255)              NULL,
    fcm_token                        TEXT                      NULL,
    preferred_language               VARCHAR(5)                NULL,
    is_active                        BOOLEAN                   NULL DEFAULT FALSE,
    created_at                       TIMESTAMP WITH TIME ZONE  NULL DEFAULT NOW(),
    last_login_at                    TIMESTAMP WITH TIME ZONE  NULL,
    last_synced_at                   TIMESTAMP WITH TIME ZONE  NULL,
    cw_uber_trips                    INTEGER                   NULL,
    cw_uber_revenue                  NUMERIC(12,2)             NULL,
    cw_uber_cash                     NUMERIC(12,2)             NULL,
    cw_uber_toll                     NUMERIC(12,2)             NULL,
    cw_uber_incentive                NUMERIC(12,2)             NULL,
    cw_uber_subscription             NUMERIC(12,2)             NULL,
    cw_uber_km                       NUMERIC(10,2)             NULL,
    cw_ola_trips                     INTEGER                   NULL,
    cw_ola_revenue                   NUMERIC(12,2)             NULL,
    cw_ola_cash                      NUMERIC(12,2)             NULL,
    cw_ola_toll                      NUMERIC(12,2)             NULL,
    cw_ola_incentive                 NUMERIC(12,2)             NULL,
    cw_ola_subscription              NUMERIC(12,2)             NULL,
    cw_ola_km                        NUMERIC(10,2)             NULL,
    cw_rapido_trips                  INTEGER                   NULL,
    cw_rapido_revenue                NUMERIC(12,2)             NULL,
    cw_rapido_cash                   NUMERIC(12,2)             NULL,
    cw_rapido_toll                   NUMERIC(12,2)             NULL,
    cw_rapido_incentive              NUMERIC(12,2)             NULL,
    cw_rapido_subscription           NUMERIC(12,2)             NULL,
    cw_rapido_km                     NUMERIC(10,2)             NULL,
    cw_vehicle_rent                  NUMERIC(12,2)             NULL,
    cw_maintenance_charge            NUMERIC(12,2)             NULL,
    cw_active_days                   SMALLINT                  NULL,
    cw_tds                           NUMERIC(12,2)             NULL,
    cw_challans                      NUMERIC(12,2)             NULL,
    cw_accident_charge               NUMERIC(12,2)             NULL,
    cw_other_adjustment              NUMERIC(12,2)             NULL,
    cw_previous_outstanding          NUMERIC(12,2)             NULL,
    cw_gps_total_km                  NUMERIC(10,2)             NULL,
    cw_gps_ideal_km                  NUMERIC(10,2)             NULL,
    cw_gps_dead_km                   NUMERIC(10,2)             NULL,
    cw_gps_dead_pct                  NUMERIC(5,2)              NULL,
    cw_gps_dead_penalty              NUMERIC(10,2)             NULL,
    cw_trips                         INTEGER                   NULL,
    cw_total_km                      NUMERIC(10,2)             NULL,
    cw_gross_earnings                NUMERIC(12,2)             NULL,
    cw_total_deductions              NUMERIC(12,2)             NULL,
    cw_total_penalties               NUMERIC(12,2)             NULL,
    cw_os                            NUMERIC(12,2)             NULL,
    cw_to_pay                        NUMERIC(12,2)             NULL,
    cw_to_collect                    NUMERIC(12,2)             NULL,
    lw_trips                         INTEGER                   NULL,
    lw_gross_earnings                NUMERIC(12,2)             NULL,
    lw_os                            NUMERIC(12,2)             NULL,
    lw_week_number                   SMALLINT                  NULL,
    lw_hisaab_number                 VARCHAR(25)               NULL,
    lw_status                        VARCHAR(20)               NULL,
    growth_pct                       NUMERIC(6,2)              NULL,
    cw_incentive_trips_done          INTEGER                   NULL
);

-- TABLE: app_operators
CREATE TABLE IF NOT EXISTS app_operators (
    app_operator_id                  SERIAL                    PRIMARY KEY,
    operator_id                      INTEGER                   NULL,
    app_driver_id                    INTEGER                   NOT NULL,
    operator_code                    VARCHAR(30)               NULL,
    operator_type                    VARCHAR(20)               NULL,
    phone                            VARCHAR(15)               NULL UNIQUE,
    company_name                     VARCHAR(150)              NULL,
    contact_person_name              VARCHAR(150)              NULL,
    initials                         VARCHAR(5)                NULL,
    address                          TEXT                      NULL,
    total_vehicles                   INTEGER                   NULL,
    active_vehicles                  INTEGER                   NULL,
    idle_vehicles                    INTEGER                   NULL,
    total_drivers                    INTEGER                   NULL,
    deposit_total_req                NUMERIC(10,2)             NULL,
    deposit_paid                     NUMERIC(10,2)             NULL,
    deposit_pending                  NUMERIC(10,2)             NULL,
    assigned_manager_name            VARCHAR(150)              NULL,
    assigned_manager_phone           VARCHAR(15)               NULL,
    referral_code                    VARCHAR(30)               NULL UNIQUE,
    referral_reward_amt              NUMERIC(10,2)             NULL,
    contract_terms_url               TEXT                      NULL,
    upi_id                           VARCHAR(100)              NULL,
    bank_account_last4               VARCHAR(4)                NULL,
    password_hash                    VARCHAR(255)              NULL,
    fcm_token                        TEXT                      NULL,
    preferred_language               VARCHAR(5)                NULL,
    is_active                        BOOLEAN                   NULL DEFAULT FALSE,
    created_at                       TIMESTAMP WITH TIME ZONE  NULL DEFAULT NOW(),
    last_login_at                    TIMESTAMP WITH TIME ZONE  NULL,
    last_synced_at                   TIMESTAMP WITH TIME ZONE  NULL,
    cw_fleet_uber_trips              INTEGER                   NULL,
    cw_fleet_uber_revenue            NUMERIC(12,2)             NULL,
    cw_fleet_uber_cash               NUMERIC(12,2)             NULL,
    cw_fleet_uber_incentive          NUMERIC(12,2)             NULL,
    cw_fleet_uber_km                 NUMERIC(12,2)             NULL,
    cw_fleet_ola_trips               INTEGER                   NULL,
    cw_fleet_ola_revenue             NUMERIC(12,2)             NULL,
    cw_fleet_ola_cash                NUMERIC(12,2)             NULL,
    cw_fleet_ola_incentive           NUMERIC(12,2)             NULL,
    cw_fleet_ola_km                  NUMERIC(12,2)             NULL,
    cw_fleet_rapido_trips            INTEGER                   NULL,
    cw_fleet_rapido_revenue          NUMERIC(12,2)             NULL,
    cw_fleet_rapido_cash             NUMERIC(12,2)             NULL,
    cw_fleet_rapido_incentive        NUMERIC(12,2)             NULL,
    cw_fleet_rapido_km               NUMERIC(12,2)             NULL,
    cw_fleet_rent                    NUMERIC(12,2)             NULL,
    cw_fleet_maintenance             NUMERIC(12,2)             NULL,
    cw_fleet_tds                     NUMERIC(12,2)             NULL,
    cw_fleet_challans                NUMERIC(12,2)             NULL,
    cw_fleet_gps_dead_km             NUMERIC(10,2)             NULL,
    cw_fleet_gps_dead_penalty        NUMERIC(10,2)             NULL,
    cw_fleet_trips                   INTEGER                   NULL,
    cw_fleet_km                      NUMERIC(12,2)             NULL,
    cw_fleet_gross_earnings          NUMERIC(12,2)             NULL,
    cw_to_collect                    NUMERIC(12,2)             NULL,
    cw_to_pay                        NUMERIC(12,2)             NULL,
    cw_fleet_net_os                  NUMERIC(12,2)             NULL,
    cw_active_vehicles               INTEGER                   NULL,
    cw_active_drivers                INTEGER                   NULL,
    lw_fleet_trips                   INTEGER                   NULL,
    lw_fleet_km                      NUMERIC(12,2)             NULL,
    lw_fleet_gross_earnings          NUMERIC(12,2)             NULL,
    lw_fleet_net_os                  NUMERIC(12,2)             NULL,
    lw_week_number                   SMALLINT                  NULL,
    lw_hisaab_number                 VARCHAR(25)               NULL,
    lw_status                        VARCHAR(20)               NULL,
    growth_pct                       NUMERIC(6,2)              NULL
);

-- TABLE: app_hisaabs
CREATE TABLE IF NOT EXISTS app_hisaabs (
    app_hisaab_id                    SERIAL                    PRIMARY KEY,
    allocation_id                    INTEGER                   NULL,
    hisaab_id                        INTEGER                   NULL,
    app_driver_id                    INTEGER                   NOT NULL,
    app_operator_id                  INTEGER                   NOT NULL,
    vehicle_id                       INTEGER                   NULL,
    uber_earnings_id                 INTEGER                   NULL,
    ola_earnings_id                  INTEGER                   NULL,
    rapido_earnings_id               INTEGER                   NULL,
    hisaab_number                    VARCHAR(25)               NULL UNIQUE,
    week_number                      SMALLINT                  NULL,
    period_start                     DATE                      NULL,
    period_end                       DATE                      NULL,
    days_count                       SMALLINT                  NULL,
    status                           VARCHAR(20)               NULL,
    is_locked                        BOOLEAN                   NULL DEFAULT FALSE,
    growth_pct                       NUMERIC(6,2)              NULL,
    uber_trips                       INTEGER                   NULL,
    uber_revenue                     NUMERIC(12,2)             NULL,
    uber_cash                        NUMERIC(12,2)             NULL,
    uber_toll                        NUMERIC(12,2)             NULL,
    uber_incentive                   NUMERIC(12,2)             NULL,
    uber_subscription                NUMERIC(12,2)             NULL,
    uber_km                          NUMERIC(10,2)             NULL,
    ola_trips                        INTEGER                   NULL,
    ola_revenue                      NUMERIC(12,2)             NULL,
    ola_cash                         NUMERIC(12,2)             NULL,
    ola_toll                         NUMERIC(12,2)             NULL,
    ola_incentive                    NUMERIC(12,2)             NULL,
    ola_subscription                 NUMERIC(12,2)             NULL,
    ola_km                           NUMERIC(10,2)             NULL,
    rapido_trips                     INTEGER                   NULL,
    rapido_revenue                   NUMERIC(12,2)             NULL,
    rapido_cash                      NUMERIC(12,2)             NULL,
    rapido_toll                      NUMERIC(12,2)             NULL,
    rapido_incentive                 NUMERIC(12,2)             NULL,
    rapido_subscription              NUMERIC(12,2)             NULL,
    rapido_km                        NUMERIC(10,2)             NULL,
    vehicle_daily_rate               NUMERIC(10,2)             NULL,
    vehicle_rent                     NUMERIC(12,2)             NULL,
    maintenance_daily_rate           NUMERIC(10,2)             NULL,
    maintenance_charge               NUMERIC(12,2)             NULL,
    tds_amount                       NUMERIC(12,2)             NULL,
    challan_amount                   NUMERIC(12,2)             NULL,
    accident_charge                  NUMERIC(12,2)             NULL,
    other_adjustment                 NUMERIC(12,2)             NULL,
    previous_outstanding             NUMERIC(12,2)             NULL,
    gps_total_km                     NUMERIC(10,2)             NULL,
    gps_ideal_km                     NUMERIC(10,2)             NULL,
    gps_dead_km                      NUMERIC(10,2)             NULL,
    gps_dead_pct                     NUMERIC(5,2)              NULL,
    gps_dead_penalty                 NUMERIC(10,2)             NULL,
    gps_free_dead_pct                NUMERIC(5,2)              NULL,
    gps_penalty_rate                 NUMERIC(8,2)              NULL,
    completed_trips                  INTEGER                   NULL,
    total_km                         NUMERIC(10,2)             NULL,
    total_gross_earnings             NUMERIC(12,2)             NULL,
    total_deductions                 NUMERIC(12,2)             NULL,
    total_penalties                  NUMERIC(12,2)             NULL,
    current_period_os                NUMERIC(12,2)             NULL,
    to_pay                           NUMERIC(12,2)             NULL,
    to_collect                       NUMERIC(12,2)             NULL,
    letzryd_earning                  NUMERIC(12,2)             NULL,
    uber_last_synced_at              TIMESTAMP WITH TIME ZONE  NULL,
    ola_last_synced_at               TIMESTAMP WITH TIME ZONE  NULL,
    rapido_last_synced_at            TIMESTAMP WITH TIME ZONE  NULL,
    weekly_hisaab_due                NUMERIC(12,2)             NULL,
    last_refreshed_at                TIMESTAMP WITH TIME ZONE  NULL DEFAULT NOW(),
    notes                            TEXT                      NULL,
    last_synced_at                   TIMESTAMP WITH TIME ZONE  NULL,
    created_at                       TIMESTAMP WITH TIME ZONE  NULL DEFAULT NOW(),
    updated_at                       TIMESTAMP WITH TIME ZONE  NULL DEFAULT NOW()
);

-- TABLE: app_payments
CREATE TABLE IF NOT EXISTS app_payments (
    app_payment_id                   SERIAL                    PRIMARY KEY,
    payment_type                     VARCHAR(20)               NULL,
    payer_type                       VARCHAR(10)               NULL,
    payer_id                         INTEGER                   NULL,
    payee_type                       VARCHAR(10)               NULL,
    payee_id                         INTEGER                   NULL,
    app_hisaab_id                    INTEGER                   NOT NULL,
    amount                           NUMERIC(12,2)             NULL,
    payment_mode                     VARCHAR(20)               NULL,
    status                           VARCHAR(20)               NULL,
    cf_order_id                      VARCHAR(100)              NULL,
    cf_payment_id                    VARCHAR(100)              NULL,
    cf_payout_id                     VARCHAR(100)              NULL,
    raw_response                     JSONB                     NULL,
    initiated_at                     TIMESTAMP WITH TIME ZONE  NULL DEFAULT NOW(),
    completed_at                     TIMESTAMP WITH TIME ZONE  NULL
);

-- TABLE: app_support_tickets
CREATE TABLE IF NOT EXISTS app_support_tickets (
    app_ticket_id                    SERIAL                    PRIMARY KEY,
    ticket_number                    VARCHAR(25)               NULL UNIQUE,
    creator_type                     VARCHAR(10)               NULL,
    creator_id                       INTEGER                   NULL,
    category                         VARCHAR(50)               NULL,
    subject                          VARCHAR(255)              NULL,
    description                      TEXT                      NULL,
    priority                         VARCHAR(10)               NULL,
    status                           VARCHAR(20)               NULL,
    assigned_to                      VARCHAR(150)              NULL,
    resolution_note                  TEXT                      NULL,
    created_at                       TIMESTAMP WITH TIME ZONE  NULL DEFAULT NOW(),
    resolved_at                      TIMESTAMP WITH TIME ZONE  NULL
);

-- TABLE: app_sessions
CREATE TABLE IF NOT EXISTS app_sessions (
    app_session_id                   SERIAL                    PRIMARY KEY,
    user_type                        VARCHAR(10)               NULL,
    user_ref_id                      INTEGER                   NULL,
    phone                            VARCHAR(15)               NULL,
    otp_hash                         VARCHAR(255)              NULL,
    attempt_count                    SMALLINT                  NULL,
    is_verified                      BOOLEAN                   NULL DEFAULT FALSE,
    used_password                    BOOLEAN                   NULL DEFAULT FALSE,
    session_jwt                      TEXT                      NULL,
    fcm_token                        TEXT                      NULL,
    ip_address                       VARCHAR(45)               NULL,
    user_agent                       TEXT                      NULL,
    expires_at                       TIMESTAMP WITH TIME ZONE  NULL,
    created_at                       TIMESTAMP WITH TIME ZONE  NULL DEFAULT NOW()
);

-- TABLE: app_notifications
CREATE TABLE IF NOT EXISTS app_notifications (
    app_notif_id                     SERIAL                    PRIMARY KEY,
    target_type                      VARCHAR(10)               NULL,
    target_id                        INTEGER                   NULL,
    notif_type                       VARCHAR(20)               NULL,
    severity                         VARCHAR(10)               NULL,
    icon                             VARCHAR(50)               NULL,
    title                            VARCHAR(255)              NULL,
    message                          TEXT                      NULL,
    deep_link                        VARCHAR(100)              NULL,
    is_read                          BOOLEAN                   NULL DEFAULT FALSE,
    created_at                       TIMESTAMP WITH TIME ZONE  NULL DEFAULT NOW()
);

-- TABLE: app_referral_leads
CREATE TABLE IF NOT EXISTS app_referral_leads (
    app_referral_id                  SERIAL                    PRIMARY KEY,
    referred_by_type                 VARCHAR(10)               NULL,
    referred_by_driver_id            INTEGER                   NULL,
    referred_by_op_id                INTEGER                   NULL,
    lead_name                        VARCHAR(150)              NULL,
    lead_phone                       VARCHAR(15)               NULL,
    referral_code_used               VARCHAR(30)               NULL,
    status                           VARCHAR(25)               NULL,
    rides_completed                  INTEGER                   NULL,
    reward_amount                    NUMERIC(10,2)             NULL,
    reward_credited                  BOOLEAN                   NULL DEFAULT FALSE,
    reward_hisaab_id                 INTEGER                   NULL,
    submitted_at                     TIMESTAMP WITH TIME ZONE  NULL DEFAULT NOW(),
    joined_at                        TIMESTAMP WITH TIME ZONE  NULL,
    created_at                       TIMESTAMP WITH TIME ZONE  NULL DEFAULT NOW(),
    updated_at                       TIMESTAMP WITH TIME ZONE  NULL DEFAULT NOW()
);

-- TABLE: app_audit_logs
CREATE TABLE IF NOT EXISTS app_audit_logs (
    app_log_id                       SERIAL                    PRIMARY KEY,
    user_type                        VARCHAR(10)               NULL,
    user_ref_id                      INTEGER                   NULL,
    event_type                       VARCHAR(50)               NULL,
    phone                            VARCHAR(15)               NULL,
    ip_address                       VARCHAR(45)               NULL,
    device_id                        VARCHAR(255)              NULL,
    metadata                         JSONB                     NULL,
    created_at                       TIMESTAMP WITH TIME ZONE  NULL DEFAULT NOW()
);


-- ==========================================================================
-- RAW PLATFORM DATA TABLES (AUTOMATION PIPELINE TARGETS)
-- ==========================================================================

CREATE TABLE IF NOT EXISTS raw_uber_data (
    id                  SERIAL PRIMARY KEY,
    vehicle_number      VARCHAR(50),
    trip_id             VARCHAR(100),
    driver_name         VARCHAR(150),
    trip_date           DATE,
    week_start          DATE,
    week_end            DATE,
    trip_status         VARCHAR(50) DEFAULT 'completed',
    net_revenue         NUMERIC(12,2) DEFAULT 0.00,
    cash_collected      NUMERIC(12,2) DEFAULT 0.00,
    tolls               NUMERIC(12,2) DEFAULT 0.00,
    incentives          NUMERIC(12,2) DEFAULT 0.00,
    subscription_fee    NUMERIC(12,2) DEFAULT 0.00,
    distance_km         NUMERIC(10,2) DEFAULT 0.00,
    imported_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS raw_ola_data (
    id                  SERIAL PRIMARY KEY,
    vehicle_number      VARCHAR(50),
    crn                 VARCHAR(100),
    driver_name         VARCHAR(150),
    trip_date           DATE,
    week_start          DATE,
    week_end            DATE,
    completion_status   VARCHAR(50) DEFAULT 'Completed',
    net_revenue         NUMERIC(12,2) DEFAULT 0.00,
    cash_collected      NUMERIC(12,2) DEFAULT 0.00,
    tolls               NUMERIC(12,2) DEFAULT 0.00,
    incentives          NUMERIC(12,2) DEFAULT 0.00,
    subscription_fee    NUMERIC(12,2) DEFAULT 0.00,
    actual_kms          NUMERIC(10,2) DEFAULT 0.00,
    imported_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS raw_rapido_data (
    id                  SERIAL PRIMARY KEY,
    vehicle_number      VARCHAR(50),
    trip_id             VARCHAR(100),
    driver_name         VARCHAR(150),
    trip_date           DATE,
    week_start          DATE,
    week_end            DATE,
    net_revenue         NUMERIC(12,2) DEFAULT 0.00,
    cash_collected      NUMERIC(12,2) DEFAULT 0.00,
    tolls               NUMERIC(12,2) DEFAULT 0.00,
    incentives          NUMERIC(12,2) DEFAULT 0.00,
    distance_kms        NUMERIC(10,2) DEFAULT 0.00,
    imported_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS raw_uber_incentives (
    id                  SERIAL PRIMARY KEY,
    vehicle_number      VARCHAR(50),
    driver_name         VARCHAR(150),
    week_start          DATE,
    week_end            DATE,
    amount              NUMERIC(12,2) DEFAULT 0.00,
    trips_completed     INTEGER DEFAULT 0,
    imported_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS raw_ola_incentives (
    id                  SERIAL PRIMARY KEY,
    vehicle_number      VARCHAR(50),
    driver_name         VARCHAR(150),
    week_start          DATE,
    week_end            DATE,
    amount              NUMERIC(12,2) DEFAULT 0.00,
    trips_completed     INTEGER DEFAULT 0,
    imported_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS raw_rapido_incentives (
    id                  SERIAL PRIMARY KEY,
    vehicle_number      VARCHAR(50),
    driver_name         VARCHAR(150),
    week_start          DATE,
    week_end            DATE,
    amount              NUMERIC(12,2) DEFAULT 0.00,
    trips_completed     INTEGER DEFAULT 0,
    imported_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS raw_traffic_challans (
    id                  SERIAL PRIMARY KEY,
    vehicle_number      VARCHAR(50),
    challan_number      VARCHAR(100),
    driver_name         VARCHAR(150),
    violation_date      DATE,
    violation_location  TEXT,
    challan_amount      NUMERIC(12,2) DEFAULT 0.00,
    recovery_status     VARCHAR(50) DEFAULT 'pending',
    imported_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS raw_accidents_registry (
    id                  SERIAL PRIMARY KEY,
    vehicle_number      VARCHAR(50),
    driver_name         VARCHAR(150),
    date_of_accident    DATE,
    accident_reason     TEXT,
    place_of_accident   TEXT,
    repair_cost         NUMERIC(12,2) DEFAULT 0.00,
    fine_amount         NUMERIC(12,2) DEFAULT 0.00,
    approval_status     VARCHAR(50) DEFAULT 'Approved',
    imported_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS raw_partner_adjustments (
    id                  SERIAL PRIMARY KEY,
    vehicle_number      VARCHAR(50),
    partner_name        VARCHAR(150),
    partner_code        VARCHAR(50),
    adjustment_date     DATE,
    adjustment_type     VARCHAR(50),
    amount              NUMERIC(12,2) DEFAULT 0.00,
    remarks             TEXT,
    status              VARCHAR(50) DEFAULT 'Approved',
    imported_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS raw_gps_logs (
    id                  SERIAL PRIMARY KEY,
    vehicle_number      VARCHAR(50),
    gps_date            DATE,
    km_driven           NUMERIC(10,2) DEFAULT 0.00,
    status              VARCHAR(50) DEFAULT 'Active',
    imported_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
