from sqlalchemy import Column, Integer, String, Numeric, Boolean, Date, DateTime, Text, JSON, SmallInteger, ForeignKey, func
from app.database import Base

class AppDrivers(Base):
    __tablename__ = "app_drivers"

    app_driver_id = Column(Integer, primary_key=True, index=True)
    driver_id = Column(Integer, nullable=False)
    operator_id = Column(Integer, nullable=False, default=1)
    full_name = Column(String(150), nullable=False)
    phone = Column(String(15), nullable=False, unique=True)
    profile_photo_url = Column(Text, nullable=True)
    initials = Column(String(5), nullable=True)
    driver_code = Column(String(30), nullable=False)
    aadhar_number = Column(String(20), nullable=True)
    blood_group = Column(String(5), nullable=True)
    dob = Column(Date, nullable=True)
    address = Column(Text, nullable=True)
    joined_date = Column(Date, nullable=True)
    emergency_name = Column(String(150), nullable=True)
    emergency_relation = Column(String(50), nullable=True)
    emergency_phone = Column(String(15), nullable=True)
    dl_number = Column(String(50), nullable=True)
    dl_expiry = Column(Date, nullable=True)
    current_vehicle_id = Column(Integer, nullable=True)
    current_allocation_id = Column(Integer, nullable=True)
    vehicle_reg_number = Column(String(20), nullable=True)
    vehicle_make = Column(String(50), nullable=True)
    vehicle_model = Column(String(50), nullable=True)
    vehicle_variant = Column(String(50), nullable=True)
    vehicle_year = Column(SmallInteger, nullable=True)
    vehicle_color = Column(String(50), nullable=True)
    vehicle_fuel_type = Column(String(20), nullable=True)
    vehicle_odometer_km = Column(Integer, nullable=True, default=0)
    vehicle_allocated_from = Column(Date, nullable=True)
    vehicle_daily_rate = Column(Numeric(12,2), nullable=True, default=1000.0)
    rc_number = Column(String(50), nullable=True)
    rc_expiry = Column(Date, nullable=True)
    insurance_number = Column(String(50), nullable=True)
    insurance_expiry = Column(Date, nullable=True)
    permit_type = Column(String(50), nullable=True)
    permit_number = Column(String(50), nullable=True)
    permit_expiry = Column(Date, nullable=True)
    fitness_number = Column(String(50), nullable=True)
    fitness_expiry = Column(Date, nullable=True)
    puc_expiry = Column(Date, nullable=True)
    doc_last_updated = Column(Date, nullable=True)
    deposit_total_req = Column(Numeric(12,2), nullable=True, default=6000.0)
    deposit_paid = Column(Numeric(12,2), nullable=True, default=5000.0)
    deposit_pending = Column(Numeric(12,2), nullable=True, default=1000.0)
    deposit_next_due = Column(Date, nullable=True)
    joining_fee_agreed = Column(Numeric(12,2), nullable=True, default=1000.0)
    joining_fee_paid = Column(Numeric(12,2), nullable=True, default=1000.0)
    cumulative_owed = Column(Numeric(12,2), nullable=True, default=0.0)
    assigned_manager_name = Column(String(150), nullable=True)
    assigned_manager_phone = Column(String(15), nullable=True)
    incentive_trips_target = Column(Integer, nullable=True, default=260)
    incentive_reward_amt = Column(Numeric(12,2), nullable=True, default=1500.0)
    referral_code = Column(String(30), nullable=True)
    referral_reward_amt = Column(Numeric(12,2), nullable=True, default=1000.0)
    contract_terms_url = Column(Text, nullable=True)
    upi_id = Column(String(100), nullable=True)
    bank_account_last4 = Column(String(4), nullable=True)
    password_hash = Column(String(255), nullable=True)
    fcm_token = Column(Text, nullable=True)
    preferred_language = Column(String(5), nullable=True, default="en")
    is_active = Column(Boolean, nullable=True, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), default=func.now(), nullable=False)
    last_login_at = Column(DateTime(timezone=True), nullable=True)
    last_synced_at = Column(DateTime(timezone=True), nullable=True)
    cw_uber_trips = Column(Integer, nullable=True, default=0)
    cw_uber_revenue = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_uber_cash = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_uber_toll = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_uber_incentive = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_uber_subscription = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_uber_km = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_ola_trips = Column(Integer, nullable=True, default=0)
    cw_ola_revenue = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_ola_cash = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_ola_toll = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_ola_incentive = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_ola_subscription = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_ola_km = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_rapido_trips = Column(Integer, nullable=True, default=0)
    cw_rapido_revenue = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_rapido_cash = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_rapido_toll = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_rapido_incentive = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_rapido_subscription = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_rapido_km = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_vehicle_rent = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_maintenance_charge = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_active_days = Column(SmallInteger, nullable=True, default=0)
    cw_tds = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_challans = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_accident_charge = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_other_adjustment = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_previous_outstanding = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_gps_total_km = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_gps_ideal_km = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_gps_dead_km = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_gps_dead_pct = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_gps_dead_penalty = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_trips = Column(Integer, nullable=True, default=0)
    cw_total_km = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_gross_earnings = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_total_deductions = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_total_penalties = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_os = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_to_pay = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_to_collect = Column(Numeric(12,2), nullable=True, default=0.0)
    lw_trips = Column(Integer, nullable=True, default=0)
    lw_gross_earnings = Column(Numeric(12,2), nullable=True, default=0.0)
    lw_os = Column(Numeric(12,2), nullable=True, default=0.0)
    lw_week_number = Column(SmallInteger, nullable=True, default=0)
    lw_hisaab_number = Column(String(25), nullable=True, default="")
    lw_status = Column(String(20), nullable=True, default="unpaid")
    growth_pct = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_incentive_trips_done = Column(Integer, nullable=True, default=0)


class AppOperators(Base):
    __tablename__ = "app_operators"

    app_operator_id = Column(Integer, primary_key=True, index=True)
    operator_id = Column(Integer, nullable=False)
    app_driver_id = Column(Integer, nullable=True, default=0)
    operator_code = Column(String(30), nullable=False)
    operator_type = Column(String(20), nullable=False, default="Fleet Owner")
    phone = Column(String(15), nullable=False, unique=True)
    company_name = Column(String(150), nullable=False)
    contact_person_name = Column(String(150), nullable=True)
    initials = Column(String(5), nullable=True)
    address = Column(Text, nullable=True)
    total_vehicles = Column(Integer, nullable=True, default=0)
    active_vehicles = Column(Integer, nullable=True, default=0)
    idle_vehicles = Column(Integer, nullable=True, default=0)
    total_drivers = Column(Integer, nullable=True, default=0)
    deposit_total_req = Column(Numeric(12,2), nullable=True, default=0.0)
    deposit_paid = Column(Numeric(12,2), nullable=True, default=0.0)
    deposit_pending = Column(Numeric(12,2), nullable=True, default=0.0)
    assigned_manager_name = Column(String(150), nullable=True)
    assigned_manager_phone = Column(String(15), nullable=True)
    referral_code = Column(String(30), nullable=True)
    referral_reward_amt = Column(Numeric(12,2), nullable=True, default=2000.0)
    contract_terms_url = Column(Text, nullable=True)
    upi_id = Column(String(100), nullable=True)
    bank_account_last4 = Column(String(4), nullable=True)
    password_hash = Column(String(255), nullable=True)
    fcm_token = Column(Text, nullable=True)
    preferred_language = Column(String(5), nullable=True, default="en")
    is_active = Column(Boolean, nullable=True, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), default=func.now(), nullable=False)
    last_login_at = Column(DateTime(timezone=True), nullable=True)
    last_synced_at = Column(DateTime(timezone=True), nullable=True)
    cw_fleet_uber_trips = Column(Integer, nullable=True, default=0)
    cw_fleet_uber_revenue = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_uber_cash = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_uber_incentive = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_uber_km = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_ola_trips = Column(Integer, nullable=True, default=0)
    cw_fleet_ola_revenue = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_ola_cash = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_ola_incentive = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_ola_km = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_rapido_trips = Column(Integer, nullable=True, default=0)
    cw_fleet_rapido_revenue = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_rapido_cash = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_rapido_incentive = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_rapido_km = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_rent = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_maintenance = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_tds = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_challans = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_gps_dead_km = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_gps_dead_penalty = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_trips = Column(Integer, nullable=True, default=0)
    cw_fleet_km = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_gross_earnings = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_to_collect = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_to_pay = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_fleet_net_os = Column(Numeric(12,2), nullable=True, default=0.0)
    cw_active_vehicles = Column(Integer, nullable=True, default=0)
    cw_active_drivers = Column(Integer, nullable=True, default=0)
    lw_fleet_trips = Column(Integer, nullable=True, default=0)
    lw_fleet_km = Column(Numeric(12,2), nullable=True, default=0.0)
    lw_fleet_gross_earnings = Column(Numeric(12,2), nullable=True, default=0.0)
    lw_fleet_net_os = Column(Numeric(12,2), nullable=True, default=0.0)
    lw_week_number = Column(SmallInteger, nullable=True, default=0)
    lw_hisaab_number = Column(String(25), nullable=True, default="")
    lw_status = Column(String(20), nullable=True, default="unpaid")
    growth_pct = Column(Numeric(12,2), nullable=True, default=0.0)


class AppHisaabs(Base):
    __tablename__ = "app_hisaabs"

    app_hisaab_id = Column(Integer, primary_key=True, index=True)
    allocation_id = Column(Integer, nullable=False, default=1)
    hisaab_id = Column(Integer, nullable=False, default=1)
    app_driver_id = Column(Integer, nullable=False)
    app_operator_id = Column(Integer, nullable=False)
    vehicle_id = Column(Integer, nullable=False, default=1)
    uber_earnings_id = Column(Integer, nullable=True)
    ola_earnings_id = Column(Integer, nullable=True)
    rapido_earnings_id = Column(Integer, nullable=True)
    hisaab_number = Column(String(25), nullable=False)
    week_number = Column(SmallInteger, nullable=False)
    period_start = Column(Date, nullable=False)
    period_end = Column(Date, nullable=False)
    days_count = Column(SmallInteger, nullable=False, default=7)
    status = Column(String(20), nullable=False, default="in_progress")
    is_locked = Column(Boolean, nullable=False, default=False)
    growth_pct = Column(Numeric(12,2), nullable=True, default=0.0)
    uber_trips = Column(Integer, nullable=True, default=0)
    uber_revenue = Column(Numeric(12,2), nullable=True, default=0.0)
    uber_cash = Column(Numeric(12,2), nullable=True, default=0.0)
    uber_toll = Column(Numeric(12,2), nullable=True, default=0.0)
    uber_incentive = Column(Numeric(12,2), nullable=True, default=0.0)
    uber_subscription = Column(Numeric(12,2), nullable=True, default=0.0)
    uber_km = Column(Numeric(12,2), nullable=True, default=0.0)
    ola_trips = Column(Integer, nullable=True, default=0)
    ola_revenue = Column(Numeric(12,2), nullable=True, default=0.0)
    ola_cash = Column(Numeric(12,2), nullable=True, default=0.0)
    ola_toll = Column(Numeric(12,2), nullable=True, default=0.0)
    ola_incentive = Column(Numeric(12,2), nullable=True, default=0.0)
    ola_subscription = Column(Numeric(12,2), nullable=True, default=0.0)
    ola_km = Column(Numeric(12,2), nullable=True, default=0.0)
    rapido_trips = Column(Integer, nullable=True, default=0)
    rapido_revenue = Column(Numeric(12,2), nullable=True, default=0.0)
    rapido_cash = Column(Numeric(12,2), nullable=True, default=0.0)
    rapido_toll = Column(Numeric(12,2), nullable=True, default=0.0)
    rapido_incentive = Column(Numeric(12,2), nullable=True, default=0.0)
    rapido_subscription = Column(Numeric(12,2), nullable=True, default=0.0)
    rapido_km = Column(Numeric(12,2), nullable=True, default=0.0)
    vehicle_daily_rate = Column(Numeric(12,2), nullable=True, default=1000.0)
    vehicle_rent = Column(Numeric(12,2), nullable=True, default=0.0)
    maintenance_daily_rate = Column(Numeric(12,2), nullable=True, default=0.0)
    maintenance_charge = Column(Numeric(12,2), nullable=True, default=0.0)
    tds_amount = Column(Numeric(12,2), nullable=True, default=0.0)
    challan_amount = Column(Numeric(12,2), nullable=True, default=0.0)
    accident_charge = Column(Numeric(12,2), nullable=True, default=0.0)
    other_adjustment = Column(Numeric(12,2), nullable=True, default=0.0)
    previous_outstanding = Column(Numeric(12,2), nullable=True, default=0.0)
    gps_total_km = Column(Numeric(12,2), nullable=True, default=0.0)
    gps_ideal_km = Column(Numeric(12,2), nullable=True, default=0.0)
    gps_dead_km = Column(Numeric(12,2), nullable=True, default=0.0)
    gps_dead_pct = Column(Numeric(12,2), nullable=True, default=0.0)
    gps_dead_penalty = Column(Numeric(12,2), nullable=True, default=0.0)
    gps_free_dead_pct = Column(Numeric(12,2), nullable=True, default=20.0)
    gps_penalty_rate = Column(Numeric(12,2), nullable=True, default=5.0)
    completed_trips = Column(Integer, nullable=True, default=0)
    total_km = Column(Numeric(12,2), nullable=True, default=0.0)
    total_gross_earnings = Column(Numeric(12,2), nullable=True, default=0.0)
    total_deductions = Column(Numeric(12,2), nullable=True, default=0.0)
    total_penalties = Column(Numeric(12,2), nullable=True, default=0.0)
    current_period_os = Column(Numeric(12,2), nullable=True, default=0.0)
    to_pay = Column(Numeric(12,2), nullable=True, default=0.0)
    to_collect = Column(Numeric(12,2), nullable=True, default=0.0)
    letzryd_earning = Column(Numeric(12,2), nullable=True, default=0.0)
    uber_last_synced_at = Column(DateTime(timezone=True), nullable=True)
    ola_last_synced_at = Column(DateTime(timezone=True), nullable=True)
    rapido_last_synced_at = Column(DateTime(timezone=True), nullable=True)
    weekly_hisaab_due = Column(Numeric(12,2), nullable=True, default=0.0)
    last_refreshed_at = Column(DateTime(timezone=True), server_default=func.now(), default=func.now(), nullable=True)
    notes = Column(Text, nullable=True)
    last_synced_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), default=func.now(), onupdate=func.now(), nullable=False)


class AppPayments(Base):
    __tablename__ = "app_payments"

    app_payment_id = Column(Integer, primary_key=True, index=True)
    payment_type = Column(String(20), nullable=False, default="collection")
    payer_type = Column(String(10), nullable=False, default="driver")
    payer_id = Column(Integer, nullable=True)
    payee_type = Column(String(10), nullable=False, default="letzryd")
    payee_id = Column(Integer, nullable=True)
    app_hisaab_id = Column(Integer, nullable=True)
    amount = Column(Numeric(12,2), nullable=False, default=0.0)
    payment_mode = Column(String(20), nullable=False, default="cashfree_upi")
    status = Column(String(20), nullable=False, default="INITIATED")
    cf_order_id = Column(String(100), nullable=True)
    cf_payment_id = Column(String(100), nullable=True)
    cf_payout_id = Column(String(100), nullable=True)
    raw_response = Column(JSON, nullable=True)
    initiated_at = Column(DateTime(timezone=True), server_default=func.now(), default=func.now(), nullable=False)
    completed_at = Column(DateTime(timezone=True), nullable=True)


class AppSupportTickets(Base):
    __tablename__ = "app_support_tickets"

    app_ticket_id = Column(Integer, primary_key=True, index=True)
    ticket_number = Column(String(25), nullable=False)
    creator_type = Column(String(10), nullable=False, default="driver")
    creator_id = Column(Integer, nullable=False)
    category = Column(String(50), nullable=False)
    subject = Column(String(255), nullable=False)
    description = Column(Text, nullable=False)
    priority = Column(String(10), nullable=False, default="medium")
    status = Column(String(20), nullable=False, default="open")
    assigned_to = Column(String(150), nullable=True)
    resolution_note = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), default=func.now(), nullable=False)
    resolved_at = Column(DateTime(timezone=True), nullable=True)


class AppSessions(Base):
    __tablename__ = "app_sessions"

    app_session_id = Column(Integer, primary_key=True, index=True)
    user_type = Column(String(10), nullable=False)
    user_ref_id = Column(Integer, nullable=False)
    phone = Column(String(15), nullable=False)
    otp_hash = Column(String(255), nullable=False)
    attempt_count = Column(SmallInteger, nullable=False, default=0)
    is_verified = Column(Boolean, nullable=False, default=False)
    used_password = Column(Boolean, nullable=False, default=False)
    session_jwt = Column(Text, nullable=True)
    fcm_token = Column(Text, nullable=True)
    ip_address = Column(String(45), nullable=True)
    user_agent = Column(Text, nullable=True)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), default=func.now(), nullable=False)


class AppNotifications(Base):
    __tablename__ = "app_notifications"

    app_notif_id = Column(Integer, primary_key=True, index=True)
    target_type = Column(String(10), nullable=False, default="driver")
    target_id = Column(Integer, nullable=True)
    notif_type = Column(String(20), nullable=False, default="hisaab")
    severity = Column(String(10), nullable=True, default="info")
    icon = Column(String(50), nullable=True)
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    deep_link = Column(String(100), nullable=True)
    is_read = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), default=func.now(), nullable=False)


class AppReferralLeads(Base):
    __tablename__ = "app_referral_leads"

    app_referral_id = Column(Integer, primary_key=True, index=True)
    referred_by_type = Column(String(10), nullable=False, default="driver")
    referred_by_driver_id = Column(Integer, nullable=True)
    referred_by_op_id = Column(Integer, nullable=True)
    lead_name = Column(String(150), nullable=False)
    lead_phone = Column(String(15), nullable=False)
    referral_code_used = Column(String(30), nullable=True)
    status = Column(String(25), nullable=False, default="submitted")
    rides_completed = Column(Integer, nullable=False, default=0)
    reward_amount = Column(Numeric(12,2), nullable=False, default=1000.0)
    reward_credited = Column(Boolean, nullable=False, default=False)
    reward_hisaab_id = Column(Integer, nullable=True)
    submitted_at = Column(DateTime(timezone=True), server_default=func.now(), default=func.now(), nullable=False)
    joined_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), default=func.now(), onupdate=func.now(), nullable=False)


class AppAuditLogs(Base):
    __tablename__ = "app_audit_logs"

    app_log_id = Column(Integer, primary_key=True, index=True)
    user_type = Column(String(10), nullable=False)
    user_ref_id = Column(Integer, nullable=True)
    event_type = Column(String(50), nullable=False)
    phone = Column(String(15), nullable=True)
    ip_address = Column(String(45), nullable=True)
    device_id = Column(String(255), nullable=True)
    metadata_payload = Column('metadata', JSON, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), default=func.now(), nullable=False)

