/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { User, Vehicle, RentalPlan, HisaabWeek, Fleet, Ticket, Notification, Announcement } from './types';

export interface DemoProfile {
  name: string;
  phone: string;
  role: 'driver' | 'operator';
  tag: string;
  otp: string;
  user: User;
  weeks: HisaabWeek[];
}

export const USER_DATA: User = {
  id: "LR-DRV-0157",
  name: "Rajesh Kumar",
  operatorCode: "VND0157",
  phone: "9876543210",
  joined: "2024-10-15",
  initials: "RK",
  aadhar: "1234-5678-9012",
  dlNumber: "KA05-2024-1234567",
  dlExpiry: "2029-05-20",
  emergencyContact: "Priya Kumar (Wife) - 9876543211",
  address: "No. 42, 3rd Cross, Indiranagar, Bangalore - 560038",
  bloodGroup: "B+",
  dob: "1992-08-14",
  operatorType: "Individual Driver",
  assignedManagerName: "Ramesh Naik",
  assignedManagerPhone: "9876543299",
  depositAmount: 6000,
  depositTotalRequired: 6000,
  depositPaidSoFar: 5000,
  depositPending: 1000,
  depositNextDueDate: "2026-08-05",
  cumulativeOwed: 3265.80,
  weeklyIncentiveTargetTrips: 260,
  completedTripsThisWeek: 233,
  weeklyIncentiveReward: 1500
};

export const VEHICLE_DATA: Vehicle = {
  number: "KA 05 AQ 7692",
  make: "Maruti Suzuki",
  model: "Dzire",
  variant: "ZXi CNG",
  year: 2021,
  color: "White Pearl",
  fuelType: "CNG",
  odometer: 124380,
  fitnessExpiry: "2026-10-12",
  insuranceExpiry: "2027-03-20",
  rcExpiry: "2036-05-01",
  permitType: "Tourist Permit",
  permitExpiry: "2026-12-31",
  pucExpiry: "2026-08-15",
  lastUpdatedOn: "2026-07-24",
  platforms: {
    uber: { status: "active", rating: 4.82, trips: 3210 },
    ola: { status: "active", rating: 4.65, trips: 890 },
    rapido: { status: "active", rating: 4.71, trips: 1540 }
  },
  allocationStart: "2024-10-15"
};

export const RENTAL_PLAN_DATA: RentalPlan = {
  name: "Standard",
  dailyRate: 1000,
  planStart: "2024-10-15",
  activeMonths: 20,
  note: "Standard EV Rental Plan: ₹1,000/active operating day. Includes battery charging credits."
};

export const ANNOUNCEMENTS_DATA: Announcement[] = [
  {
    id: "ANN-01",
    title: "Urgent Hub Vehicle Inspection Required",
    message: "Mandatory EV battery telemetry audit at Hitec City Hub before Thursday 5:00 PM.",
    severity: "warning",
    date: "2026-07-27"
  }
];

export const HISAAB_WEEKS_DATA: HisaabWeek[] = [
  {
    weekNumber: 30,
    hisaabNumber: "HIS-2026-030",
    weekStart: "2026-06-22",
    weekEnd: "2026-06-28",
    status: "in_progress",
    isLocked: false,
    activeDays: 4,
    growthPct: 12.5,
    platforms: {
      uber: { trips: 120, revenue: 15800, cashCollection: -10500, toll: 420, incentive: 3200, subscription: -1500, km: 1250 },
      ola: { trips: 65, revenue: 6800, cashCollection: -4200, toll: 180, incentive: 1200, subscription: -900, km: 680 },
      rapido: { trips: 48, revenue: 5200, cashCollection: -2800, toll: 90, incentive: 850, subscription: -390, km: 511 }
    },
    rent: { dailyRate: 1000, netWeeklyRent: 4000 },
    dailyMaintenance: 200,
    previousAdjustments: 0,
    tds: 154.20,
    challan: 0,
    accident: 0,
    adjustment: 0,
    paidDeposit: 5000,
    pendingDeposit: 0,
    joiningFeePaid: 1000,
    pendingJoiningFee: 0,
    previousOutstanding: 0,
    pendingSinceDate: "2026-06-22",
    gps: {
      totalGpsKm: 3200.80,
      idealGpsKm: 3820.60,
      deadMile: 0.00,
      deadMilePct: 0,
      deadKmPenalty: 0,
      allowedFreeDeadKmPct: 20,
      penaltyRatePerKm: 5
    },
    lastRefreshedTime: "2026-07-28 02:15 PM",
    currentWeekOs: -3265.80,
    pendingDue: 0,
    totalOs: -3265.80,
    toCollect: 0,
    toPay: 3265.80,
    letzrydEarning: 4000,
    notes: "Current active week in progress. Net payout of ₹3,265.80 payable to driver."
  },
  {
    weekNumber: 29,
    hisaabNumber: "HIS-2026-029",
    weekStart: "2026-06-15",
    weekEnd: "2026-06-21",
    status: "to_collect",
    isLocked: true,
    activeDays: 6,
    growthPct: -4.2,
    platforms: {
      uber: { trips: 198, revenue: 22300, cashCollection: -18900, toll: 680, incentive: 4500, subscription: -2200, km: 1950 },
      ola: { trips: 88, revenue: 9400, cashCollection: -6800, toll: 240, incentive: 1800, subscription: -1200, km: 890 },
      rapido: { trips: 62, revenue: 6800, cashCollection: -4100, toll: 120, incentive: 1100, subscription: -650, km: 620 }
    },
    rent: { dailyRate: 1000, netWeeklyRent: 6000 },
    dailyMaintenance: 300,
    previousAdjustments: -250,
    tds: 284.40,
    challan: 500,
    accident: 0,
    adjustment: 0,
    paidDeposit: 5000,
    pendingDeposit: 0,
    joiningFeePaid: 1000,
    pendingJoiningFee: 0,
    previousOutstanding: 0,
    pendingSinceDate: "2026-06-21",
    gps: {
      totalGpsKm: 3460.00,
      idealGpsKm: 3460.00,
      deadMile: 0,
      deadMilePct: 0,
      deadKmPenalty: 0,
      allowedFreeDeadKmPct: 20,
      penaltyRatePerKm: 5
    },
    lastRefreshedTime: "2026-06-22 10:00 AM",
    currentWeekOs: 1034.80,
    pendingDue: 1034.80,
    totalOs: 1034.80,
    toCollect: 1034.80,
    toPay: 0,
    letzrydEarning: 6000,
    notes: "Locked Past Week. Pending due ₹1,034.80 owed by driver."
  }
];

export const DEMO_PROFILES: DemoProfile[] = [
  {
    name: "Rajesh Kumar",
    phone: "9876543210",
    role: "driver",
    tag: "Paid Last Week (₹0.00)",
    otp: "1234",
    user: USER_DATA,
    weeks: [
      { ...HISAAB_WEEKS_DATA[0] },
      { ...HISAAB_WEEKS_DATA[1], isLocked: true, status: 'settled_pay', currentWeekOs: 0 }
    ]
  },
  {
    name: "Suresh Sharma",
    phone: "9876543211",
    role: "driver",
    tag: "Unpaid Last Week (-₹1,034.80)",
    otp: "1234",
    user: {
      ...USER_DATA,
      id: "LR-DRV-0294",
      name: "Suresh Sharma",
      operatorCode: "VND0294",
      phone: "9876543211",
      initials: "SS",
      depositAmount: 6000,
      depositTotalRequired: 6000,
      depositPaidSoFar: 5000,
      depositPending: 1000,
      depositNextDueDate: "2026-08-05",
      cumulativeOwed: 2884.80
    },
    weeks: [
      { ...HISAAB_WEEKS_DATA[0], currentWeekOs: 1850.00, pendingDeposit: 0 },
      { ...HISAAB_WEEKS_DATA[1], isLocked: false, status: 'to_collect', currentWeekOs: 1034.80, pendingDeposit: 1000 }
    ]
  },
  {
    name: "RK Transport",
    phone: "9876543222",
    role: "operator",
    tag: "Fleet Operator",
    otp: "1234",
    user: {
      ...USER_DATA,
      id: "OPR-HYD-004",
      name: "RK Transport & Fleet",
      operatorCode: "OPR-HYD-004",
      phone: "9876543222",
      initials: "RK",
      operatorType: "Fleet Owner"
    },
    weeks: HISAAB_WEEKS_DATA
  }
];

export const OPERATOR_FLEET_DATA: Fleet = {
  operatorCode: "OPR-HYD-004",
  operatorName: "RK Transport & Fleet Logistics",
  depositTotalRequired: 25000,
  depositPaidSoFar: 20000,
  depositPending: 5000,
  vehicles: [
    {
      number: "KA05AQ7692",
      make: "Maruti Suzuki",
      model: "Dzire CNG",
      driverName: "Rajesh Kumar",
      plan: { name: "Standard", dailyRate: 1000 },
      currentWeekOs: -3265.80,
      status: "active",
      hisaabWeeks: HISAAB_WEEKS_DATA
    },
    {
      number: "TS09EV8812",
      make: "Tata",
      model: "Tigor EV",
      driverName: "Suresh Reddy",
      plan: { name: "Standard", dailyRate: 1000 },
      currentWeekOs: 1450.00,
      status: "active",
      hisaabWeeks: HISAAB_WEEKS_DATA
    },
    {
      number: "TS07EV4401",
      make: "Mahindra",
      model: "eVerito",
      driverName: "Vikram Singh",
      plan: { name: "Standard", dailyRate: 1000 },
      currentWeekOs: 0,
      status: "active",
      hisaabWeeks: HISAAB_WEEKS_DATA
    },
    {
      number: "TS08EV1129",
      make: "Tata",
      model: "XPRES-T EV",
      driverName: "Mohammed Ali",
      plan: { name: "Standard", dailyRate: 1000 },
      currentWeekOs: -1820.50,
      status: "active",
      hisaabWeeks: HISAAB_WEEKS_DATA
    },
    {
      number: "TS09EV9900",
      make: "BYD",
      model: "e6 EV",
      driverName: "Anil Verma",
      plan: { name: "Standard", dailyRate: 1000 },
      currentWeekOs: 0,
      status: "idle",
      hisaabWeeks: HISAAB_WEEKS_DATA
    }
  ]
};

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: "TKT-2026-0041",
    category: "Hisaab Dispute",
    subject: "Traffic Challan incorrectly charged on 18th Jun",
    description: "A challan of ₹500 was charged for speed violation on MG Road on Jun 18. I was off-duty and vehicle was parked.",
    status: "open",
    priority: "high",
    date: "2026-06-22",
    response: null
  },
  {
    id: "TKT-2026-0028",
    category: "Vehicle Maintenance",
    subject: "AC compressor cooling issue",
    description: "AC in vehicle KA05AQ7692 is blowing warm air when parked. Urgent servicing required.",
    status: "resolved",
    priority: "medium",
    date: "2026-06-10",
    response: "Serviced at Hitec City Hub on Jun 12. AC refrigerant refilled."
  }
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: "NOTIF-01",
    icon: "ReceiptIndianRupee",
    title: "Weekly Payout Calculated",
    message: "Estimated payout of ₹3,265.80 ready for Sunday clearance.",
    time: "2 hours ago",
    read: false
  },
  {
    id: "NOTIF-02",
    icon: "FileWarning",
    title: "Hub Inspection Notice",
    message: "Mandatory battery telemetry audit at Hitec City Hub before Thursday.",
    time: "1 day ago",
    read: false
  }
];

export const SUPPORT_HOTLINE = "0800-053-8793";
export const LETZRYD_UPI_ID = "letzryd@ybl";
export const TICKET_CATEGORIES = [
  "Hisaab Dispute",
  "Vehicle Maintenance",
  "App / Platform Issue",
  "Challan Dispute",
  "Other"
];

/* =========================================================================
   COMPREHENSIVE 5-LANGUAGE LOCALIZATION DICTIONARIES
   ========================================================================= */

export const TRANSLATIONS_EN: Record<string, string> = {
  "app.title": "LetzRyd Portal",
  "app.subtitle": "Drive in the Future of Urban Mobility.",
  "login.selectRole": "Enter Mobile Number to Login",
  "login.driver": "Driver Login",
  "login.operator": "Operator Login",
  "login.enterPhone": "Enter 10-Digit Mobile Number",
  "login.sendOtp": "Get OTP",
  "login.enterOtp": "Enter 4-Digit OTP",
  "login.verifyOtp": "Verify & Enter Portal",
  "home.greeting": "Hi",
  "home.summary": "Here's your weekly settlement at a glance",
  "home.estimatedPayout": "ESTIMATED PAYOUT",
  "home.thisWeek": "THIS WEEK",
  "home.payoutToDriver": "LetzRyd payout to driver",
  "home.dueToLetzryd": "Due to be paid to LetzRyd",
  "home.daysActive": "Days Active",
  "home.trips": "Trips",
  "home.totalKm": "Total KMs",
  "home.deadMilesPct": "Dead Miles %",
  "home.settleNow": "Settle via Cashfree / UPI",
  "home.quickAccess": "Quick Access Shortcuts",
  "home.currentHisaab": "Current Hisaab",
  "home.lastWeekHisaab": "Last Week Hisaab",
  "home.raiseTicket": "Raise Support Ticket",
  "home.referDriver": "Refer & Earn ₹1,000",
  "home.payLetzryd": "Pay Dues Direct",
  "home.incentiveTracker": "Weekly Incentive Goal",
  "home.announcements": "Important LetzRyd Announcement",
  "home.deposit": "Security Deposit",
  "home.cumulativeOwed": "Cumulative Money Owed",
  "hisaab.title": "Weekly Hisaab Statement",
  "hisaab.weekIndex": "Week",
  "hisaab.of": "of",
  "hisaab.inProgress": "In Progress",
  "hisaab.locked": "Locked Past Hisaab",
  "hisaab.earnings": "Earnings",
  "hisaab.tripsCompleted": "Trips Completed",
  "hisaab.digitalEarnings": "Digital Earnings",
  "hisaab.cashCollected": "Cash Collected",
  "hisaab.tollPassThrough": "Toll Refund",
  "hisaab.incentives": "Platform Incentives",
  "hisaab.subscriptionDeduction": "Platform Fee / Subscription",
  "hisaab.vehicleRent": "Vehicle Rent",
  "hisaab.dailyMaintenance": "Daily Maintenance Charge",
  "hisaab.prevAdjustments": "Previous Adjustments",
  "hisaab.tds": "TDS Deduction (1%)",
  "hisaab.paidDeposit": "Paid Deposit",
  "hisaab.pendingDeposit": "Pending Deposit",
  "hisaab.joiningFeePaid": "Joining Fee Paid",
  "hisaab.pendingJoiningFee": "Pending Joining Fee",
  "hisaab.previousOutstanding": "Previous Outstanding",
  "hisaab.gpsRefreshedAt": "Last Refreshed At",
  "hisaab.disputeNotice": "Hisaab disputes can be raised Mon–Thu. Changes after Thursday apply to next week.",
  "settle.title": "Settle Weekly Hisaab",
  "settle.forWeek": "Settlement Period:",
  "settle.copy": "Copy UPI ID",
  "settle.iHavePaid": "I Have Paid (Manual)",
  "settle.backToHisaab": "Back to Hisaab",
  "vehicle.title": "Vehicle Details",
  "vehicle.subtitle": "",
  "vehicle.documents": "DOCUMENTS",
  "vehicle.specifications": "SPECIFICATIONS",
  "vehicle.lastUpdated": "Last Updated On",
  "support.title": "Support Desk",
  "support.subtitle": "Contact manager or raise tickets",
  "support.manager": "MANAGER",
  "support.newTicket": "Raise New Ticket",
  "profile.title": "User Profile & Identity",
  "profile.subtitle": "Personal information, credentials, and registered contact details",
  "profile.edit": "Edit Profile",
  "profile.saved": "Profile updated successfully!",
  "sos.title": "Emergency SOS Safety Center",
  "sos.subtitle": "Press emergency button to transmit real-time coordinates to dispatch.",
  "sos.confirm": "Trigger Emergency SOS alert? This will immediately notify LetzRyd Central Control Hub.",
  "sos.pressToAlert": "Press to Alert Hub",
  "sos.reportAccident": "Report Accident or Roadside Breakdown",
  "sos.location": "Current Location / Nearest Landmark",
  "sos.locationPlaceholder": "e.g. Near Hitec City Metro Station, Outer Ring Road",
  "sos.activated": "Emergency SOS Active!",
  "refer.title": "Refer Driver & Earn ₹1,000",
  "refer.subtitle": "Share your referral link with EV drivers joining LetzRyd.",
  "nav.home": "Home",
  "nav.hisaab": "Hisaab",
  "nav.settle": "Settle",
  "nav.vehicle": "Vehicle",
  "nav.fleet": "Fleet",
  "nav.support": "Support",
  "home.vehicle": "Vehicle",
  "home.vehicleNumber": "Vehicle Number",
  "home.vehicleModel": "Vehicle Model",
  "home.week": "Week",
  "home.vsLastWeek": "vs last week",
  "home.bonus": "Bonus",
  "home.tripsRemaining": "trips remaining",
  "home.toUnlockBonus": "to unlock ₹1,500 bonus",
    "home.paid": "Paid:",
  "home.pending": "Pending:",
  "home.settlement": "SETTLEMENT",
  "home.balanceDue": "Balance Due",
  "home.paidToLetzryd": "Paid to LetzRyd",
  "home.paidToBank": "Paid to Bank",
  "home.totalOutstandingDue": "Total Outstanding Due",
  "home.due": "Due",
  "home.supportDeskSub": "Support desk",
  "home.earnBonusSub": "Earn bonus",
  "hisaab.completed": "Completed",
  "hisaab.netPayout": "NET DRIVER PAYOUT",
  "hisaab.netDue": "NET AMOUNT DUE",
  "hisaab.breakdownTitle": "HISAAB BREAKDOWN",
  "hisaab.driverHoldsFares": "Driver holds fares",
  "hisaab.rides": "rides",
  "hisaab.toDate": "TO",
  "hisaab.othersTitle": "Others",
  "hisaab.gpsDeadMiles": "GPS Dead Miles",
  "hisaab.totalGpsTracked": "Total GPS Tracked KM",
  "hisaab.idealTripKm": "Ideal Trip KM",
  "hisaab.excessDeadMiles": "Excess Dead Miles",
  "hisaab.deadMilePenalty": "Dead Mile Penalty Due",
  "vehicle.specificationsTitle": "SPECIFICATIONS",
  "vehicle.brand": "Brand",
  "vehicle.model": "Model",
  "vehicle.variant": "Variant",
  "vehicle.regYear": "Registration Year",
  "vehicle.updated": "Updated",
  "vehicle.rc": "Registration Certificate (RC)",
  "vehicle.insurance": "Insurance",
  "vehicle.permit": "Permit",
  "vehicle.fc": "Fitness Certificate (FC)",
  "vehicle.expires": "Expires",
  "support.open": "Open",
  "support.resolved": "Resolved",
  "support.dispute": "Hisaab Dispute",
  "support.maintenance": "Vehicle Maintenance",
  "operator.operatorId": "Operator ID:",
  "operator.totalCars": "Total Cars:",
  "operator.active": "Active",
  "operator.toPay": "TO PAY",
  "operator.toCollect": "TO COLLECT",
  "operator.cars": "CARS",
  "operator.drivers": "Drivers",
  "operator.vehicles": "Vehicles",
  "operator.fleetDeposit": "FLEET SECURITY DEPOSIT",
  "operator.toPayDriver": "To Pay Driver:",
  "operator.driverOwes": "Driver Owes:",
  "settle.selectOption": "SELECT PAYMENT OPTION",
  "settle.full": "Full",
  "settle.partPay": "Part Pay",
  "settle.advance": "Advance",
  "settle.amountToPay": "Amount to Pay (₹)",
  "settle.payBtn": "Pay",
    "name.Rajesh": "Rajesh",
  "name.Suresh": "Suresh",
  "name.Vikram": "Vikram",
  "name.Mohammed": "Mohammed",
  "name.Anil": "Anil",
  "name.RK": "RK Transport",
  "name.Ramesh": "Ramesh",
  "refer.yourCode": "YOUR REFERRAL CODE",
  "refer.copyCode": "Copy Code",
  "refer.rewardInfo": "Receive ₹1,000 credit directly in your next weekly Hisaab when your referred driver completes 50 rides."
};

export const TRANSLATIONS_HI: Record<string, string> = {
  "app.title": "लेत्ज़रॉइड पोर्टल",
  "app.subtitle": "Drive in the Future of Urban Mobility.",
  "login.selectRole": "लॉगिन करने के लिए मोबाइल नंबर दर्ज करें",
  "login.driver": "ड्राइवर लॉगिन",
  "login.operator": "ऑपरेटर लॉगिन",
  "login.enterPhone": "10-अंकों का मोबाइल नंबर दर्ज करें",
  "login.sendOtp": "ओटीपी प्राप्त करें",
  "login.enterOtp": "4-अंकों का ओटीपी दर्ज करें",
  "login.verifyOtp": "सत्यापित करें और प्रवेश करें",
  "login.changeNumber": "मोबाइल नंबर बदलें",
  "home.greeting": "नमस्कार",
  "home.summary": "यह रहा आपका साप्ताहिक हिसाब",
  "home.estimatedPayout": "इस सप्ताह का अनुमानित नेट भुगतान",
  "home.payoutToDriver": "लेत्ज़रॉइड द्वारा ड्राइवर को भुगतान",
  "home.dueToLetzryd": "लेत्ज़रॉइड को देय राशि",
  "home.daysActive": "सक्रिय दिन",
  "home.trips": "कुल यात्राएं",
  "home.totalKm": "कुल किलोमीटर",
  "home.deadMilesPct": "डेड माइल्स %",
  "home.settleNow": "कैशफ्री / यूपीआई से भुगतान करें",
  "home.quickAccess": "त्वरित शॉर्टकट",
  "home.currentHisaab": "वर्तमान हिसाब",
  "home.lastWeekHisaab": "पिछले सप्ताह का हिसाब",
  "home.raiseTicket": "सहायता टिकट दर्ज करें",
  "home.referDriver": "रेफर करें और ₹1,000 कमाएं",
  "home.payLetzryd": "सीधा भुगतान करें",
  "home.incentiveTracker": "साप्ताहिक प्रोत्साहन लक्ष्य",
  "home.announcements": "महत्वपूर्ण लेत्ज़रॉइड घोषणा",
  "home.deposit": "सुरक्षा जमा राशि",
  "home.cumulativeOwed": "कुल बकाया राशि",
  "hisaab.title": "साप्ताहिक हिसाब विवरण",
  "hisaab.weekIndex": "सप्ताह",
  "hisaab.of": "का",
  "hisaab.inProgress": "प्रगति में",
  "hisaab.locked": "पुराना हिसाब (लॉक)",
  "hisaab.earnings": "कुल कमाई",
  "hisaab.tripsCompleted": "पूर्ण यात्राएं",
  "hisaab.digitalEarnings": "डिजिटल कमाई",
  "hisaab.cashCollected": "नकद संग्रह",
  "hisaab.tollPassThrough": "टोल रिफंड",
  "hisaab.incentives": "प्लेटफॉर्म इंसेंटिव",
  "hisaab.subscriptionDeduction": "प्लेटफॉर्म शुल्क",
  "hisaab.vehicleRent": "वाहन किराया",
  "hisaab.dailyMaintenance": "दैनिक रखरखाव शुल्क",
  "hisaab.prevAdjustments": "अन्य बकाया और समायोजन",
  "hisaab.tds": "टीडीएस कटौती (1%)",
  "hisaab.paidDeposit": "जमा की गई राशि",
  "hisaab.pendingDeposit": "बकाया जमा राशि",
  "hisaab.joiningFeePaid": "ज्वाइनिंग शुल्क जमा",
  "hisaab.pendingJoiningFee": "बकाया ज्वाइनिंग शुल्क",
  "hisaab.previousOutstanding": "पिछला बकाया",
  "hisaab.gpsRefreshedAt": "अंतिम अपडेट समय",
  "hisaab.disputeNotice": "हिसाब विवाद सोमवार-गुरुवार दर्ज करें।",
  "settle.title": "साप्ताहिक हिसाब चुकता करें",
  "settle.forWeek": "साप्ताहिक अवधि:",
  "settle.copy": "यूपीआई आईडी कॉपी करें",
  "settle.iHavePaid": "मैंने भुगतान कर दिया है",
  "settle.backToHisaab": "हिसाब पर वापस जाएं",
  "vehicle.title": "वाहन विवरण एवं दस्तावेज़",
  "vehicle.subtitle": "विनिर्देश, वैधता स्थिति और प्लेटफॉर्म अनुमति",
  "vehicle.lastUpdated": "अंतिम अपडेट तिथि",
  "support.title": "सहायता केंद्र",
  "support.subtitle": "अपने ड्राइवर मैनेजर से संपर्क करें या नया टिकट बनाएं",
  "support.manager": "आवंटित ड्राइवर मैनेजर",
  "support.newTicket": "नया टिकट बनाएं",
  "profile.title": "प्रोफ़ाइल एवं पहचान",
  "profile.subtitle": "व्यक्तिगत जानकारी और क्रेडेंशियल",
  "profile.edit": "प्रोफ़ाइल संपादित करें",
  "profile.saved": "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!",
  "refer.title": "ड्राइवर को रेफर करें और ₹1,000 कमाएं",
  "refer.subtitle": "लेत्ज़रॉइड से जुड़ने वाले ईवी ड्राइवरों के साथ अपना लिंक साझा करें।",
  "nav.home": "होम",
  "nav.hisaab": "हिसाब",
  "nav.settle": "सेटल",
  "nav.vehicle": "वाहन",
  "nav.fleet": "फ्लैट",
  "nav.support": "सहायता",
  "home.vehicle": "वाहन",
  "home.week": "सप्ताह",
  "home.vsLastWeek": "पिछले सप्ताह की तुलना में",
  "home.bonus": "बोनस",
  "home.tripsRemaining": "यात्राएं शेष",
  "home.toUnlockBonus": "₹1,500 बोनस अनलॉक करने के लिए",
    "home.paid": "जमा:",
  "home.pending": "बकाया:",
  "home.settlement": "सेटलमेंट",
  "home.balanceDue": "शेष बकाया",
  "home.paidToLetzryd": "लेत्ज़राइड को भुगतान किया गया",
  "home.paidToBank": "बैंक में जमा किया गया",
  "home.totalOutstandingDue": "कुल बकाया राशि",
  "home.due": "बकाया",
  "home.supportDeskSub": "सहायता डेस्क",
  "home.earnBonusSub": "बोनस कमाएं",
  "hisaab.completed": "पूर्ण",
  "hisaab.netPayout": "ड्राइवर का कुल भुगतान",
  "hisaab.netDue": "कुल देय राशि",
  "hisaab.breakdownTitle": "हिसाब विवरण",
  "hisaab.driverHoldsFares": "ड्राइवर के पास किराया",
  "hisaab.rides": "राइड्स",
  "hisaab.toDate": "से",
  "hisaab.othersTitle": "अन्य",
  "hisaab.gpsDeadMiles": "जीपीएस डेड माइल्स",
  "hisaab.totalGpsTracked": "कुल जीपीएस ट्रैक किए गए किलोमीटर",
  "hisaab.idealTripKm": "आदर्श ट्रिप किलोमीटर",
  "hisaab.excessDeadMiles": "अतिरिक्त डेड माइल्स",
  "hisaab.deadMilePenalty": "डेड माइल जुर्माना देय",
  "vehicle.specificationsTitle": "विनिर्देश",
  "vehicle.brand": "ब्रांड",
  "vehicle.model": "मॉडल",
  "vehicle.variant": "वेरिएंट",
  "vehicle.regYear": "पंजीकरण वर्ष",
  "vehicle.updated": "अपडेट किया गया",
  "vehicle.rc": "पंजीकरण प्रमाणपत्र (आरसी)",
  "vehicle.insurance": "बीमा",
  "vehicle.permit": "परमिट",
  "vehicle.fc": "फिटनेस प्रमाणपत्र (एफसी)",
  "vehicle.expires": "समाप्ति तिथि",
  "support.open": "खुला है",
  "support.resolved": "हल हो गया",
  "support.dispute": "हिसाब विवाद",
  "support.maintenance": "वाहन रखरखाव",
  "operator.operatorId": "ऑपरेटर आईडी:",
  "operator.totalCars": "कुल गाड़ियां:",
  "operator.active": "सक्रिय",
  "operator.toPay": "भुगतान योग्य",
  "operator.toCollect": "वसूल योग्य",
  "operator.cars": "गाड़ियां",
  "operator.drivers": "ड्राइवर",
  "operator.vehicles": "वाहन",
  "operator.fleetDeposit": "फ्लैट सुरक्षा जमा राशि",
  "operator.toPayDriver": "ड्राइवर को देय:",
  "operator.driverOwes": "ड्राइवर पर बकाया:",
  "settle.selectOption": "भुगतान विकल्प चुनें",
  "settle.full": "पूरा",
  "settle.partPay": "आंशिक भुगतान",
  "settle.advance": "एडवांस",
  "settle.amountToPay": "भुगतान राशि (₹)",
  "settle.payBtn": "भुगतान करें",
    "name.Rajesh": "राजेश",
  "name.Suresh": "सुरेश",
  "name.Vikram": "विक्रम",
  "name.Mohammed": "मोहम्मद",
  "name.Anil": "अनिल",
  "name.RK": "आरके ट्रांसपोर्ट",
  "name.Ramesh": "रमेश",
    "vehicle.specifications": "विनिर्देश",
  "vehicle.documents": "दस्तावेज़",
  "hisaab.daysAt": "दिन @",
  "platform.uber": "उबर",
  "platform.ola": "ओला",
  "platform.rapido": "रैपिडो",
  "platform.others": "अन्य",
  "refer.yourCode": "आपका रेफरल कोड",
  "refer.copyCode": "कोड कॉपी करें",
  "refer.rewardInfo": "जब आपका रेफर किया गया ड्राइवर 50 राइड्स पूरी करता है तो अगले साप्ताहिक हिसाब में सीधे ₹1,000 क्रेडिट प्राप्त करें।"
};

export const TRANSLATIONS_MR: Record<string, string> = {
  "app.title": "लेत्झरॉइड पोर्टल",
  "app.subtitle": "Drive in the Future of Urban Mobility.",
  "login.selectRole": "लॉगिन करण्यासाठी नंबर टाका",
  "login.driver": "ड्रायव्हर लॉगिन",
  "login.operator": "ऑपरेटर लॉगिन",
  "login.enterPhone": "10-अंकी मोबाईल नंबर प्रविष्ट करा",
  "login.sendOtp": "ओटीपी मिळवा",
  "login.enterOtp": "4-अंकी ओटीपी प्रविष्ट करा",
  "login.verifyOtp": "सत्यापित करा आणि पुढे जा",
  "login.changeNumber": "मोबाईल नंबर बदला",
  "home.greeting": "शुभ दुपार",
  "home.summary": "तुमचा या आठवड्याचा हिशोब",
  "home.estimatedPayout": "या आठवड्याची अंदाजे कमाई",
  "home.payoutToDriver": "लेत्झरॉइड द्वारे ड्रायव्हरला देणे",
  "home.dueToLetzryd": "लेत्झरॉइडला देणे असलेली रक्कम",
  "home.daysActive": "सक्रिय दिवस",
  "home.trips": "एकूण ट्रिप्स",
  "home.totalKm": "एकूण किलोमीटर",
  "home.deadMilesPct": "डेड माईल्स %",
  "home.settleNow": "कॅशफ्री / यूपीआय द्वारे भरा",
  "home.quickAccess": "जलद शॉर्टकट",
  "home.currentHisaab": "सध्याचा हिशोब",
  "home.lastWeekHisaab": "मागील आठवड्याचा हिशोब",
  "home.raiseTicket": "मदत तिकीट तयार करा",
  "home.referDriver": "रेफर करा आणि ₹1,000 मिळवा",
  "home.payLetzryd": "थेट पैसे भरा",
  "home.incentiveTracker": "साप्ताहिक इन्सेंटिव्ह ध्येय",
  "home.announcements": "महत्त्वाची लेत्झरॉइड सूचना",
  "home.deposit": "डिपॉझिट रक्कम",
  "home.cumulativeOwed": "एकूण बाकी रक्कम",
  "hisaab.title": "साप्ताहिक हिशोब पत्रक",
  "hisaab.weekIndex": "आठवडा",
  "hisaab.of": "पैकी",
  "hisaab.inProgress": "प्रगतीपथावर",
  "hisaab.locked": "मागील हिशोब (लॉक)",
  "hisaab.earnings": "एकूण कमाई",
  "hisaab.tripsCompleted": "पूर्ण ट्रिप्स",
  "hisaab.digitalEarnings": "डिजिटल कमाई",
  "hisaab.cashCollected": "रोख जमा",
  "hisaab.tollPassThrough": "टोल परतावा",
  "hisaab.incentives": "प्लॅटफॉर्म इन्सेंटिव्ह",
  "hisaab.subscriptionDeduction": "प्लॅटफॉर्म फी",
  "hisaab.vehicleRent": "गाडीचे भाडे",
  "hisaab.dailyMaintenance": "दैनिक देखभाल शुल्क",
  "hisaab.prevAdjustments": "इतर बाकी आणि समायोजन",
  "hisaab.tds": "टीडीएस कपात (1%)",
  "hisaab.paidDeposit": "भरलेले डिपॉझिट",
  "hisaab.pendingDeposit": "बाकी डिपॉझिट",
  "hisaab.joiningFeePaid": "जॉइनिंग फी भरली",
  "hisaab.pendingJoiningFee": "बाकी जॉइनिंग फी",
  "hisaab.previousOutstanding": "मागील बाकी",
  "hisaab.gpsRefreshedAt": "अंतिम अपडेट वेळ",
  "hisaab.disputeNotice": "हिशोब तक्रार सोमवार ते गुरुवार नोंदवा.",
  "settle.title": "साप्ताहिक हिशोब पूर्ण करा",
  "settle.forWeek": "कालावधी:",
  "settle.copy": "यूपीआय आयडी कॉपी करा",
  "settle.iHavePaid": "मी पैसे भरले आहेत",
  "settle.backToHisaab": "हिशोबावर परत जा",
  "vehicle.title": "वाहनाची माहिती आणि कागदपत्रे",
  "vehicle.subtitle": "तपशील, वैधता आणि प्लॅटफॉर्म परवानगी",
  "vehicle.lastUpdated": "अंतिम अपडेट तारीख",
  "support.title": "मदत केंद्र",
  "support.subtitle": "मॅनेजरशी संपर्क साधा किंवा तिकीट काढा",
  "support.manager": "नियुक्त ड्रायव्हर मॅनेजर",
  "support.newTicket": "नवीन तिकीट काढा",
  "profile.title": "प्रोफाईल माहिती",
  "profile.subtitle": "वैयक्तिक माहिती आणि संपर्क",
  "profile.edit": "प्रोफाईल संपादित करा",
  "profile.saved": "प्रोफाईल यशस्वीपणे अद्यतनित झाली!",
  "refer.title": "ड्रायव्हर रेफर करा आणि ₹1,000 मिळवा",
  "refer.subtitle": "लेत्झरॉइड जोडणाऱ्या ड्रायव्हर्सना तुमची लिंक पाठवा.",
  "nav.home": "होम",
  "nav.hisaab": "हिशोब",
  "nav.settle": "सेटल",
  "nav.vehicle": "वाहन",
  "nav.fleet": "फ्लूट",
  "nav.support": "मदत",
  "home.vehicle": "वाहन",
  "home.week": "आठवडा",
  "home.vsLastWeek": "मागील आठवड्याच्या तुलनेत",
  "home.bonus": "बोनस",
  "home.tripsRemaining": "ट्रिप्स बाकी",
  "home.toUnlockBonus": "₹1,500 बोनस अनलॉक करण्यासाठी",
    "home.paid": "जमा:",
  "home.pending": "थकबाकी:",
  "home.settlement": "सेटलमेंट",
  "home.balanceDue": "उर्वरित बाकी",
  "home.paidToLetzryd": "लेत्झरॉइडला भरले",
  "home.paidToBank": "बँकेत जमा केले",
  "home.totalOutstandingDue": "एकूण थकबाकी",
  "home.due": "थकबाकी",
  "home.supportDeskSub": "मदत केंद्र",
  "home.earnBonusSub": "बोनस मिळवा",
  "hisaab.completed": "पूर्ण",
  "hisaab.netPayout": "ड्रायव्हरचे एकूण उत्पन्न",
  "hisaab.netDue": "एकूण देय रक्कम",
  "hisaab.breakdownTitle": "हिशोब तपशील",
  "hisaab.driverHoldsFares": "ड्रायव्हरकडे जमा रक्कम",
  "hisaab.rides": "राइड्स",
  "hisaab.toDate": "ते",
  "hisaab.othersTitle": "इतर",
  "hisaab.gpsDeadMiles": "जीपीएस डेड माईल्स",
  "hisaab.totalGpsTracked": "एकूण जीपीएस किलोमीटर",
  "hisaab.idealTripKm": "आदर्श ट्रिप किलोमीटर",
  "hisaab.excessDeadMiles": "अतिरिक्त डेड माईल्स",
  "hisaab.deadMilePenalty": "डेड माईल्स दंड बाकी",
  "vehicle.specificationsTitle": "तपशील",
  "vehicle.brand": "ब्रांड",
  "vehicle.model": "मॉडेल",
  "vehicle.variant": "व्हेरियंट",
  "vehicle.regYear": "नोंदणी वर्ष",
  "vehicle.updated": "अद्यतनित",
  "vehicle.rc": "नोंदणी प्रमाणपत्र (RC)",
  "vehicle.insurance": "विमा",
  "vehicle.permit": "परमिट",
  "vehicle.fc": "फिटनेस प्रमाणपत्र (FC)",
  "vehicle.expires": "मुदत संपण्याची तारीख",
  "support.open": "उघडे",
  "support.resolved": "सोडवले",
  "support.dispute": "हिशोब तक्रार",
  "support.maintenance": "गाडीची देखभाल",
  "operator.operatorId": "ऑपरेटर आयडी:",
  "operator.totalCars": "एकूण गाड्या:",
  "operator.active": "सक्रिय",
  "operator.toPay": "देणे बाकी",
  "operator.toCollect": "घेणे बाकी",
  "operator.cars": "गाड्या",
  "operator.drivers": "ड्रायव्हर",
  "operator.vehicles": "वाहने",
  "operator.fleetDeposit": "फ्लॅट डिपॉझिट रक्कम",
  "operator.toPayDriver": "ड्रायव्हरला देणे:",
  "operator.driverOwes": "ड्रायव्हरवर बाकी:",
  "settle.selectOption": "पैसे भरण्याचा पर्याय निवडा",
  "settle.full": "पूर्ण",
  "settle.partPay": "भाग भरणा",
  "settle.advance": "अ‍ॅडव्हान्स",
  "settle.amountToPay": "भरण्याची रक्कम (₹)",
  "settle.payBtn": "पैसे भरा",
    "name.Rajesh": "राजेश",
  "name.Suresh": "सुरेश",
  "name.Vikram": "विक्रम",
  "name.Mohammed": "मोहम्मद",
  "name.Anil": "अनिल",
  "name.RK": "आरके ट्रान्सपोर्ट",
  "name.Ramesh": "रमेश",
    "vehicle.specifications": "तपशील",
  "vehicle.documents": "कागदपत्रे",
  "hisaab.daysAt": "दिवस @",
  "platform.uber": "उबर",
  "platform.ola": "ओला",
  "platform.rapido": "रॅपिडो",
  "platform.others": "इतर",
  "refer.yourCode": "तुमचा रेफरल कोड",
  "refer.copyCode": "कोड कॉपी करा",
  "refer.rewardInfo": "तुमचा रेफर केलेला ड्रायव्हर 50 राइड्स पूर्ण करतो तेव्हा पुढील साप्ताहिक हिशोबात थेट ₹1,000 मिळवा."
};

export const TRANSLATIONS_TE: Record<string, string> = {
  "app.title": "లెట్జ్రైడ్ పోర్టల్",
  "app.subtitle": "Drive in the Future of Urban Mobility.",
  "login.selectRole": "లాగిన్ అవ్వడానికి నంబర్ నమోదు చేయండి",
  "login.driver": "డ్రైవర్ లాగిన్",
  "login.operator": "ఆపరేటర్ లాగిన్",
  "login.enterPhone": "10-అంకెల మొబైల్ నంబర్ ఎంటర్ చేయండి",
  "login.sendOtp": "ఓటీపీ పొందండి",
  "login.enterOtp": "4-అంకెల ఓటీపీ ఎంటర్ చేయండి",
  "login.verifyOtp": "నిర్ధారించి ప్రవేశించండి",
  "login.changeNumber": "మొబైల్ నంబర్ మార్చండి",
  "home.greeting": "శుభ మధ్యాహ్నం",
  "home.summary": "ఈ వారపు వసూళ్ల సారాంశం",
  "home.estimatedPayout": "ఈ వారపు అంచనా నికర చెల్లింపు",
  "home.payoutToDriver": "డ్రైవర్‌కు చెల్లించాల్సిన మొత్తం",
  "home.dueToLetzryd": "లెట్జ్రైడ్‌కు చెల్లించాల్సిన మొత్తం",
  "home.daysActive": "యాక్టివ్ రోజులు",
  "home.trips": "మొత్తం ట్రిప్‌లు",
  "home.totalKm": "మొత్తం కిలోమీటర్లు",
  "home.deadMilesPct": "డెడ్ మైల్స్ %",
  "home.settleNow": "క్యాష్‌ఫ్రీ / యూపీఐ ద్వారా చెల్లించండి",
  "home.quickAccess": "త్వరిత లింక్‌లు",
  "home.currentHisaab": "ప్రస్తుత లెక్కలు",
  "home.lastWeekHisaab": "గత వారపు లెక్కలు",
  "home.raiseTicket": "సపోర్ట్ టికెట్ నమోదు చేయండి",
  "home.referDriver": "రెఫర్ చేయండి ₹1,000 పొందండి",
  "home.payLetzryd": "నేరుగా చెల్లించండి",
  "home.incentiveTracker": "వారపు ఇన్సెంటివ్ లక్ష్యం",
  "home.announcements": "ముఖ్యమైన లెట్జ్రైడ్ ప్రకటన",
  "home.deposit": "సెక్యూరిటీ డిపాజిట్",
  "home.cumulativeOwed": "మొత్తం బాకీ పడిన సొమ్ము",
  "hisaab.title": "వారపు లెక్కల వివరాలు",
  "hisaab.weekIndex": "వారం",
  "hisaab.of": "లో",
  "hisaab.inProgress": "పురోగతిలో ఉంది",
  "hisaab.locked": "పాత లెక్కలు (లాక్ చేయబడింది)",
  "hisaab.earnings": "మొత్తం సంపాదన",
  "hisaab.tripsCompleted": "పూర్తయిన ట్రిప్‌లు",
  "hisaab.digitalEarnings": "డిజిటల్ సంపాదన",
  "hisaab.cashCollected": "నగదు సేకరణ",
  "hisaab.tollPassThrough": "టోల్ రీఫండ్",
  "hisaab.incentives": "ప్లాట్‌ఫాం ఇన్సెంటివ్‌లు",
  "hisaab.subscriptionDeduction": "ప్లాట్‌ఫాం రుసుము",
  "hisaab.vehicleRent": "వాహనం కిరాయి",
  "hisaab.dailyMaintenance": "రోజువారీ నిర్వహణ రుసుము",
  "hisaab.prevAdjustments": "ఇతర బాకీలు మరియు సర్దుబాట్లు",
  "hisaab.tds": "టీడీఎస్ తగ్గింపు (1%)",
  "hisaab.paidDeposit": "చెల్లించిన డిపాజిట్",
  "hisaab.pendingDeposit": "బాకీ ఉన్న డిపాజిట్",
  "hisaab.joiningFeePaid": "చేరిక రుసుము చెల్లించారు",
  "hisaab.pendingJoiningFee": "బాకీ ఉన్న చేరిక రుసుము",
  "hisaab.previousOutstanding": "గత బాకీ",
  "hisaab.gpsRefreshedAt": "చివరి అప్‌డేట్ సమయం",
  "hisaab.disputeNotice": "లెక్కల ఫిర్యాదులు సోమ-గురువారాల్లో నమోదు చేయండి.",
  "settle.title": "వారపు లెక్కలు పూర్తి చేయండి",
  "settle.forWeek": "సమయం:",
  "settle.copy": "యూపీఐ ఐడీ కాపీ చేయండి",
  "settle.iHavePaid": "నేను చెల్లించాను",
  "settle.backToHisaab": "లెక్కల పేజీకి వెళ్లండి",
  "vehicle.title": "వాహనం మరియు పత్రాల వివరాలు",
  "vehicle.subtitle": "వివరాలు, గడువు మరియు ప్లాట్‌ఫాం అనుమతి",
  "vehicle.lastUpdated": "చివరి అప్‌డేట్ తేదీ",
  "support.title": "సపోర్ట్ సెంటర్",
  "support.subtitle": "మేనేజర్‌ను సంప్రదించండి లేదా టికెట్ నమోదు చేయండి",
  "support.manager": "కేటాయించిన డ్రైవర్ మేనేజర్",
  "support.newTicket": "కొత్త టికెట్ తీసుకోండి",
  "profile.title": "ప్రొఫైల్ వివరాలు",
  "profile.subtitle": "వ్యక్తిగత సమాచారం మరియు వివరాలు",
  "profile.edit": "ప్రొఫైల్ సవరించండి",
  "profile.saved": "ప్రొఫైల్ అప్‌డేట్ చేయబడింది!",
  "refer.title": "డ్రైవర్‌ను రెఫర్ చేసి ₹1,000 సంపాదించండి",
  "refer.subtitle": "లెట్జ్రైడ్‌లో చేరే ఈవీ డ్రైవర్లకు మీ లింక్ షేర్ చేయండి.",
  "nav.home": "హోమ్",
  "nav.hisaab": "లెక్కలు",
  "nav.settle": "చెల్లింపు",
  "nav.vehicle": "వాహనం",
  "nav.fleet": "ఫ్లీట్",
  "nav.support": "సపోర్ట్",
  "home.vehicle": "వాహనం",
  "home.week": "వారం",
  "home.vsLastWeek": "గత వారంతో పోలిస్తే",
  "home.bonus": "బోనస్",
  "home.tripsRemaining": "ట్రిప్‌లు మిగిలి ఉన్నాయి",
  "home.toUnlockBonus": "₹1,500 బోనస్ పొందడానికి",
    "home.paid": "చెల్లించినది:",
  "home.pending": "బాకీ:",
  "home.settlement": "సెటిల్మెంట్",
  "home.balanceDue": "మిగిలిన బాకీ",
  "home.paidToLetzryd": "లెట్జ్రైడ్కు చెల్లించబడింది",
  "home.paidToBank": "బ్యాంకుకు చెల్లించబడింది",
  "home.totalOutstandingDue": "మొత్తం బాకీ",
  "home.due": "బాకీ",
  "home.supportDeskSub": "సపోర్ట్ డెస్క్",
  "home.earnBonusSub": "బోనస్ పొందండి",
  "hisaab.completed": "పూర్తయింది",
  "hisaab.netPayout": "డ్రైవర్ నికర పేఅవుట్",
  "hisaab.netDue": "మొత్తం చెల్లించాల్సిన బాకీ",
  "hisaab.breakdownTitle": "లెక్కల వివరాలు",
  "hisaab.driverHoldsFares": "డ్రైవర్ వద్ద ఉన్న నగదు",
  "hisaab.rides": "రైడ్స్",
  "hisaab.toDate": "నుండి",
  "hisaab.othersTitle": "ఇతర",
  "hisaab.gpsDeadMiles": "జీపీఎస్ డెడ్ మైళ్ళు",
  "hisaab.totalGpsTracked": "మొత్తం జీపీఎస్ ట్రాక్ చేసిన కిలోమీటర్లు",
  "hisaab.idealTripKm": "ఆదర్శ ట్రిప్ కిలోమీటర్లు",
  "hisaab.excessDeadMiles": "అదనపు డెడ్ మైళ్ళు",
  "hisaab.deadMilePenalty": "డెడ్ మైల్ జరిమానా బాకీ",
  "vehicle.specificationsTitle": "వివరాలు",
  "vehicle.brand": "బ్రాండ్",
  "vehicle.model": "మోడల్",
  "vehicle.variant": "వేరియంట్",
  "vehicle.regYear": "రిజిస్ట్రేషన్ సంవత్సరం",
  "vehicle.updated": "అప్‌డేట్ చేయబడింది",
  "vehicle.rc": "రిజిస్ట్రేషన్ సర్టిఫికేట్ (RC)",
  "vehicle.insurance": "ఇన్సూరెన్స్",
  "vehicle.permit": "పర్మిట్",
  "vehicle.fc": "ఫిట్‌నెస్ సర్టిఫికేట్ (FC)",
  "vehicle.expires": "గడువు ముగింపు తేదీ",
  "support.open": "ఓపెన్",
  "support.resolved": "పరిష్కరించబడింది",
  "support.dispute": "లెక్కల వివాదం",
  "support.maintenance": "వాహన నిర్వహణ",
  "operator.operatorId": "ఆపరేటర్ ఐడీ:",
  "operator.totalCars": "మొత్తం కార్లు:",
  "operator.active": "యాక్టివ్",
  "operator.toPay": "చెల్లించాల్సినవి",
  "operator.toCollect": "వసూలు చేయాల్సినవి",
  "operator.cars": "కార్లు",
  "operator.drivers": "డ్రైవర్లు",
  "operator.vehicles": "వాహనాలు",
  "operator.fleetDeposit": "ఫ్లీట్ సెక్యూరిటీ డిపాజిట్",
  "operator.toPayDriver": "డ్రైవర్‌కు చెల్లించాల్సినవి:",
  "operator.driverOwes": "డ్రైవర్ బాకీ ఉన్నది:",
  "settle.selectOption": "చెల్లింపు ఎంపికను ఎంచుకోండి",
  "settle.full": "పూర్తి",
  "settle.partPay": "పాక్షిక చెల్లింపు",
  "settle.advance": "అడ్వాన్స్",
  "settle.amountToPay": "చెల్లించాల్సిన మొత్తం (₹)",
  "settle.payBtn": "చెల్లించండి",
    "name.Rajesh": "రాజేష్",
  "name.Suresh": "సురేష్",
  "name.Vikram": "విక్రమ్",
  "name.Mohammed": "మొహమ్మద్",
  "name.Anil": "అనిల్",
  "name.RK": "ఆర్కే ట్రాన్స్‌పోర్ట్",
  "name.Ramesh": "రమేష్",
    "vehicle.specifications": "వివరాలు",
  "vehicle.documents": "పత్రాలు",
  "hisaab.daysAt": "రోజులు @",
  "platform.uber": "ఊబర్",
  "platform.ola": "ఓలా",
  "platform.rapido": "ర్యాపిడో",
  "platform.others": "ఇతర",
  "refer.yourCode": "మీ రెఫరల్ కోడ్",
  "refer.copyCode": "కోడ్ కాపీ చేయండి",
  "refer.rewardInfo": "మీరు రెఫర్ చేసిన డ్రైవర్ 50 రైడ్‌లు పూర్తి చేసినప్పుడు మీ తదుపరి వారపు లెక్కల్లో రూ.1,000 క్రెడిట్ పొందండి."
};

export const TRANSLATIONS_KN: Record<string, string> = {
  "app.title": "ಲೆಟ್ಜ್ರೈಡ್ ಪೋರ್ಟಲ್",
  "app.subtitle": "Drive in the Future of Urban Mobility.",
  "login.selectRole": "ಲಾಗಿನ್ ಮಾಡಲು ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
  "login.driver": "ಚಾಲಕ ಲಾಗಿನ್",
  "login.operator": "ಆಪರೇಟರ್ ಲಾಗಿನ್",
  "login.enterPhone": "10-ಅಂಕೆಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
  "login.sendOtp": "ಒಟಿಪಿ ಪಡೆಯಿರಿ",
  "login.enterOtp": "4-ಅಂಕೆಗಳ ಒಟಿಪಿ ನಮೂದಿಸಿ",
  "login.verifyOtp": "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಪ್ರವೇಶಿಸಿ",
  "login.changeNumber": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಬದಲಾಯಿಸಿ",
  "home.greeting": "ಶುಭ ಮಧ್ಯಾಹ್ನ",
  "home.summary": "ಈ ವಾರದ ಲೆಕ್ಕಾಚಾರದ ವಿವರಗಳು",
  "home.estimatedPayout": "ಈ ವಾರದ ಅಂದಾಜು ನಿವ್ವಳ ಪಾವತಿ",
  "home.payoutToDriver": "ಚಾಲಕನಿಗೆ ಲೆಟ್ಜ್ರೈಡ್ ಪಾವತಿಸುವ ಮೊತ್ತ",
  "home.dueToLetzryd": "ಲೆಟ್ಜ್ರೈಡ್‌ಗೆ ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ",
  "home.daysActive": "ಸಕ್ರಿಯ ದಿನಗಳು",
  "home.trips": "ಒಟ್ಟು ಟ್ರಿಪ್‌ಗಳು",
  "home.totalKm": "ಒಟ್ಟು ಕಿಲೋಮೀಟರ್",
  "home.deadMilesPct": "ಡೆಡ್ ಮೈಲ್ಸ್ %",
  "home.settleNow": "ಕ್ಯಾಶ್‌ಫ್ರೀ / ಯುಪಿಐ ಮೂಲಕ ಪಾವತಿಸಿ",
  "home.quickAccess": "ತ್ವರಿತ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು",
  "home.currentHisaab": "ಪ್ರಸ್ತುತ ಲೆಕ್ಕಚಾರ",
  "home.lastWeekHisaab": "ಕಳೆದ ವಾರದ ಲೆಕ್ಕಚಾರ",
  "home.raiseTicket": "ಸಹಾಯ ಟಿಕೆಟ್ ನಮೂದಿಸಿ",
  "home.referDriver": "ರೆಫರ್ ಮಾಡಿ ₹1,000 ಗಳಿಸಿ",
  "home.payLetzryd": "ನೇರವಾಗಿ ಪಾವತಿಸಿ",
  "home.incentiveTracker": "ವಾರದ ಇನ್ಸೆಂಟಿವ್ ಗುರಿ",
  "home.announcements": "ಪ್ರಮುಖ ಲೆಟ್ಜ್ರೈಡ್ ಪ್ರಕಟಣೆ",
  "home.deposit": "ಸೆಕ್ಯೂರಿಟಿ ಡೆಪಾಸಿಟ್",
  "home.cumulativeOwed": "ಒಟ್ಟು ಬಾಕಿ ಮೊತ್ತ",
  "hisaab.title": "ವಾರದ ಲೆಕ್ಕಾಚಾರದ ವರದಿ",
  "hisaab.weekIndex": "ವಾರ",
  "hisaab.of": "ರ",
  "hisaab.inProgress": "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
  "hisaab.locked": "ಹಿಂದಿನ ಲೆಕ್ಕಾಚಾರ (ಲಾಕ್ ಆಗಿದೆ)",
  "hisaab.earnings": "ಒಟ್ಟು ಗಳಿಕೆ",
  "hisaab.tripsCompleted": "ಪೂರ್ಣಗೊಂಡ ಟ್ರಿಪ್‌ಗಳು",
  "hisaab.digitalEarnings": "ಡಿಜಿಟಲ್ ಗಳಿಕೆ",
  "hisaab.cashCollected": "ನಗದು ಸಂಗ್ರಹ",
  "hisaab.tollPassThrough": "ಟೋಲ್ ಮರುಪಾವತಿ",
  "hisaab.incentives": "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಇನ್ಸೆಂಟಿವ್‌ಗಳು",
  "hisaab.subscriptionDeduction": "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ",
  "hisaab.vehicleRent": "ವಾಹನ ಬಾಡಿಗೆ",
  "hisaab.dailyMaintenance": "ದೈನಂದಿನ ನಿರ್ವಹಣೆ ಶುಲ್ಕ",
  "hisaab.prevAdjustments": "ಇತರ ಬಾಕಿ ಮತ್ತು ಹೊಂದಾಣಿಕೆಗಳು",
  "hisaab.tds": "ಟಿಡಿಎಸ್ ಕಡಿತ (1%)",
  "hisaab.paidDeposit": "ಪಾವತಿಸಿದ ಡೆಪಾಸಿಟ್",
  "hisaab.pendingDeposit": "ಬಾಕಿ ಡೆಪಾಸಿಟ್",
  "hisaab.joiningFeePaid": "ಸೇರ್ಪಡೆ ಶುಲ್ಕ ಪಾವತಿಸಲಾಗಿದೆ",
  "hisaab.pendingJoiningFee": "ಬಾಕಿ ಸೇರ್ಪಡೆ ಶುಲ್ಕ",
  "hisaab.previousOutstanding": "ಹಿಂದಿನ ಬಾಕಿ",
  "hisaab.gpsRefreshedAt": "ಕೊನೆಯ ಅಪ್‌ಡೇಟ್ ಸಮಯ",
  "hisaab.disputeNotice": "ಲೆಕ್ಕಾಚಾರದ ದೂರುಗಳನ್ನು ಸೋಮ-ಗುರುವಾರದೊಳಗೆ ನಮೂದಿಸಿ.",
  "settle.title": "ವಾರದ ಲೆಕ್ಕಾಚಾರ ಪೂರ್ಣಗೊಳಿಸಿ",
  "settle.forWeek": "ಅವಧಿ:",
  "settle.copy": "ಯುಪಿಐ ಐಡಿ ಕಾಪಿ ಮಾಡಿ",
  "settle.iHavePaid": "ನಾನು ಪಾವತಿಸಿದ್ದೇನೆ",
  "settle.backToHisaab": "ಲೆಕ್ಕಾಚಾರಕ್ಕೆ ಹಿಂತಿರುಗಿ",
  "vehicle.title": "ವಾಹನ ಮತ್ತು ದಾಖಲೆಗಳ ವಿವರ",
  "vehicle.subtitle": "ವಿವರಣೆ, ಸಿಂಧುತ್ವ ಮತ್ತು ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಅನುಮತಿ",
  "vehicle.lastUpdated": "ಕೊನೆಯ ಅಪ್‌ಡೇಟ್ ದಿನಾಂಕ",
  "support.title": "ಸಹಾಯ ಕೇಂದ್ರ",
  "support.subtitle": "ಮ್ಯಾನೇಜರ್ ಸಂಪರ್ಕಿಸಿ ಅಥವಾ ಟಿಕೆಟ್ ನಮೂದಿಸಿ",
  "support.manager": "ನಿಯೋಜಿತ ಚಾಲಕ ಮ್ಯಾನೇಜರ್",
  "support.newTicket": "ಹೊಸ ಟಿಕೆಟ್ ನಮೂದಿಸಿ",
  "profile.title": "ಪ್ರೊಫೈಲ್ ವಿವರಗಳು",
  "profile.subtitle": "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ ಮತ್ತು ವಿವರಗಳು",
  "profile.edit": "ಪ್ರೊಫೈಲ್ ಎಡಿಟ್ ಮಾಡಿ",
  "profile.saved": "ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ಅಪ್‌ಡೇಟ್ ಆಗಿದೆ!",
  "refer.title": "ಚಾಲಕರನ್ನು ರೆಫರ್ ಮಾಡಿ ₹1,000 ಗಳಿಸಿ",
  "refer.subtitle": "ಲೆಟ್ಜ್ರೈಡ್‌ಗೆ ಸೇರುವ ಇವಿ ಚಾಲಕರಿಗೆ ಲಿಂಕ್ ಕಳುಹಿಸಿ.",
  "nav.home": "ಹೋಮ್",
  "nav.hisaab": "ಲೆಕ್ಕಾಚಾರ",
  "nav.settle": "ಸೆಟಲ್",
  "nav.vehicle": "ವಾಹನ",
  "nav.fleet": "ಫ್ಲೀಟ್",
  "nav.support": "ಸಹಾಯ",
  "home.vehicle": "ವಾಹನ",
  "home.week": "ವಾರ",
  "home.vsLastWeek": "ಕಳೆದ ವಾರಕ್ಕೆ ಹೋಲಿಸಿದರೆ",
  "home.bonus": "ಬೋನಸ್",
  "home.tripsRemaining": "ಟ್ರಿಪ್‌ಗಳು ಬಾಕಿ ಇವೆ",
  "home.toUnlockBonus": "₹1,500 ಬೋನಸ್ ಪಡೆಯಲು",
    "home.paid": "ಪಾವತಿಸಿದ:",
  "home.pending": "ಪಾಕಿ:",
  "home.settlement": "ಸೆಟಲ್ಮೆಂಟ್",
  "home.balanceDue": "ಉಳಿದ ಬಾಕಿ",
  "home.paidToLetzryd": "ಲೆಟ್ಜ್‌ರೈಡ್‌ಗೆ ಪಾವತಿಸಲಾಗಿದೆ",
  "home.paidToBank": "ಬ್ಯಾಂಕ್‌ಗೆ ಪಾವತಿಸಲಾಗಿದೆ",
  "home.totalOutstandingDue": "ಒಟ್ಟು ಬಾಕಿ",
  "home.due": "ಬಾಕಿ",
  "home.supportDeskSub": "ಸಹಾಯ ಕೇಂದ್ರ",
  "home.earnBonusSub": "ಬೋನಸ್ ಗಳಿಸಿ",
  "hisaab.completed": "ಪೂರ್ಣಗೊಂಡಿದೆ",
  "hisaab.netPayout": "ಚಾಲಕನ ನಿವ್ವಳ ಪಾವತಿ",
  "hisaab.netDue": "ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ",
  "hisaab.breakdownTitle": "ಲೆಕ್ಕಾಚಾರ ವಿವರಗಳು",
  "hisaab.driverHoldsFares": "ಚಾಲಕನ ಬಳಿ ಇರುವ ಹಣ",
  "hisaab.rides": "ರೈಡ್‌ಗಳು",
  "hisaab.toDate": "ರಿಂದ",
  "hisaab.othersTitle": "ಇತರ",
  "hisaab.gpsDeadMiles": "ಜಿಪಿಎಸ್ ಡೆಡ್ ಮೈಲಿಗಳು",
  "hisaab.totalGpsTracked": "ಒಟ್ಟು ಜಿಪಿಎಸ್ ಕಿಲೋಮೀಟರ್",
  "hisaab.idealTripKm": "ಸೂಕ್ತ ಟ್ರಿಪ್ ಕಿಲೋಮೀಟರ್",
  "hisaab.excessDeadMiles": "ಹೆಚ್ಚುವರಿ ಡೆಡ್ ಮೈಲಿಗಳು",
  "hisaab.deadMilePenalty": "ಡೆಡ್ ಮೈಲ್ ದಂಡ ಬಾಕಿ",
  "vehicle.specificationsTitle": "ವಿವರಣೆ",
  "vehicle.brand": "ಬ್ರ್ಯಾಂಡ್",
  "vehicle.model": "ಮಾಡೆಲ್",
  "vehicle.variant": "ವೇರಿಯೆಂಟ್",
  "vehicle.regYear": "ನೋಂದಣಿ ವರ್ಷ",
  "vehicle.updated": "ಅಪ್‌ಡೇಟ್ ಆಗಿದೆ",
  "vehicle.rc": "ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರ (RC)",
  "vehicle.insurance": "ವಿಮೆ",
  "vehicle.permit": "ಪರ್ಮಿಟ್",
  "vehicle.fc": "ಫಿಟ್ನೆಸ್ ಪ್ರಮಾಣಪತ್ರ (FC)",
  "vehicle.expires": "ಸಿಂಧುತ್ವ ಮುಕ್ತಾಯ",
  "support.open": "ತೆರೆದಿದೆ",
  "support.resolved": "ಪರಿಹರಿಸಲಾಗಿದೆ",
  "support.dispute": "ಲೆಕ್ಕಾಚಾರ ದೂರು",
  "support.maintenance": "ವಾಹನ ನಿರ್ವಹಣೆ",
  "operator.operatorId": "ಆಪರೇಟರ್ ಐಡಿ:",
  "operator.totalCars": "ಒಟ್ಟು ಕಾರುಗಳು:",
  "operator.active": "ಸಕ್ರಿಯ",
  "operator.toPay": "ಪಾವತಿಸಬೇಕಾದ",
  "operator.toCollect": "ಸಂಗ್ರಹಿಸಬೇಕಾದ",
  "operator.cars": "ಕಾರುಗಳು",
  "operator.drivers": "ಚಾಲಕರು",
  "operator.vehicles": "ವಾಹನಗಳು",
  "operator.fleetDeposit": "ಫ್ಲೀಟ್ ಸೆಕ್ಯೂರಿಟಿ ಡೆಪಾಸಿಟ್",
  "operator.toPayDriver": "ಚಾಲಕನಿಗೆ ಪಾವತಿಸಬೇಕಾದ:",
  "operator.driverOwes": "ಚಾಲಕ ಬಾಕಿ ಇರುವುದು:",
  "settle.selectOption": "ಪಾವತಿ ಆಯ್ಕೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "settle.full": "ಪೂರ್ಣ",
  "settle.partPay": "ಭಾಗಶಃ ಪಾವತಿ",
  "settle.advance": "ಅಡ್ವಾನ್ಸ್",
  "settle.amountToPay": "ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ (₹)",
  "settle.payBtn": "ಪಾವತಿಸಿ",
    "name.Rajesh": "ರಾಜೇಶ್",
  "name.Suresh": "ಸುರೇಶ್",
  "name.Vikram": "ವಿಕ್ರಮ್",
  "name.Mohammed": "ಮೊಹಮ್ಮದ್",
  "name.Anil": "ಅನಿಲ್",
  "name.RK": "ಆರ್‌ಕೆ ಟ್ರಾನ್ಸ್‌ಪೋರ್ಟ್",
  "name.Ramesh": "ರಮೇಶ್",
    "vehicle.specifications": "ವಿವರಣೆ",
  "vehicle.documents": "ದಾಖಲೆಗಳು",
  "hisaab.daysAt": "ದಿನಗಳು @",
  "platform.uber": "ಉಬರ್",
  "platform.ola": "ಓಲಾ",
  "platform.rapido": "ರ್ಯಾಪಿಡೋ",
  "platform.others": "ಇತರ",
  "refer.yourCode": "ನಿಮ್ಮ ರೆಫರಲ್ ಕೋಡ್",
  "refer.copyCode": "ಕೋಡ್ ಕಾಪಿ ಮಾಡಿ",
  "refer.rewardInfo": "ನಿಮ್ಮ ರೆಫರ್ ಮಾಡಿದ ಚಾಲಕ 50 ರೈಡ್‌ಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿದಾಗ ನಿಮ್ಮ ಮುಂದಿನ ವಾರದ ಲೆಕ್ಕಾಚಾರದಲ್ಲಿ ನೇರವಾಗಿ ₹1,000 ಪಡೆಯಿರಿ."
};

