/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { User, Vehicle, RentalPlan, HisaabWeek, Fleet, Ticket, Notification, Announcement } from './types';

export interface DemoProfile {
  name: string;
  phone: string;
  role: 'driver' | 'operator';
  tag: string;
  otp: string;
  user: User;
  weeks: HisaabWeek[];
}

export const USER_DATA: User = {
  id: "LR-DRV-0157",
  name: "Rajesh Kumar",
  operatorCode: "VND0157",
  phone: "9876543210",
  joined: "2024-10-15",
  initials: "RK",
  aadhar: "1234-5678-9012",
  dlNumber: "KA05-2024-1234567",
  dlExpiry: "2029-05-20",
  emergencyContact: "Priya Kumar (Wife) - 9876543211",
  emergencyName: "Priya Kumar",
  emergencyRelation: "Spouse / Wife",
  emergencyPhone: "9876543211",
  address: "No. 42, 3rd Cross, Indiranagar, Bangalore - 560038",
  bloodGroup: "B+",
  dob: "1992-08-14",
  operatorType: "Individual Driver",
  assignedManagerName: "Ramesh Naik",
  assignedManagerPhone: "9876543299",
  depositAmount: 6000,
  depositTotalRequired: 6000,
  depositPaidSoFar: 5000,
  depositPending: 1000,
  depositNextDueDate: "2026-08-05",
  cumulativeOwed: 3265.80,
  weeklyIncentiveTargetTrips: 260,
  completedTripsThisWeek: 233,
  weeklyIncentiveReward: 1500
};

export const VEHICLE_DATA: Vehicle = {
  number: "KA 05 AQ 7692",
  make: "Maruti Suzuki",
  model: "Dzire",
  variant: "ZXi CNG",
  year: 2021,
  color: "White Pearl",
  fuelType: "CNG",
  odometer: 124380,
  fitnessExpiry: "2026-10-12",
  insuranceExpiry: "2027-03-20",
  rcExpiry: "2036-05-01",
  permitType: "Tourist Permit",
  permitExpiry: "2026-12-31",
  pucExpiry: "2026-08-15",
  lastUpdatedOn: "2026-07-24",
  platforms: {
    uber: { status: "active", rating: 4.82, trips: 3210 },
    ola: { status: "active", rating: 4.65, trips: 890 },
    rapido: { status: "active", rating: 4.71, trips: 1540 }
  },
  allocationStart: "2024-10-15"
};

export const RENTAL_PLAN_DATA: RentalPlan = {
  name: "Standard",
  dailyRate: 1000,
  planStart: "2024-10-15",
  activeMonths: 20,
  note: "Standard EV Rental Plan: ₹1,000/active operating day. Includes battery charging credits."
};

export const ANNOUNCEMENTS_DATA: Announcement[] = [
  {
    id: "ANN-01",
    title: "Urgent Hub Vehicle Inspection Required",
    message: "Mandatory EV battery telemetry audit at Hitec City Hub before Thursday 5:00 PM.",
    severity: "warning",
    date: "2026-07-27"
  }
];

export const HISAAB_WEEKS_DATA: HisaabWeek[] = [
  {
    weekNumber: 30,
    hisaabNumber: "HIS-2026-030",
    weekStart: "2026-06-22",
    weekEnd: "2026-06-28",
    status: "in_progress",
    isLocked: false,
    activeDays: 4,
    growthPct: 12.5,
    platforms: {
      uber: { trips: 120, revenue: 15800, cashCollection: -10500, toll: 420, incentive: 3200, subscription: -1500, km: 1250 },
      ola: { trips: 65, revenue: 6800, cashCollection: -4200, toll: 180, incentive: 1200, subscription: -900, km: 680 },
      rapido: { trips: 48, revenue: 5200, cashCollection: -2800, toll: 90, incentive: 850, subscription: -390, km: 511 }
    },
    rent: { dailyRate: 1000, netWeeklyRent: 4000 },
    dailyMaintenance: 200,
    previousAdjustments: 0,
    tds: 154.20,
    challan: 500,
    accident: 0,
    adjustment: 0,
    paidDeposit: 5000,
    pendingDeposit: 1000,
    joiningFeePaid: 1000,
    pendingJoiningFee: 0,
    previousOutstanding: 0,
    pendingSinceDate: "2026-06-22",
    gps: {
      totalGpsKm: 3200.80,
      idealGpsKm: 3820.60,
      deadMile: 0.00,
      deadMilePct: 0,
      deadKmPenalty: 0,
      allowedFreeDeadKmPct: 20,
      penaltyRatePerKm: 5
    },
    lastRefreshedTime: "2026-07-28 02:15 PM",
    currentWeekOs: -3265.80,
    pendingDue: 0,
    totalOs: -3265.80,
    toCollect: 0,
    toPay: 3265.80,
    letzrydEarning: 4000,
    notes: "Current active week in progress. Net payout of ₹3,265.80 payable to driver."
  },
  {
    weekNumber: 29,
    hisaabNumber: "HIS-2026-029",
    weekStart: "2026-06-15",
    weekEnd: "2026-06-21",
    status: "to_collect",
    isLocked: true,
    activeDays: 6,
    growthPct: -4.2,
    platforms: {
      uber: { trips: 198, revenue: 22300, cashCollection: -18900, toll: 680, incentive: 4500, subscription: -2200, km: 1950 },
      ola: { trips: 88, revenue: 9400, cashCollection: -6800, toll: 240, incentive: 1800, subscription: -1200, km: 890 },
      rapido: { trips: 62, revenue: 6800, cashCollection: -4100, toll: 120, incentive: 1100, subscription: -650, km: 620 }
    },
    rent: { dailyRate: 1000, netWeeklyRent: 6000 },
    dailyMaintenance: 300,
    previousAdjustments: -250,
    tds: 284.40,
    challan: 500,
    accident: 0,
    adjustment: 0,
    paidDeposit: 5000,
    pendingDeposit: 1000,
    joiningFeePaid: 1000,
    pendingJoiningFee: 0,
    previousOutstanding: 0,
    pendingSinceDate: "2026-06-21",
    gps: {
      totalGpsKm: 3460.00,
      idealGpsKm: 3460.00,
      deadMile: 0,
      deadMilePct: 0,
      deadKmPenalty: 0,
      allowedFreeDeadKmPct: 20,
      penaltyRatePerKm: 5
    },
    lastRefreshedTime: "2026-06-22 10:00 AM",
    currentWeekOs: 1034.80,
    pendingDue: 1034.80,
    totalOs: 1034.80,
    toCollect: 1034.80,
    toPay: 0,
    letzrydEarning: 6000,
    notes: "Locked Past Week. Pending due ₹1,034.80 owed by driver."
  }
];

export const DEMO_PROFILES: DemoProfile[] = [
  {
    name: "Rajesh Kumar",
    phone: "9876543210",
    role: "driver",
    tag: "Paid Last Week (₹0.00)",
    otp: "1234",
    user: USER_DATA,
    weeks: [
      { ...HISAAB_WEEKS_DATA[0] },
      { ...HISAAB_WEEKS_DATA[1], isLocked: true, status: 'settled_pay', currentWeekOs: 0 }
    ]
  },
  {
    name: "Suresh Sharma",
    phone: "9876543211",
    role: "driver",
    tag: "Unpaid Last Week (-₹1,034.80)",
    otp: "1234",
    user: {
      ...USER_DATA,
      id: "LR-DRV-0294",
      name: "Suresh Sharma",
      operatorCode: "VND0294",
      phone: "9876543211",
      initials: "SS",
      depositAmount: 6000,
      depositTotalRequired: 6000,
      depositPaidSoFar: 5000,
      depositPending: 1000,
      depositNextDueDate: "2026-08-05",
      cumulativeOwed: 2884.80
    },
    weeks: [
      { ...HISAAB_WEEKS_DATA[0], currentWeekOs: 1850.00, pendingDeposit: 1000 },
      { ...HISAAB_WEEKS_DATA[1], isLocked: false, status: 'to_collect', currentWeekOs: 1034.80, pendingDeposit: 1000 }
    ]
  },
  {
    name: "RK Transport",
    phone: "9876543222",
    role: "operator",
    tag: "Fleet Operator",
    otp: "1234",
    user: {
      ...USER_DATA,
      id: "OPR-HYD-004",
      name: "RK Transport & Fleet",
      operatorCode: "OPR-HYD-004",
      phone: "9876543222",
      initials: "RK",
      operatorType: "Fleet Owner"
    },
    weeks: HISAAB_WEEKS_DATA
  }
];

export const OPERATOR_FLEET_DATA: Fleet = {
  operatorCode: "OPR-HYD-004",
  operatorName: "RK Transport & Fleet Logistics",
  depositTotalRequired: 25000,
  depositPaidSoFar: 20000,
  depositPending: 5000,
  vehicles: [
    {
      number: "KA05AQ7692",
      make: "Maruti Suzuki",
      model: "Dzire CNG",
      driverName: "Rajesh Kumar",
      plan: { name: "Standard", dailyRate: 1000 },
      currentWeekOs: -3265.80,
      status: "active",
      hisaabWeeks: HISAAB_WEEKS_DATA
    },
    {
      number: "TS09EV8812",
      make: "Tata",
      model: "Tigor EV",
      driverName: "Suresh Reddy",
      plan: { name: "Standard", dailyRate: 1000 },
      currentWeekOs: 1450.00,
      status: "active",
      hisaabWeeks: HISAAB_WEEKS_DATA
    },
    {
      number: "TS07EV4401",
      make: "Mahindra",
      model: "eVerito",
      driverName: "Vikram Singh",
      plan: { name: "Standard", dailyRate: 1000 },
      currentWeekOs: 0,
      status: "active",
      hisaabWeeks: HISAAB_WEEKS_DATA
    },
    {
      number: "TS08EV1129",
      make: "Tata",
      model: "XPRES-T EV",
      driverName: "Mohammed Ali",
      plan: { name: "Standard", dailyRate: 1000 },
      currentWeekOs: -1820.50,
      status: "active",
      hisaabWeeks: HISAAB_WEEKS_DATA
    },
    {
      number: "TS09EV9900",
      make: "BYD",
      model: "e6 EV",
      driverName: "Anil Verma",
      plan: { name: "Standard", dailyRate: 1000 },
      currentWeekOs: 0,
      status: "idle",
      hisaabWeeks: HISAAB_WEEKS_DATA
    }
  ]
};

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: "TKT-2026-0041",
    category: "Challan Dispute",
    subject: "Traffic Challan incorrectly charged on 18th Jun",
    description: "A challan of ₹500 was charged for speed violation on MG Road on Jun 18. I was off-duty and vehicle was parked.",
    status: "open",
    priority: "high",
    date: "2026-06-22",
    response: null
  },
  {
    id: "TKT-2026-0028",
    category: "Vehicle Maintenance",
    subject: "AC compressor cooling issue",
    description: "AC in vehicle KA05AQ7692 is blowing warm air when parked. Urgent servicing required.",
    status: "resolved",
    priority: "medium",
    date: "2026-06-10",
    response: "Serviced at Hitec City Hub on Jun 12. AC refrigerant refilled."
  }
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: "NOTIF-01",
    icon: "ReceiptIndianRupee",
    title: "Hisaab is Created",
    message: "Your weekly Hisaab statement is ready for review.",
    time: "",
    read: false
  },
  {
    id: "NOTIF-02",
    icon: "Wallet",
    title: "Pay Hisaab",
    message: "Please settle your outstanding Hisaab dues.",
    time: "",
    read: false
  }
];

export const SUPPORT_HOTLINE = "0800-053-8793";
export const LETZRYD_UPI_ID = "letzryd@ybl";
export const TICKET_CATEGORIES = [
  "Vehicle Maintenance",
  "App / Platform Issue",
  "Challan Dispute",
  "Other"
];

/* =========================================================================
   COMPREHENSIVE 5-LANGUAGE LOCALIZATION DICTIONARIES
   ========================================================================= */

export const TRANSLATIONS_EN: Record<string, string> = {
  "app.title": "LetzRyd Portal",
  "app.subtitle": "Drive in the Future of Urban Mobility.",
  "login.selectRole": "Enter Mobile Number to Login",
  "login.driver": "Driver Login",
  "login.operator": "Operator Login",
  "login.enterPhone": "Enter 10-Digit Mobile Number",
  "login.sendOtp": "Get OTP",
  "login.enterOtp": "Enter 4-Digit OTP",
  "login.verifyOtp": "Verify & Enter Portal",
  "home.greeting": "Hi",
  "home.summary": "Here's your weekly settlement at a glance",
  "home.estimatedPayout": "ESTIMATED PAYOUT",
  "home.thisWeek": "THIS WEEK",
  "home.payoutToDriver": "LetzRyd payout to driver",
  "home.dueToLetzryd": "Due to be paid to LetzRyd",
  "home.daysActive": "Days Active",
  "home.trips": "Trips",
  "home.totalKm": "Total KMs",
  "home.deadMilesPct": "Dead Miles %",
  "home.settleNow": "Settle via Cashfree / UPI",
  "home.quickAccess": "Quick Access Shortcuts",
  "home.currentHisaab": "Current Hisaab",
  "home.lastWeekHisaab": "Last Week Hisaab",
  "home.raiseTicket": "Raise Support Ticket",
  "home.referDriver": "Refer & Earn ₹1,000",
  "home.payLetzryd": "Pay Dues Direct",
  "home.incentiveTracker": "Weekly Incentive Goal",
  "home.announcements": "Important LetzRyd Announcement",
  "home.deposit": "Security Deposit",
  "home.cumulativeOwed": "Cumulative Money Owed",
  "hisaab.title": "Weekly Hisaab Statement",
  "hisaab.weekIndex": "Week",
  "hisaab.of": "of",
  "hisaab.inProgress": "In Progress",
  "hisaab.locked": "Locked Past Hisaab",
  "hisaab.earnings": "Earnings",
  "hisaab.tripsCompleted": "Trips Completed",
  "hisaab.digitalEarnings": "Digital Earnings",
  "hisaab.cashCollected": "Cash Collected",
  "hisaab.tollPassThrough": "Toll Refund",
  "hisaab.incentives": "Platform Incentives",
  "hisaab.subscriptionDeduction": "Platform Fee / Subscription",
  "hisaab.vehicleRent": "Vehicle Rent",
  "hisaab.dailyMaintenance": "Daily Maintenance Charge",
  "hisaab.prevAdjustments": "Previous Adjustments",
  "hisaab.tds": "TDS Deduction (1%)",
  "hisaab.paidDeposit": "Paid Deposit",
  "hisaab.pendingDeposit": "Pending Deposit",
  "hisaab.joiningFeePaid": "Joining Fee Paid",
  "hisaab.pendingJoiningFee": "Pending Joining Fee",
  "hisaab.previousOutstanding": "Previous Outstanding",
  "hisaab.gpsRefreshedAt": "Last Refreshed At",
  "hisaab.disputeNotice": "Hisaab disputes can be raised Mon–Thu. Changes after Thursday apply to next week.",
  "settle.title": "Settle Weekly Hisaab",
  "settle.forWeek": "Settlement Period:",
  "settle.copy": "Copy UPI ID",
  "settle.iHavePaid": "I Have Paid (Manual)",
  "settle.backToHisaab": "Back to Hisaab",
  "vehicle.title": "Vehicle Details",
  "vehicle.subtitle": "",
  "vehicle.documents": "DOCUMENTS",
  "vehicle.specifications": "SPECIFICATIONS",
  "vehicle.lastUpdated": "Last Updated On",
  "support.title": "Support Desk",
  "support.subtitle": "Contact manager or raise tickets",
  "support.manager": "DRIVER MANAGER",
  "support.newTicket": "Raise New Ticket",
  "profile.title": "User Profile",
  "profile.subtitle": "Personal profile, documents, and emergency details",
  "profile.edit": "Edit Profile",
  "profile.editDetails": "Edit Details",
  "profile.saveChanges": "Save Changes",
  "profile.personalTitle": "PERSONAL & MEDICAL INFO",
  "profile.documentsTitle": "DOCUMENTS & CREDENTIALS",
  "profile.fullName": "Full Name",
  "profile.vendorCode": "Vendor Code",
  "profile.driverId": "Driver ID",
  "profile.registeredPhone": "Registered Phone",
  "profile.aadharNumber": "Aadhaar Number",
  "profile.drivingLicense": "Driving License",
  "profile.dlExpiry": "DL Expiry",
  "profile.emergencyTitle": "EMERGENCY CONTACT",
  "profile.emergencyPerson": "Contact Person",
  "profile.emergencyRelation": "Relation",
  "profile.emergencyPhone": "Emergency Mobile",
  "profile.bloodGroup": "Blood Group",
  "profile.dob": "Date of Birth",
  "profile.address": "Residential Address",
  "relation.spouse": "Spouse / Wife",
  "relation.father": "Father",
  "relation.mother": "Mother",
  "relation.brother": "Brother",
  "relation.sister": "Sister",
  "relation.relative": "Relative / Friend",
  "profile.saved": "Profile updated successfully!",
  "profile.savedSuccess": "Profile details updated!",
  "sos.title": "Emergency SOS Safety Center",
  "sos.subtitle": "Press emergency button to transmit real-time coordinates to dispatch.",
  "sos.confirm": "Trigger Emergency SOS alert? This will immediately notify LetzRyd Central Control Hub.",
  "sos.pressToAlert": "Press to Alert Hub",
  "sos.reportAccident": "Report Accident or Roadside Breakdown",
  "sos.location": "Current Location / Nearest Landmark",
  "sos.locationPlaceholder": "e.g. Near Hitec City Metro Station, Outer Ring Road",
  "sos.activated": "Emergency SOS Active!",
  "refer.title": "Refer Driver & Earn ₹1,000",
  "refer.subtitle": "Share your referral link with EV drivers joining LetzRyd.",
  "nav.home": "Home",
  "nav.hisaab": "Hisaab",
  "nav.settle": "Settle",
  "nav.vehicle": "Vehicle",
  "nav.fleet": "Fleet",
  "nav.support": "Support",
  "home.vehicle": "Vehicle",
  "home.vehicleNumber": "Vehicle Number",
  "home.vehicleModel": "Vehicle Model",
  "home.week": "Week",
  "home.vsLastWeek": "vs last week",
  "home.bonus": "Bonus",
  "home.tripsRemaining": "trips remaining",
  "home.toUnlockBonus": "to unlock ₹1,500 bonus",
  "home.paid": "Paid",
  "home.pending": "Pending",
  "home.settlement": "SETTLEMENT",
  "home.balanceDue": "Balance Due",
  "home.paidToLetzryd": "Paid to LetzRyd",
  "home.paidToBank": "Paid to Bank",
  "home.totalOutstandingDue": "Total Outstanding Due",
  "home.due": "Due",
  "home.supportDeskSub": "Help & Tickets",
  "home.earnBonusSub": "Earn bonus",
  "hisaab.completed": "Completed",
  "hisaab.netPayout": "NET DRIVER PAYOUT",
  "hisaab.netDue": "NET AMOUNT DUE",
  "hisaab.breakdownTitle": "HISAAB BREAKDOWN",
  "hisaab.driverHoldsFares": "Driver holds fares",
  "hisaab.rides": "rides",
  "hisaab.toDate": "TO",
  "hisaab.othersTitle": "Others",
  "hisaab.gpsDeadMiles": "GPS Dead Miles",
  "hisaab.totalGpsTracked": "Total GPS Tracked KM",
  "hisaab.idealTripKm": "Ideal Trip KM",
  "hisaab.excessDeadMiles": "Excess Dead Miles",
  "hisaab.deadMilePenalty": "Dead Mile Penalty Due",
  "vehicle.specificationsTitle": "SPECIFICATIONS",
  "vehicle.brand": "Brand",
  "vehicle.model": "Model",
  "vehicle.variant": "Variant",
  "vehicle.regYear": "Registration Year",
  "vehicle.updated": "Updated",
  "vehicle.rc": "Registration Certificate (RC)",
  "vehicle.insurance": "Insurance",
  "vehicle.permit": "Permit",
  "vehicle.fc": "Fitness Certificate (FC)",
  "vehicle.expires": "Expires",
  "support.open": "Open",
  "support.resolved": "Resolved",
  "support.dispute": "Hisaab Dispute",
  "support.maintenance": "Vehicle Maintenance",
  "operator.operatorId": "Operator ID:",
  "operator.totalCars": "Total Cars:",
  "operator.active": "Active",
  "operator.toPay": "TO PAY",
  "operator.toCollect": "TO COLLECT",
  "operator.cars": "CARS",
  "operator.drivers": "Drivers",
  "operator.vehicles": "Vehicles",
  "operator.fleetDeposit": "FLEET SECURITY DEPOSIT",
  "operator.toPayDriver": "To Pay Driver:",
  "operator.driverOwes": "Driver Owes:",
  "settle.selectOption": "SELECT PAYMENT OPTION",
  "settle.full": "Full",
  "settle.partPay": "Part Pay",
  "settle.advance": "Advance",
  "settle.amountToPay": "Amount to Pay (₹)",
  "settle.payBtn": "Pay",
  "name.Rajesh": "Rajesh",
  "name.Suresh": "Suresh",
  "name.Vikram": "Vikram",
  "name.Mohammed": "Mohammed",
  "name.Anil": "Anil",
  "name.RK": "RK Transport",
  "name.Ramesh": "Ramesh",
  "refer.yourCode": "YOUR REFERRAL CODE",
  "refer.copyCode": "Copy Code",
  "refer.rewardInfo": "Receive ₹1,000 credit directly in your next weekly Hisaab when your referred driver completes 50 rides.",
  "refer.submitLeadTitle": "Direct Lead Referral",
  "refer.leadName": "Driver Name",
  "refer.leadPhone": "Mobile Number",
  "refer.submitBtn": "Submit Lead & Earn ₹1,000",
  "refer.leadSubmitted": "Lead submitted successfully! Our team will contact them within 24h.",
  "support.activeTickets": "Active Tickets",
  "support.closedTickets": "Closed Tickets",
  "support.allTickets": "All Tickets",
  "support.ticketCategory": "Ticket Category",
  "support.issueSubject": "Issue Subject",
  "support.subjectPlaceholder": "Summary of the issue...",
  "support.detailedDescription": "Detailed Description",
  "support.descriptionPlaceholder": "Describe what happened, relevant week dates, or vehicle issues...",
  "support.submitTicket": "Submit Ticket",
  "support.cancel": "Cancel",
  "ticketCategory.Vehicle Maintenance": "Vehicle Maintenance",
  "ticketCategory.App / Platform Issue": "App / Platform Issue",
  "ticketCategory.Challan Dispute": "Challan Dispute",
  "ticketCategory.Other": "Other",
  "ticketDetail.issueDetails": "Issue Details",
  "ticketDetail.resolutionTitle": "LetzRyd Support Resolution",
  "ticketDetail.closeBtn": "Close",
  "refer.programReward": "PROGRAM REWARD",
  "refer.codeLabel": "Registered Phone / Code",
  "refer.referredDriversTitle": "Your Referred Drivers",
  "refer.rides": "Rides",
  "refer.pending": "Pending",
  "settle.instantPay": "Instant Pay",
  "settle.weeklyHisaabDue": "Weekly Hisaab Due:",
  "settle.challansAndPenalties": "Challans & Penalties:",
  "settle.connectingGateway": "Connecting Gateway...",
  "settle.toDate": "to",
  "vehicle.number": "Vehicle Number",
  "support.ticketsTitle": "SUPPORT TICKETS",
  "home.settleDuesTitle": "Settle Dues",
  "home.settleDuesSub": "Pay Dues",
  "home.myVehicleTitle": "My Vehicle",
  "home.myVehicleSub": "Specs & Docs",
  "home.supportDeskTitle": "Support Desk",
  "home.referDriverTitle": "Refer Driver",
  "home.referDriverSub": "Earn ₹1,000",
  "hisaab.challanPenalty": "Traffic Challan & Penalty",
  "hisaab.gpsDeadMilesTitle": "GPS Dead Miles",
  "hisaab.standingBalancesTitle": "STANDING ACCOUNT BALANCES",
  "hisaab.contractTerms": "Contract Terms",
  "hisaab.depositTitle": "Security Deposit",
  "hisaab.joiningFeeTitle": "Joining Fee",
  "hisaab.agreed": "Agreed:",
  "hisaab.paid": "Paid:",
  "hisaab.pending": "Pending:",
  "refer.perDriver": "Driver",
  "refer.namePlaceholder": "e.g. Ramesh Verma",
  "refer.phonePlaceholder": "10-digit Mobile No.",
  "notif.title": "Notifications",
  "notif.markAllRead": "Mark All Read",
  "notif.payoutTitle": "Weekly Payout Calculated",
  "notif.payoutMessage": "Estimated payout of ₹3,265.80 ready for Sunday clearance.",
  "notif.twoHoursAgo": "2 hours ago",
  "notif.closeFeed": "Close Feed",
  "notif.hisaabCreatedTitle": "Hisaab is Created",
  "notif.hisaabCreatedMessage": "Your weekly Hisaab statement is ready for review.",
  "notif.payHisaabTitle": "Pay Hisaab",
  "notif.payHisaabMessage": "Please settle your outstanding Hisaab dues.",
  "support.active": "Active",
  "support.closed": "Closed",
  "hisaab.earningsTitle": "Platform Earnings",
  "hisaab.deductionsTitle": "Deductions & Rent",
  "hisaab.uberEarnings": "Uber Earnings",
  "hisaab.olaEarnings": "Ola Earnings",
  "hisaab.rapidoEarnings": "Rapido Earnings",
  "hisaab.summaryTitle": "WEEKLY SUMMARY HIGHLIGHTS",
  "hisaab.totalRides": "Total Rides",
  "hisaab.grossEarnings": "Total Gross Earnings",
  "hisaab.totalFeesRent": "Total Fees & Rent",
  "hisaab.totalPenalties": "Total Penalties",
  "hisaab.billTitle": "WEEKLY HISAAB STATEMENT",
  "hisaab.rentAndMaintenance": "Rent & Maintenance",
  "hisaab.totalEarnings": "Total Earnings",
  "hisaab.weekLabel": "Week",
  "hisaab.ridesUnit": "Rides",
  "hisaab.lastUpdated": "Last Updated"
};

export const TRANSLATIONS_HI: Record<string, string> = {
  "app.title": "लेत्ज़रॉइड पोर्टल",
  "app.subtitle": "Drive in the Future of Urban Mobility.",
  "login.selectRole": "लॉगिन करने के लिए मोबाइल नंबर दर्ज करें",
  "login.driver": "ड्राइवर लॉगिन",
  "login.operator": "ऑपरेटर लॉगिन",
  "login.enterPhone": "10-अंकों का मोबाइल नंबर दर्ज करें",
  "login.sendOtp": "ओटीपी प्राप्त करें",
  "login.enterOtp": "4-अंकों का ओटीपी दर्ज करें",
  "login.verifyOtp": "सत्यापित करें और प्रवेश करें",
  "login.changeNumber": "मोबाइल नंबर बदलें",
  "home.greeting": "नमस्कार",
  "home.summary": "यह रहा आपका साप्ताहिक हिसाब",
  "home.estimatedPayout": "अनुमानित पेआउट",
  "home.payoutToDriver": "लेत्ज़रॉइड द्वारा ड्राइवर को भुगतान",
  "home.dueToLetzryd": "लेत्ज़रॉइड को देय राशि",
  "home.daysActive": "सक्रिय दिन",
  "home.trips": "कुल यात्राएं",
  "home.totalKm": "कुल किलोमीटर",
  "home.deadMilesPct": "डेड माइल्स %",
  "home.settleNow": "कैशफ्री / यूपीआई से भुगतान करें",
  "home.quickAccess": "त्वरित शॉर्टकट",
  "home.currentHisaab": "वर्तमान हिसाब",
  "home.lastWeekHisaab": "पिछले सप्ताह का हिसाब",
  "home.raiseTicket": "सहायता टिकट दर्ज करें",
  "home.referDriver": "रेफर करें और ₹1,000 कमाएं",
  "home.payLetzryd": "सीधा भुगतान करें",
  "home.incentiveTracker": "साप्ताहिक प्रोत्साहन लक्ष्य",
  "home.announcements": "महत्वपूर्ण लेत्ज़रॉइड घोषणा",
  "home.deposit": "सुरक्षा जमा राशि",
  "home.cumulativeOwed": "कुल बकाया राशि",
  "hisaab.title": "साप्ताहिक हिसाब विवरण",
  "hisaab.weekIndex": "सप्ताह",
  "hisaab.of": "का",
  "hisaab.inProgress": "प्रगति में",
  "hisaab.locked": "पुराना हिसाब (लॉक)",
  "hisaab.earnings": "कुल कमाई",
  "hisaab.tripsCompleted": "पूर्ण यात्राएं",
  "hisaab.digitalEarnings": "डिजिटल कमाई",
  "hisaab.cashCollected": "नकद संग्रह",
  "hisaab.tollPassThrough": "टोल रिफंड",
  "hisaab.incentives": "प्लेटफॉर्म इंसेंटिव",
  "hisaab.subscriptionDeduction": "प्लेटफॉर्म शुल्क",
  "hisaab.vehicleRent": "वाहन किराया",
  "hisaab.dailyMaintenance": "दैनिक रखरखाव शुल्क",
  "hisaab.prevAdjustments": "अन्य बकाया और समायोजन",
  "hisaab.tds": "टीडीएस कटौती (1%)",
  "hisaab.paidDeposit": "जमा की गई राशि",
  "hisaab.pendingDeposit": "बकाया जमा राशि",
  "hisaab.joiningFeePaid": "ज्वाइनिंग शुल्क जमा",
  "hisaab.pendingJoiningFee": "बकाया ज्वाइनिंग शुल्क",
  "hisaab.previousOutstanding": "पिछला बकाया",
  "hisaab.gpsRefreshedAt": "अंतिम अपडेट समय",
  "hisaab.disputeNotice": "हिसाब विवाद सोमवार-गुरुवार दर्ज करें।",
  "settle.title": "साप्ताहिक हिसाब चुकता करें",
  "settle.forWeek": "साप्ताहिक अवधि:",
  "settle.copy": "यूपीआई आईडी कॉपी करें",
  "settle.iHavePaid": "मैंने भुगतान कर दिया है",
  "settle.backToHisaab": "हिसाब पर वापस जाएं",
  "vehicle.title": "वाहन विवरण एवं दस्तावेज़",
  "vehicle.subtitle": "विनिर्देश, वैधता स्थिति और प्लेटफॉर्म अनुमति",
  "vehicle.lastUpdated": "अंतिम अपडेट तिथि",
  "support.title": "सहायता केंद्र",
  "support.subtitle": "अपने ड्राइवर मैनेजर से संपर्क करें या नया टिकट बनाएं",
  "support.manager": "आवंटित ड्राइवर मैनेजर",
  "support.newTicket": "नया टिकट बनाएं",
  "profile.title": "प्रोफ़ाइल एवं पहचान",
  "profile.subtitle": "सत्यापित क्रेडेंशियल और आपातकालीन विवरण",
  "profile.edit": "प्रोफ़ाइल संपादित करें",
  "profile.editDetails": "विवरण संपादित करें",
  "profile.saveChanges": "बदलाव सहेजें",
  "profile.identityTitle": "पहचान क्रेडेंशियल",
  "profile.registeredPhone": "पंजीकृत फोन",
  "profile.aadharNumber": "आधार नंबर",
  "profile.drivingLicense": "ड्राइविंग लाइसेंस",
  "profile.dlExpiry": "डीएल समाप्ति",
  "profile.emergencyTitle": "आपातकालीन संपर्क",
  "profile.emergencyPerson": "संपर्क व्यक्ति",
  "profile.emergencyRelation": "संबंध",
  "profile.emergencyPhone": "आपातकालीन मोबाइल",
  "profile.bloodGroup": "ब्लड ग्रुप",
  "profile.dob": "जन्म तिथि",
  "profile.address": "आवासीय पता",
  "relation.spouse": "पति / पत्नी",
  "relation.father": "पिता",
  "relation.mother": "माता",
  "relation.brother": "भाई",
  "relation.sister": "बहन",
  "relation.relative": "रिश्तेदार / मित्र",
  "profile.saved": "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!",
  "profile.savedSuccess": "आपातकालीन विवरण सफलतापूर्वक अपडेट किया गया!",
  "refer.title": "ड्राइवर को रेफर करें और ₹1,000 कमाएं",
  "refer.subtitle": "लेत्ज़रॉइड से जुड़ने वाले ईवी ड्राइवरों के साथ अपना लिंक साझा करें।",
  "nav.home": "होम",
  "nav.hisaab": "हिसाब",
  "nav.settle": "सेटल",
  "nav.vehicle": "वाहन",
  "nav.fleet": "फ्लैट",
  "nav.support": "सहायता",
  "home.vehicle": "वाहन",
  "home.week": "सप्ताह",
  "home.vsLastWeek": "पिछले सप्ताह की तुलना में",
  "home.bonus": "बोनस",
  "home.tripsRemaining": "यात्राएं शेष",
  "home.toUnlockBonus": "₹1,500 बोनस अनलॉक करने के लिए",
  "home.paid": "जमा:",
  "home.pending": "बकाया:",
  "home.settlement": "सेटलमेंट",
  "home.balanceDue": "शेष बकाया",
  "home.paidToLetzryd": "लेत्ज़राइड को भुगतान किया गया",
  "home.paidToBank": "बैंक में जमा किया गया",
  "home.totalOutstandingDue": "कुल बकाया राशि",
  "home.due": "बकाया",
  "home.supportDeskSub": "मदद और टिकट",
  "home.earnBonusSub": "बोनस कमाएं",
  "hisaab.completed": "पूर्ण",
  "hisaab.netPayout": "ड्राइवर का कुल भुगतान",
  "hisaab.netDue": "कुल देय राशि",
  "hisaab.breakdownTitle": "हिसाब विवरण",
  "hisaab.driverHoldsFares": "ड्राइवर के पास किराया",
  "hisaab.rides": "राइड्स",
  "hisaab.toDate": "से",
  "hisaab.othersTitle": "अन्य",
  "hisaab.gpsDeadMiles": "जीपीएस डेड माइल्स",
  "hisaab.totalGpsTracked": "कुल जीपीएस ट्रैक किए गए किलोमीटर",
  "hisaab.idealTripKm": "आदर्श ट्रिप किलोमीटर",
  "hisaab.excessDeadMiles": "अतिरिक्त डेड माइल्स",
  "hisaab.deadMilePenalty": "डेड माइल जुर्माना देय",
  "vehicle.specificationsTitle": "विनिर्देश",
  "vehicle.brand": "ब्रांड",
  "vehicle.model": "मॉडल",
  "vehicle.variant": "वेरिएंट",
  "vehicle.regYear": "पंजीकरण वर्ष",
  "vehicle.updated": "अपडेट किया गया",
  "vehicle.rc": "पंजीकरण प्रमाणपत्र (आरसी)",
  "vehicle.insurance": "बीमा",
  "vehicle.permit": "परमिट",
  "vehicle.fc": "फिटनेस प्रमाणपत्र (एफसी)",
  "vehicle.expires": "समाप्ति तिथि",
  "support.open": "खुला है",
  "support.resolved": "हल हो गया",
  "support.dispute": "हिसाब विवाद",
  "support.maintenance": "वाहन रखरखाव",
  "operator.operatorId": "ऑपरेटर आईडी:",
  "operator.totalCars": "कुल गाड़ियां:",
  "operator.active": "सक्रिय",
  "operator.toPay": "भुगतान योग्य",
  "operator.toCollect": "वसूल योग्य",
  "operator.cars": "गाड़ियां",
  "operator.drivers": "ड्राइवर",
  "operator.vehicles": "वाहन",
  "operator.fleetDeposit": "फ्लैट सुरक्षा जमा राशि",
  "operator.toPayDriver": "ड्राइवर को देय:",
  "operator.driverOwes": "ड्राइवर पर बकाया:",
  "settle.selectOption": "भुगतान विकल्प चुनें",
  "settle.full": "पूरा",
  "settle.partPay": "आंशिक भुगतान",
  "settle.advance": "एडवांस",
  "settle.amountToPay": "भुगतान राशि (₹)",
  "settle.payBtn": "भुगतान करें",
  "name.Rajesh": "राजेश",
  "name.Suresh": "सुरेश",
  "name.Vikram": "विक्रम",
  "name.Mohammed": "मोहम्मद",
  "name.Anil": "अनिल",
  "name.RK": "आरके ट्रांसपोर्ट",
  "name.Ramesh": "रमेश",
  "vehicle.specifications": "विनिर्देश",
  "vehicle.documents": "दस्तावेज़",
  "hisaab.daysAt": "दिन @",
  "platform.uber": "उबर",
  "platform.ola": "ओला",
  "platform.rapido": "रैपिडो",
  "platform.others": "अन्य",
  "refer.yourCode": "आपका रेफरल कोड",
  "refer.copyCode": "कोड कॉपी करें",
  "refer.rewardInfo": "जब आपका रेफर किया गया ड्राइवर 50 राइड्स पूरी करता है तो अगले साप्ताहिक हिसाब में सीधे ₹1,000 क्रेडिट प्राप्त करें।",
  "support.activeTickets": "सक्रिय टिकट",
  "support.closedTickets": "बंद टिकट",
  "support.allTickets": "सभी टिकट",
  "support.ticketCategory": "टिकट श्रेणी",
  "support.issueSubject": "विषय (संक्षेप)",
  "support.subjectPlaceholder": "समस्या का संक्षेप लिखें...",
  "support.detailedDescription": "विस्तृत विवरण",
  "support.descriptionPlaceholder": "घटना, प्रासंगिक सप्ताह तिथि या वाहन की समस्या का विवरण दें...",
  "support.submitTicket": "टिकट जमा करें",
  "support.cancel": "रद्द करें",
  "ticketCategory.Vehicle Maintenance": "वाहन रखरखाव एवं सर्विसिंग",
  "ticketCategory.App / Platform Issue": "ऐप / प्लेटफॉर्म संबंधी समस्या",
  "ticketCategory.Challan Dispute": "ट्रैफिक चालान विवाद",
  "ticketCategory.Other": "अन्य समस्या",
  "ticketDetail.issueDetails": "समस्या का विवरण",
  "ticketDetail.resolutionTitle": "लेत्ज़रॉइड सहायता समाधान",
  "ticketDetail.closeBtn": "बंद करें",
  "refer.programReward": "पुरस्कार विवरण",
  "refer.codeLabel": "पंजीकृत मोबाइल / कोड",
  "refer.referredDriversTitle": "आपके द्वारा रेफर किए गए ड्राइवर",
  "refer.rides": "राइड्स",
  "refer.pending": "लंबित",
  "settle.instantPay": "त्वरित भुगतान",
  "settle.weeklyHisaabDue": "साप्ताहिक हिसाब देय:",
  "settle.challansAndPenalties": "चालान एवं जुर्माना:",
  "settle.connectingGateway": "गेटवे से जुड़ रहा है...",
  "settle.toDate": "से",
  "home.vehicleNumber": "गाड़ी नंबर / वाहन क्रमांक",
  "vehicle.number": "गाड़ी नंबर / वाहन क्रमांक",
  "support.ticketsTitle": "सहायता टिकट",
  "home.settleDuesTitle": "हिसाब चुकाएं",
  "home.settleDuesSub": "बकाया भुगतान",
  "home.myVehicleTitle": "मेरा वाहन",
  "home.myVehicleSub": "विवरण व दस्तावेज़",
  "home.supportDeskTitle": "सहायता केंद्र",
  "home.referDriverTitle": "ड्राइवर रेफर करें",
  "home.referDriverSub": "कमाएं ₹1,000",
  "hisaab.challanPenalty": "ट्रैफिक चालान एवं जुर्माना",
  "hisaab.gpsDeadMilesTitle": "जीपीएस डेड माइल्स",
  "hisaab.standingBalancesTitle": "स्थायी खाता शेष विवरण",
  "hisaab.contractTerms": "अनुबंध की शर्तें",
  "hisaab.depositTitle": "सुरक्षा जमा राशि",
  "hisaab.joiningFeeTitle": "जॉइनिंग फीस",
  "hisaab.agreed": "सहमति:",
  "hisaab.paid": "जमा:",
  "hisaab.pending": "बकाया:",
  "refer.perDriver": "ड्राइवर",
  "refer.namePlaceholder": "उदा. रमेश वर्मा",
  "refer.phonePlaceholder": "10-अंकों का मोबाइल नंबर",
  "refer.submitLeadTitle": "डायरेक्ट लीड रेफरल",
  "refer.leadName": "ड्राइवर का नाम",
  "refer.leadPhone": "मोबाइल नंबर",
  "refer.submitBtn": "लीड सबमिट करें और ₹1,000 कमाएं",
  "refer.referredBadge": "रेफर किया गया",
  "notif.title": "सूचनाएं",
  "notif.markAllRead": "सभी पढ़े गए चिह्नित करें",
  "notif.payoutTitle": "साप्ताहिक पेआउट की गणना हुई",
  "notif.payoutMessage": "रविवार की निकासी के लिए ₹3,265.80 का अनुमानित पेआउट तैयार है।",
  "notif.twoHoursAgo": "2 घंटे पहले",
  "notif.closeFeed": "बंद करें",
  "notif.hisaabCreatedTitle": "हिसाब बन गया है",
  "notif.hisaabCreatedMessage": "आपका साप्ताहिक हिसाब विवरण तैयार है।",
  "notif.payHisaabTitle": "हिसाब का भुगतान करें",
  "notif.payHisaabMessage": "कृपया अपने बकाया हिसाब का भुगतान करें।",
  "support.active": "सक्रिय",
  "support.closed": "बंद",
  "hisaab.earningsTitle": "प्लेटफ़ॉर्म कमाई",
  "hisaab.deductionsTitle": "कटौती और किराया",
  "hisaab.uberEarnings": "उबर कमाई",
  "hisaab.olaEarnings": "ओला कमाई",
  "hisaab.rapidoEarnings": "रापिडो कमाई",
  "hisaab.summaryTitle": "साप्ताहिक सारांश मुख्य बिंदु",
  "hisaab.totalRides": "कुल राइड्स",
  "hisaab.grossEarnings": "कुल सकल कमाई",
  "hisaab.totalFeesRent": "कुल शुल्क और किराया",
  "hisaab.totalPenalties": "कुल जुर्माना",
  "hisaab.billTitle": "साप्ताहिक हिसाब विवरण",
  "hisaab.rentAndMaintenance": "किराया और रखरखाव",
  "hisaab.totalEarnings": "कुल कमाई",
  "hisaab.weekLabel": "सप्ताह",
  "hisaab.ridesUnit": "राइड्स",
  "profile.personalTitle": "व्यक्तिगत एवं चिकित्सा विवरण",
  "profile.documentsTitle": "दस्तावेज़ एवं प्रमाण पत्र"
};

export const TRANSLATIONS_MR: Record<string, string> = {
  "app.title": "लेत्झरॉइड पोर्टल",
  "app.subtitle": "Drive in the Future of Urban Mobility.",
  "login.selectRole": "लॉगिन करण्यासाठी नंबर टाका",
  "login.driver": "ड्रायव्हर लॉगिन",
  "login.operator": "ऑपरेटर लॉगिन",
  "login.enterPhone": "10-अंकी मोबाईल नंबर प्रविष्ट करा",
  "login.sendOtp": "ओटीपी मिळवा",
  "login.enterOtp": "4-अंकी ओटीपी प्रविष्ट करा",
  "login.verifyOtp": "सत्यापित करा आणि पुढे जा",
  "login.changeNumber": "मोबाईल नंबर बदला",
  "home.greeting": "शुभ दुपार",
  "home.summary": "तुमचा या आठवड्याचा हिशोब",
  "home.estimatedPayout": "अंदाजित पेआउट",
  "home.payoutToDriver": "लेत्झरॉइड द्वारे ड्रायव्हरला देणे",
  "home.dueToLetzryd": "लेत्झरॉइडला देणे असलेली रक्कम",
  "home.daysActive": "सक्रिय दिवस",
  "home.trips": "एकूण ट्रिप्स",
  "home.totalKm": "एकूण किलोमीटर",
  "home.deadMilesPct": "डेड माईल्स %",
  "home.settleNow": "कॅशफ्री / यूपीआय द्वारे भरा",
  "home.quickAccess": "जलद शॉर्टकट",
  "home.currentHisaab": "सध्याचा हिशोब",
  "home.lastWeekHisaab": "मागील आठवड्याचा हिशोब",
  "home.raiseTicket": "मदत तिकीट तयार करा",
  "home.referDriver": "रेफर करा आणि ₹1,000 मिळवा",
  "home.payLetzryd": "थेट पैसे भरा",
  "home.incentiveTracker": "साप्ताहिक इन्सेंटिव्ह ध्येय",
  "home.announcements": "महत्त्वाची लेत्झरॉइड सूचना",
  "home.deposit": "डिपॉझिट रक्कम",
  "home.cumulativeOwed": "एकूण बाकी रक्कम",
  "hisaab.title": "साप्ताहिक हिशोब पत्रक",
  "hisaab.weekIndex": "आठवडा",
  "hisaab.of": "पैकी",
  "hisaab.inProgress": "प्रगतीपथावर",
  "hisaab.locked": "मागील हिशोब (लॉक)",
  "hisaab.earnings": "एकूण कमाई",
  "hisaab.tripsCompleted": "पूर्ण ट्रिप्स",
  "hisaab.digitalEarnings": "डिजिटल कमाई",
  "hisaab.cashCollected": "रोख जमा",
  "hisaab.tollPassThrough": "टोल परतावा",
  "hisaab.incentives": "प्लॅटफॉर्म इन्सेंटिव्ह",
  "hisaab.subscriptionDeduction": "प्लॅटफॉर्म फी",
  "hisaab.vehicleRent": "गाडीचे भाडे",
  "hisaab.dailyMaintenance": "दैनिक देखभाल शुल्क",
  "hisaab.prevAdjustments": "इतर बाकी आणि समायोजन",
  "hisaab.tds": "टीडीएस कपात (1%)",
  "hisaab.paidDeposit": "भरलेले डिपॉझिट",
  "hisaab.pendingDeposit": "बाकी डिपॉझिट",
  "hisaab.joiningFeePaid": "जॉइनिंग फी भरली",
  "hisaab.pendingJoiningFee": "बाकी जॉइनिंग फी",
  "hisaab.previousOutstanding": "मागील बाकी",
  "hisaab.gpsRefreshedAt": "अंतिम अपडेट वेळ",
  "hisaab.disputeNotice": "हिशोब तक्रार सोमवार ते गुरुवार नोंदवा.",
  "settle.title": "साप्ताहिक हिशोब पूर्ण करा",
  "settle.forWeek": "कालावधी:",
  "settle.copy": "यूपीआय आयडी कॉपी करा",
  "settle.iHavePaid": "मी पैसे भरले आहेत",
  "settle.backToHisaab": "हिशोबावर परत जा",
  "vehicle.title": "वाहनाची माहिती आणि कागदपत्रे",
  "vehicle.subtitle": "तपशील, वैधता आणि प्लॅटफॉर्म परवानगी",
  "vehicle.lastUpdated": "अंतिम अपडेट तारीख",
  "support.title": "मदत केंद्र",
  "support.subtitle": "मॅनेजरशी संपर्क साधा किंवा तिकीट काढा",
  "support.manager": "नियुक्त ड्रायव्हर मॅनेजर",
  "support.newTicket": "नवीन तिकीट काढा",
  "profile.title": "प्रोफाईल आणि ओळख",
  "profile.subtitle": "सत्यापित ओळख आणि आपत्कालीन माहिती",
  "profile.edit": "प्रोफाईल संपादित करा",
  "profile.editDetails": "माहिती बदला",
  "profile.saveChanges": "बदल सेव्ह करा",
  "profile.identityTitle": "ओळखपत्रे",
  "profile.registeredPhone": "नोंदणीकृत फोन",
  "profile.aadharNumber": "आधार क्रमांक",
  "profile.drivingLicense": "ड्रायव्हिंग लायसन्स",
  "profile.dlExpiry": "मुदत समाप्ती",
  "profile.emergencyTitle": "आपत्कालीन संपर्क",
  "profile.emergencyPerson": "संपर्क व्यक्ती",
  "profile.emergencyRelation": "नाते",
  "profile.emergencyPhone": "आपत्कालीन मोबाईल",
  "profile.bloodGroup": "रक्तगट",
  "profile.dob": "जन्म तारीख",
  "profile.address": "राहण्याचा पत्ता",
  "relation.spouse": "पती / पत्नी",
  "relation.father": "वडील",
  "relation.mother": "आई",
  "relation.brother": "भाऊ",
  "relation.sister": "बहीण",
  "relation.relative": "नातेवाईक / मित्र",
  "profile.saved": "प्रोफाईल यशस्वीपणे अद्यतनित झाली!",
  "profile.savedSuccess": "आपत्कालीन माहिती यशस्वीरित्या सेव्ह झाली!",
  "refer.title": "ड्रायव्हर रेफर करा आणि ₹1,000 मिळवा",
  "refer.subtitle": "लेत्झरॉइड जोडणाऱ्या ड्रायव्हर्सना तुमची लिंक पाठवा.",
  "nav.home": "होम",
  "nav.hisaab": "हिशोब",
  "nav.settle": "सेटल",
  "nav.vehicle": "वाहन",
  "nav.fleet": "फ्लूट",
  "nav.support": "मदत",
  "home.vehicle": "वाहन",
  "home.week": "आठवडा",
  "home.vsLastWeek": "मागील आठवड्याच्या तुलनेत",
  "home.bonus": "बोनस",
  "home.tripsRemaining": "ट्रिप्स बाकी",
  "home.toUnlockBonus": "₹1,500 बोनस अनलॉक करण्यासाठी",
  "home.paid": "जमा:",
  "home.pending": "थकबाकी:",
  "home.settlement": "सेटलमेंट",
  "home.balanceDue": "उर्वरित बाकी",
  "home.paidToLetzryd": "लेत्झरॉइडला भरले",
  "home.paidToBank": "बँकेत जमा केले",
  "home.totalOutstandingDue": "एकूण थकबाकी",
  "home.due": "थकबाकी",
  "home.supportDeskSub": "मदत व तिकीट",
  "home.earnBonusSub": "बोनस मिळवा",
  "hisaab.completed": "पूर्ण",
  "hisaab.netPayout": "ड्रायव्हरचे एकूण उत्पन्न",
  "hisaab.netDue": "एकूण देय रक्कम",
  "hisaab.breakdownTitle": "हिशोब तपशील",
  "hisaab.driverHoldsFares": "ड्रायव्हरकडे जमा रक्कम",
  "hisaab.rides": "राइड्स",
  "hisaab.toDate": "ते",
  "hisaab.othersTitle": "इतर",
  "hisaab.gpsDeadMiles": "जीपीएस डेड माईल्स",
  "hisaab.totalGpsTracked": "एकूण जीपीएस किलोमीटर",
  "hisaab.idealTripKm": "आदर्श ट्रिप किलोमीटर",
  "hisaab.excessDeadMiles": "अतिरिक्त डेड माईल्स",
  "hisaab.deadMilePenalty": "डेड माईल्स दंड बाकी",
  "vehicle.specificationsTitle": "तपशील",
  "vehicle.brand": "ब्रांड",
  "vehicle.model": "मॉडेल",
  "vehicle.variant": "व्हेरियंट",
  "vehicle.regYear": "नोंदणी वर्ष",
  "vehicle.updated": "अद्यतनित",
  "vehicle.rc": "नोंदणी प्रमाणपत्र (RC)",
  "vehicle.insurance": "विमा",
  "vehicle.permit": "परमिट",
  "vehicle.fc": "फिटनेस प्रमाणपत्र (FC)",
  "vehicle.expires": "मुदत संपण्याची तारीख",
  "support.open": "उघडे",
  "support.resolved": "सोडवले",
  "support.dispute": "हिशोब तक्रार",
  "support.maintenance": "गाडीची देखभाल",
  "operator.operatorId": "ऑपरेटर आयडी:",
  "operator.totalCars": "एकूण गाड्या:",
  "operator.active": "सक्रिय",
  "operator.toPay": "देणे बाकी",
  "operator.toCollect": "घेणे बाकी",
  "operator.cars": "गाड्या",
  "operator.drivers": "ड्रायव्हर",
  "operator.vehicles": "वाहने",
  "operator.fleetDeposit": "फ्लॅट डिपॉझिट रक्कम",
  "operator.toPayDriver": "ड्रायव्हरला देणे:",
  "operator.driverOwes": "ड्रायव्हरवर बाकी:",
  "settle.selectOption": "पैसे भरण्याचा पर्याय निवडा",
  "settle.full": "पूर्ण",
  "settle.partPay": "भाग भरणा",
  "settle.advance": "अ‍ॅडव्हान्स",
  "settle.amountToPay": "पेमेंट रक्कम (₹)",
  "settle.payBtn": "पेमेंट करा",
  "name.Rajesh": "राजेश",
  "name.Suresh": "सुरेश",
  "name.Vikram": "विक्रम",
  "name.Mohammed": "मोहम्मद",
  "name.Anil": "अनिल",
  "name.RK": "आरके ट्रान्सपोर्ट",
  "name.Ramesh": "रमेश",
  "vehicle.specifications": "तपशील",
  "vehicle.documents": "कागदपत्रे",
  "hisaab.daysAt": "दिवस @",
  "platform.uber": "उबर",
  "platform.ola": "ओला",
  "platform.rapido": "रॅपिडो",
  "platform.others": "इतर",
  "refer.yourCode": "तुमचा रेफरल कोड",
  "refer.copyCode": "कोड कॉपी करा",
  "refer.rewardInfo": "तुमचा रेफर केलेला ड्रायव्हर 50 राइड्स पूर्ण करतो तेव्हा पुढील साप्ताहिक हिशोबात थेट ₹1,000 मिळवा.",
  "support.activeTickets": "सक्रिय तिकीट",
  "support.closedTickets": "बंद झालेली तिकीट",
  "support.allTickets": "सर्व तिकीट",
  "support.ticketCategory": "तिकीट वर्ग",
  "support.issueSubject": "विषय (थोडक्यात)",
  "support.subjectPlaceholder": "समस्येचा थोडक्यात तपशील...",
  "support.detailedDescription": "सविस्तर माहिती",
  "support.descriptionPlaceholder": "घडलेला प्रकार, आठवड्याची तारीख किंवा वाहनाची समस्या स्पष्ट करा...",
  "support.submitTicket": "तिकीट सबमिट करा",
  "support.cancel": "रद्द करा",
  "ticketCategory.Vehicle Maintenance": "वाहनांची देखभाल",
  "ticketCategory.App / Platform Issue": "ॲप / प्लॅटफॉर्म समस्या",
  "ticketCategory.Challan Dispute": "ट्रॅफिक चलान वाद",
  "ticketCategory.Other": "इतर समस्या",
  "ticketDetail.issueDetails": "समस्येचा तपशील",
  "ticketDetail.resolutionTitle": "लेत्झरॉइड सपोर्ट निवारण",
  "ticketDetail.closeBtn": "बंद करा",
  "refer.programReward": "बक्षीस माहिती",
  "refer.codeLabel": "नोंदणीकृत मोबाईल / कोड",
  "refer.referredDriversTitle": "तुम्ही रेफर केलेले ड्रायव्हर",
  "refer.rides": "राईड्स",
  "refer.pending": "प्रलंबित",
  "settle.instantPay": "झटपट पेमेंट",
  "settle.weeklyHisaabDue": "साप्ताहिक हिसाब देय:",
  "settle.challansAndPenalties": "चलान आणि दंड:",
  "settle.connectingGateway": "गेटवेशी कनेक्ट होत आहे...",
  "settle.toDate": "ते",
  "home.vehicleNumber": "वाहनाचा क्रमांक",
  "vehicle.number": "वाहनाचा क्रमांक",
  "support.ticketsTitle": "सपोर्ट तिकीट",
  "home.settleDuesTitle": "हिसाब चुकता करा",
  "home.settleDuesSub": "पेमेंट करा",
  "home.myVehicleTitle": "माझे वाहन",
  "home.myVehicleSub": "माहिती व कागदपत्रे",
  "home.supportDeskTitle": "सपोर्ट डेस्क",
  "home.referDriverTitle": "ड्रायव्हर रेफर करा",
  "home.referDriverSub": "कमवा ₹1,000",
  "hisaab.challanPenalty": "ट्रॅफिक चलान आणि दंड",
  "hisaab.gpsDeadMilesTitle": "जीपीएस डेड माईल",
  "hisaab.standingBalancesTitle": "खाते शिल्लक माहिती",
  "hisaab.contractTerms": "करार अटी",
  "hisaab.depositTitle": "सुरक्षा अनामत रक्कम",
  "hisaab.joiningFeeTitle": "जॉयनिंग फी",
  "hisaab.agreed": "मान्य:",
  "hisaab.paid": "जमा:",
  "hisaab.pending": "प्रलंबित:",
  "refer.perDriver": "ड्रायव्हर",
  "refer.namePlaceholder": "उदा. रमेश वर्मा",
  "refer.phonePlaceholder": "10-अंकी मोबाईल नंबर",
  "refer.submitLeadTitle": "डायरेक्ट लीड रेफरल",
  "refer.leadName": "ड्रायव्हरचे नाव",
  "refer.leadPhone": "मोबाईल नंबर",
  "refer.submitBtn": "लीड सबमिट करा आणि ₹1,000 कमवा",
  "refer.referredBadge": "रेफर केलेले",
  "notif.title": "सूचना",
  "notif.markAllRead": "सर्व वाचलेले चिन्हांकित करा",
  "notif.payoutTitle": "साप्ताहिक पेआउटची गणना झाली",
  "notif.payoutMessage": "रविवारच्या पेआउटसाठी ₹3,265.80 चे अंदाजित पेआउट तयार आहे.",
  "notif.twoHoursAgo": "२ तासांपूर्वी",
  "notif.closeFeed": "बंद करा",
  "notif.hisaabCreatedTitle": "हिसाब तयार झाला आहे",
  "notif.hisaabCreatedMessage": "तुमचे साप्ताहिक हिसाब पत्रक तयार आहे.",
  "notif.payHisaabTitle": "हिसाब भरा",
  "notif.payHisaabMessage": "कृपया तुमचे थकित हिसाब भरा.",
  "support.active": "सक्रिय",
  "support.closed": "बंद",
  "hisaab.earningsTitle": "प्लॅटफॉर्म कमाई",
  "hisaab.deductionsTitle": "कपात आणि भाडे",
  "hisaab.uberEarnings": "उबर कमाई",
  "hisaab.olaEarnings": "ओला कमाई",
  "hisaab.rapidoEarnings": "रापिडो कमाई",
  "hisaab.summaryTitle": "साप्ताहिक सारांश",
  "hisaab.totalRides": "एकूण राइड्स",
  "hisaab.grossEarnings": "एकूण कमाई",
  "hisaab.totalFeesRent": "एकूण शुल्क आणि भाडे",
  "hisaab.totalPenalties": "एकूण दंड",
  "hisaab.billTitle": "साप्ताहिक हिसाब विवरण",
  "hisaab.rentAndMaintenance": "भाडे आणि देखभाल",
  "hisaab.totalEarnings": "एकूण कमाई",
  "hisaab.weekLabel": "आठवडा",
  "hisaab.ridesUnit": "राइड्स",
  "profile.personalTitle": "वैयक्तिक आणि वैद्यकीय माहिती",
  "profile.documentsTitle": "कागदपत्रे आणि प्रमाणपत्रे"
};

export const TRANSLATIONS_TE: Record<string, string> = {
  "app.title": "లెట్జ్రైడ్ పోర్టల్",
  "app.subtitle": "Drive in the Future of Urban Mobility.",
  "login.selectRole": "లాగిన్ అవ్వడానికి నంబర్ నమోదు చేయండి",
  "login.driver": "డ్రైవర్ లాగిన్",
  "login.operator": "ఆపరేటర్ లాగిన్",
  "login.enterPhone": "10-అంకెల మొబైల్ నంబర్ ఎంటర్ చేయండి",
  "login.sendOtp": "ఓటీపీ పొందండి",
  "login.enterOtp": "4-అంకెల ఓటీపీ ఎంటర్ చేయండి",
  "login.verifyOtp": "నిర్ధారించి ప్రవేశించండి",
  "login.changeNumber": "మొబైల్ నంబర్ మార్చండి",
  "home.greeting": "శుభ మధ్యాహ్నం",
  "home.summary": "ఈ వారపు వసూళ్ల సారాంశం",
  "home.estimatedPayout": "అంచనా పేఅవుట్",
  "home.payoutToDriver": "డ్రైవర్‌కు చెల్లించాల్సిన మొత్తం",
  "home.dueToLetzryd": "లెట్జ్రైడ్‌కు చెల్లించాల్సిన మొత్తం",
  "home.daysActive": "యాక్టివ్ రోజులు",
  "home.trips": "మొత్తం ట్రిప్‌లు",
  "home.totalKm": "మొత్తం కిలోమీటర్లు",
  "home.deadMilesPct": "డెడ్ మైల్స్ %",
  "home.settleNow": "క్యాష్‌ఫ్రీ / యూపీఐ ద్వారా చెల్లించండి",
  "home.quickAccess": "త్వరిత లింక్‌లు",
  "home.currentHisaab": "ప్రస్తుత లెక్కలు",
  "home.lastWeekHisaab": "గత వారపు లెక్కలు",
  "home.raiseTicket": "సపోర్ట్ టికెట్ నమోదు చేయండి",
  "home.referDriver": "రెఫర్ చేయండి ₹1,000 పొందండి",
  "home.payLetzryd": "నేరుగా చెల్లించండి",
  "home.incentiveTracker": "వారపు ఇన్సెంటివ్ లక్ష్యం",
  "home.announcements": "ముఖ్యమైన లెట్జ్రైడ్ ప్రకటన",
  "home.deposit": "సెక్యూరిటీ డిపాజిట్",
  "home.cumulativeOwed": "మొత్తం బాకీ పడిన సొమ్ము",
  "hisaab.title": "వారపు లెక్కల వివరాలు",
  "hisaab.weekIndex": "వారం",
  "hisaab.of": "లో",
  "hisaab.inProgress": "పురోగతిలో ఉంది",
  "hisaab.locked": "పాత లెక్కలు (లాక్ చేయబడింది)",
  "hisaab.earnings": "మొత్తం సంపాదన",
  "hisaab.tripsCompleted": "పూర్తయిన ట్రిప్‌లు",
  "hisaab.digitalEarnings": "డిజిటల్ సంపాదన",
  "hisaab.cashCollected": "నగదు సేకరణ",
  "hisaab.tollPassThrough": "టోల్ రీఫండ్",
  "hisaab.incentives": "ప్లాట్‌ఫాం ఇన్సెంటివ్‌లు",
  "hisaab.subscriptionDeduction": "ప్లాట్‌ఫాం రుసుము",
  "hisaab.vehicleRent": "వాహనం కిరాయి",
  "hisaab.dailyMaintenance": "రోజువారీ నిర్వహణ రుసుము",
  "hisaab.prevAdjustments": "ఇతర బాకీలు మరియు సర్దుబాట్లు",
  "hisaab.tds": "టీడీఎస్ తగ్గింపు (1%)",
  "hisaab.paidDeposit": "చెల్లించిన డిపాజిట్",
  "hisaab.pendingDeposit": "బాకీ ఉన్న డిపాజిట్",
  "hisaab.joiningFeePaid": "చేరిక రుసుము చెల్లించారు",
  "hisaab.pendingJoiningFee": "బాకీ ఉన్న చేరిక రుసుము",
  "hisaab.previousOutstanding": "గత బాకీ",
  "hisaab.gpsRefreshedAt": "చివరి అప్‌డేట్ సమయం",
  "hisaab.disputeNotice": "లెక్కల ఫిర్యాదులు సోమ-గురువారాల్లో నమోదు చేయండి.",
  "settle.title": "వారపు లెక్కలు పూర్తి చేయండి",
  "settle.forWeek": "సమయం:",
  "settle.copy": "యూపీఐ ఐడీ కాపీ చేయండి",
  "settle.iHavePaid": "నేను చెల్లించాను",
  "settle.backToHisaab": "లెక్కల పేజీకి వెళ్లండి",
  "vehicle.title": "వాహనం మరియు పత్రాల వివరాలు",
  "vehicle.subtitle": "వివరాలు, గడువు మరియు ప్లాట్‌ఫాం అనుమతి",
  "vehicle.lastUpdated": "చివరి అప్‌డేట్ తేదీ",
  "support.title": "సపోర్ట్ సెంటర్",
  "support.subtitle": "మేనేజర్‌ను సంప్రదించండి లేదా టికెట్ నమోదు చేయండి",
  "support.manager": "కేటాయించిన డ్రైవర్ మేనేజర్",
  "support.newTicket": "కొత్త టికెట్ తీసుకోండి",
  "profile.title": "యూజర్ ప్రొఫైల్",
  "profile.subtitle": "గుర్తింపు వివరాలు మరియు అత్యవసర సమాచారం",
  "profile.edit": "ప్రొఫైల్ సవరించండి",
  "profile.editDetails": "వివరాలు సవరించండి",
  "profile.saveChanges": "మార్పులను సేవ్ చేయండి",
  "profile.identityTitle": "గుర్తింపు వివరాలు",
  "profile.registeredPhone": "రిజిస్టర్డ్ ఫోన్",
  "profile.aadharNumber": "ఆధార్ సంఖ్య",
  "profile.drivingLicense": "డ్రైవింగ్ లైసెన్స్",
  "profile.dlExpiry": "లైసెన్స్ గడువు",
  "profile.emergencyTitle": "అత్యవసర సంప్రదింపు",
  "profile.emergencyPerson": "సంప్రదించాల్సిన వ్యక్తి",
  "profile.emergencyRelation": "సంబంధం",
  "profile.emergencyPhone": "అత్యవసర మొబైల్",
  "profile.bloodGroup": "బ్లడ్ గ్రూప్",
  "profile.dob": "పుట్టిన తేదీ",
  "profile.address": "నివాస చిరునామా",
  "relation.spouse": "భార్య / భర్త",
  "relation.father": "తండ్రి",
  "relation.mother": "తల్లి",
  "relation.brother": "సోదరుడు",
  "relation.sister": "సోదరి",
  "relation.relative": "బంధువు / స్నేహితుడు",
  "profile.saved": "ప్రొఫైల్ అప్‌డేట్ చేయబడింది!",
  "profile.savedSuccess": "సమాచారం విజయవంతంగా సేవ్ చేయబడింది!",
  "refer.title": "డ్రైవర్‌ను రెఫర్ చేసి ₹1,000 సంపాదించండి",
  "refer.subtitle": "లెట్జ్రైడ్‌లో చేరే ఈవీ డ్రైవర్లకు మీ లింక్ షేర్ చేయండి.",
  "nav.home": "హోమ్",
  "nav.hisaab": "లెక్కలు",
  "nav.settle": "చెల్లింపు",
  "nav.vehicle": "వాహనం",
  "nav.fleet": "ఫ్లీట్",
  "nav.support": "సపోర్ట్",
  "home.vehicle": "వాహనం",
  "home.week": "వారం",
  "home.vsLastWeek": "గత వారంతో పోలిస్తే",
  "home.bonus": "బోనస్",
  "home.tripsRemaining": "ట్రిప్‌లు మిగిలి ఉన్నాయి",
  "home.toUnlockBonus": "₹1,500 బోనస్ పొందడానికి",
  "home.paid": "చెల్లించినది",
  "home.pending": "బాకీ:",
  "home.settlement": "సెటిల్మెంట్",
  "home.balanceDue": "మిగిలిన బాకీ",
  "home.paidToLetzryd": "లెట్జ్రైడ్కు చెల్లించబడింది",
  "home.paidToBank": "బ్యాంకుకు చెల్లించబడింది",
  "home.totalOutstandingDue": "మొత్తం బాకీ",
  "home.due": "బాకీ",
  "home.supportDeskSub": "సహాయం & టిక్కెట్లు",
  "home.earnBonusSub": "బోనస్ పొందండి",
  "hisaab.completed": "పూర్తయింది",
  "hisaab.netPayout": "డ్రైవర్ నికర పేఅవుట్",
  "hisaab.netDue": "మొత్తం చెల్లించాల్సిన బాకీ",
  "hisaab.breakdownTitle": "లెక్కల వివరాలు",
  "hisaab.driverHoldsFares": "డ్రైవర్ వద్ద ఉన్న నగదు",
  "hisaab.rides": "రైడ్స్",
  "hisaab.toDate": "నుండి",
  "hisaab.othersTitle": "ఇతర",
  "hisaab.gpsDeadMiles": "జీపీఎస్ డెడ్ మైళ్ళు",
  "hisaab.totalGpsTracked": "మొత్తం జీపీఎస్ ట్రాక్ చేసిన కిలోమీటర్లు",
  "hisaab.idealTripKm": "ఆదర్శ ట్రిప్ కిలోమీటర్లు",
  "hisaab.excessDeadMiles": "అదనపు డెడ్ మైళ్ళు",
  "hisaab.deadMilePenalty": "డెడ్ మైల్ జరిమానా బాకీ",
  "vehicle.specificationsTitle": "వివరాలు",
  "vehicle.brand": "బ్రాండ్",
  "vehicle.model": "మోడల్",
  "vehicle.variant": "వేరియంట్",
  "vehicle.regYear": "రిజిస్ట్రేషన్ సంవత్సరం",
  "vehicle.updated": "అప్‌డేట్ చేయబడింది",
  "vehicle.rc": "రిజిస్ట్రేషన్ సర్టిఫికేట్ (RC)",
  "vehicle.insurance": "ఇన్సూరెన్స్",
  "vehicle.permit": "పర్మిట్",
  "vehicle.fc": "ఫిట్‌నెస్ సర్టిఫికేట్ (FC)",
  "vehicle.expires": "గడువు ముగింపు తేదీ",
  "support.open": "ఓపెన్",
  "support.resolved": "పరిష్కరించబడింది",
  "support.dispute": "లెక్కల వివాదం",
  "support.maintenance": "వాహన నిర్వహణ",
  "operator.operatorId": "ఆపరేటర్ ఐడీ:",
  "operator.totalCars": "మొత్తం కార్లు:",
  "operator.active": "యాక్టివ్",
  "operator.toPay": "చెల్లించాల్సినవి",
  "operator.toCollect": "వసూలు చేయాల్సినవి",
  "operator.cars": "కార్లు",
  "operator.drivers": "డ్రైవర్లు",
  "operator.vehicles": "వాహనాలు",
  "operator.fleetDeposit": "ఫ్లీట్ సెక్యూరిటీ డిపాజిట్",
  "operator.toPayDriver": "డ్రైవర్‌కు చెల్లించాల్సినవి:",
  "operator.driverOwes": "డ్రైవర్ బాకీ ఉన్నది:",
  "settle.selectOption": "చెల్లింపు ఎంపికను ఎంచుకోండి",
  "settle.full": "పూర్తి",
  "settle.partPay": "పాక్షిక చెల్లింపు",
  "settle.advance": "అడ్వాన్స్",
  "settle.amountToPay": "చెల్లించాల్సిన మొత్తం (₹)",
  "settle.payBtn": "చెల్లించండి",
  "name.Rajesh": "రాజేష్",
  "name.Suresh": "సురేష్",
  "name.Vikram": "విక్రమ్",
  "name.Mohammed": "మొహమ్మద్",
  "name.Anil": "అనిల్",
  "name.RK": "ఆర్కే ట్రాన్స్‌పోర్ట్",
  "name.Ramesh": "రమేష్",
  "vehicle.specifications": "వివరాలు",
  "vehicle.documents": "పత్రాలు",
  "hisaab.daysAt": "రోజులు @",
  "platform.uber": "ఊబర్",
  "platform.ola": "ఓలా",
  "platform.rapido": "ర్యాపిడో",
  "platform.others": "ఇతర",
  "refer.yourCode": "మీ రెఫరల్ కోడ్",
  "refer.copyCode": "కోడ్ కాపీ చేయండి",
  "refer.rewardInfo": "మీరు రెఫర్ చేసిన డ్రైవర్ 50 రైడ్‌లు పూర్తి చేసినప్పుడు మీ తదుపరి వారపు లెక్కల్లో రూ.1,000 క్రెడిట్ పొందండి.",
  "support.activeTickets": "యాక్టివ్ టిక్కెట్లు",
  "support.closedTickets": "మూసివేసిన టిక్కెట్లు",
  "support.allTickets": "అన్ని టిక్కెట్లు",
  "support.ticketCategory": "టిక్కెట్ రకం",
  "support.issueSubject": "సమస్య అంశం",
  "support.subjectPlaceholder": "సమస్య వివరాలు సంక్షిప్తంగా...",
  "support.detailedDescription": "పూర్తి వివరాలు",
  "support.descriptionPlaceholder": "జరిగిన సంఘటన లేదా వాహన సమస్యను వివరించండి...",
  "support.submitTicket": "టిక్కెట్ సమర్పించండి",
  "support.cancel": "రద్దు చేయండి",
  "ticketCategory.Vehicle Maintenance": "వాహన నిర్వహణ",
  "ticketCategory.App / Platform Issue": "యాప్ / ప్లాట్‌ఫారమ్ సమస్య",
  "ticketCategory.Challan Dispute": "ట్రాఫిక్ చలాన్ వివాదం",
  "ticketCategory.Other": "ఇతర సమస్య",
  "ticketDetail.issueDetails": "సమస్య వివరాలు",
  "ticketDetail.resolutionTitle": "లెట్జ్రైడ్ సపోర్ట్ పరిష్కారం",
  "ticketDetail.closeBtn": "మూసివేయి",
  "refer.programReward": "రివార్డ్ వివరాలు",
  "refer.codeLabel": "రిజిస్టర్డ్ మొబైల్ / కోడ్",
  "refer.referredDriversTitle": "మీరు రెఫర్ చేసిన డ్రైవర్లు",
  "refer.rides": "రైడ్లు",
  "refer.pending": "పెండింగ్‌లో ఉంది",
  "settle.instantPay": "తక్షణ చెల్లింపు",
  "settle.weeklyHisaabDue": "వారపు లెక్కల బాకీ:",
  "settle.challansAndPenalties": "చలానాలు మరియు జరిమానాలు:",
  "settle.connectingGateway": "గేట్‌వేకి కనెక్ట్ అవుతోంది...",
  "settle.toDate": "నుండి",
  "home.vehicleNumber": "వాహనం నంబర్",
  "vehicle.number": "వాహనం నంబర్",
  "support.ticketsTitle": "సపోర్ట్ టిక్కెట్లు",
  "home.settleDuesTitle": "బాకీలు చెల్లించండి",
  "home.settleDuesSub": "చెల్లింపు చేయండి",
  "home.myVehicleTitle": "నా వాహనం",
  "home.myVehicleSub": "వివరాలు & పత్రాలు",
  "home.supportDeskTitle": "సపోర్ట్ డెస్క్",
  "home.referDriverTitle": "డ్రైవర్‌ను రెఫర్ చేయండి",
  "home.referDriverSub": "సంపాదించండి ₹1,000",
  "hisaab.challanPenalty": "ట్రాఫిక్ చలాన్ మరియు జరిమానా",
  "hisaab.gpsDeadMilesTitle": "జీపీఎస్ డెడ్ మైళ్ళు",
  "hisaab.standingBalancesTitle": "ఖాతా నిల్వల వివరాలు",
  "hisaab.contractTerms": "ఒప్పంద నిబంధనలు",
  "hisaab.depositTitle": "సెక్యూరిటీ డిపాజిట్",
  "hisaab.joiningFeeTitle": "జాయినింగ్ ఫీజు",
  "hisaab.agreed": "అంగీకరించినవి:",
  "hisaab.paid": "చెల్లించినవి:",
  "hisaab.pending": "పెండింగ్:",
  "refer.perDriver": "డ్రైవర్",
  "refer.namePlaceholder": "ఉదా. రమేష్ వర్మ",
  "refer.phonePlaceholder": "10-అంకెల మొబైల్ సంఖ్య",
  "refer.submitLeadTitle": "డైరెక్ట్ లీడ్ రెఫరల్",
  "refer.leadName": "డ్రైవర్ పేరు",
  "refer.leadPhone": "మొబైల్ సంఖ్య",
  "refer.submitBtn": "లీడ్ సమర్పించండి & ₹1,000 సంపాదించండి",
  "refer.referredBadge": "రెఫర్ చేయబడింది",
  "notif.title": "నోటిఫికేషన్లు",
  "notif.markAllRead": "అన్నీ చదివినట్లు గుర్తించండి",
  "notif.payoutTitle": "వారపు పేఅవుట్ లెక్కించబడింది",
  "notif.payoutMessage": "ఆదివారం నిధుల విడుదల కోసం ₹3,265.80 అంచనా పేఅవుట్ సిద్ధంగా ఉంది.",
  "notif.twoHoursAgo": "2 గంటల క్రితం",
  "notif.closeFeed": "మూసివేయి",
  "notif.hisaabCreatedTitle": "లెక్కలు తయారు చేయబడ్డాయి",
  "notif.hisaabCreatedMessage": "మీ వారపు లెక్కల నివేదిక సిద్ధంగా ఉంది.",
  "notif.payHisaabTitle": "లెక్కలు చెల్లించండి",
  "notif.payHisaabMessage": "దయచేసి మీ వారపు బాకీలను చెల్లించండి.",
  "support.active": "యాక్టివ్",
  "support.closed": "ముగిసింది",
  "hisaab.earningsTitle": "ప్లాట్‌ఫారమ్ సంపాదన",
  "hisaab.deductionsTitle": "మినహాయింపులు & అద్దె",
  "hisaab.uberEarnings": "ఉబర్ సంపాదన",
  "hisaab.olaEarnings": "ఓలా సంపాదన",
  "hisaab.rapidoEarnings": "రాపిడో సంపాదన",
  "hisaab.summaryTitle": "వారపు సారాంశం ముఖ్యాంశాలు",
  "hisaab.totalRides": "మొత్తం రైడ్లు",
  "hisaab.grossEarnings": "మొత్తం ఆదాయం",
  "hisaab.totalFeesRent": "మొత్తం రుసుములు & అద్దె",
  "hisaab.totalPenalties": "మొత్తం జరిమానాలు",
  "hisaab.billTitle": "వారపు నివేదిక బిల్లు",
  "hisaab.rentAndMaintenance": "అద్దె & నిర్వహణ",
  "hisaab.totalEarnings": "మొత్తం సంపాదన",
  "hisaab.weekLabel": "వారం",
  "hisaab.ridesUnit": "రైడ్లు",
  "profile.personalTitle": "వ్యక్తిగత & వైద్య సమాచారం",
  "profile.documentsTitle": "పత్రాలు & ఆధారాలు"
};

export const TRANSLATIONS_KN: Record<string, string> = {
  "app.title": "ಲೆಟ್ಜ್ರೈಡ್ ಪೋರ್ಟಲ್",
  "app.subtitle": "Drive in the Future of Urban Mobility.",
  "login.selectRole": "ಲಾಗಿನ್ ಮಾಡಲು ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
  "login.driver": "ಚಾಲಕ ಲಾಗಿನ್",
  "login.operator": "ಆಪರೇಟರ್ ಲಾಗಿನ್",
  "login.enterPhone": "10-ಅಂಕೆಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
  "login.sendOtp": "ಒಟಿಪಿ ಪಡೆಯಿರಿ",
  "login.enterOtp": "4-ಅಂಕೆಗಳ ಒಟಿಪಿ ನಮೂದಿಸಿ",
  "login.verifyOtp": "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಪ್ರವೇಶಿಸಿ",
  "login.changeNumber": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಬದಲಾಯಿಸಿ",
  "home.greeting": "ಶುಭ ಮಧ್ಯಾಹ್ನ",
  "home.summary": "ಈ ವಾರದ ಲೆಕ್ಕಾಚಾರದ ವಿವರಗಳು",
  "home.estimatedPayout": "ಅಂದಾಜು ಪಾವತಿ",
  "home.payoutToDriver": "ಚಾಲಕನಿಗೆ ಲೆಟ್ಜ್ರೈಡ್ ಪಾವತಿಸುವ ಮೊತ್ತ",
  "home.dueToLetzryd": "ಲೆಟ್ಜ್ರೈಡ್‌ಗೆ ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ",
  "home.daysActive": "ಸಕ್ರಿಯ ದಿನಗಳು",
  "home.trips": "ಒಟ್ಟು ಟ್ರಿಪ್‌ಗಳು",
  "home.totalKm": "ಒಟ್ಟು ಕಿಲೋಮೀಟರ್",
  "home.deadMilesPct": "ಡೆಡ್ ಮೈಲ್ಸ್ %",
  "home.settleNow": "ಕ್ಯಾಶ್‌ಫ್ರೀ / ಯುಪಿಐ ಮೂಲಕ ಪಾವತಿಸಿ",
  "home.quickAccess": "ತ್ವರಿತ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು",
  "home.currentHisaab": "ಪ್ರಸ್ತುತ ಲೆಕ್ಕಚಾರ",
  "home.lastWeekHisaab": "ಕಳೆದ ವಾರದ ಲೆಕ್ಕಚಾರ",
  "home.raiseTicket": "ಸಹಾಯ ಟಿಕೆಟ್ ನಮೂದಿಸಿ",
  "home.referDriver": "ರೆಫರ್ ಮಾಡಿ ₹1,000 ಗಳಿಸಿ",
  "home.payLetzryd": "ನೇರವಾಗಿ ಪಾವತಿಸಿ",
  "home.incentiveTracker": "ವಾರದ ಇನ್ಸೆಂಟಿವ್ ಗುರಿ",
  "home.announcements": "ಪ್ರಮುಖ ಲೆಟ್ಜ್ರೈಡ್ ಪ್ರಕಟಣೆ",
  "home.deposit": "ಸೆಕ್ಯೂರಿಟಿ ಡೆಪಾಸಿಟ್",
  "home.cumulativeOwed": "ಒಟ್ಟು ಬಾಕಿ ಮೊತ್ತ",
  "hisaab.title": "ವಾರದ ಲೆಕ್ಕಾಚಾರದ ವರದಿ",
  "hisaab.weekIndex": "ವಾರ",
  "hisaab.of": "ರ",
  "hisaab.inProgress": "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
  "hisaab.locked": "ಹಿಂದಿನ ಲೆಕ್ಕಾಚಾರ (ಲಾಕ್ ಆಗಿದೆ)",
  "hisaab.earnings": "ಒಟ್ಟು ಗಳಿಕೆ",
  "hisaab.tripsCompleted": "ಪೂರ್ಣಗೊಂಡ ಟ್ರಿಪ್‌ಗಳು",
  "hisaab.digitalEarnings": "ಡಿಜಿಟಲ್ ಗಳಿಕೆ",
  "hisaab.cashCollected": "ನಗದು ಸಂಗ್ರಹ",
  "hisaab.tollPassThrough": "ಟೋಲ್ ಮರುಪಾವತಿ",
  "hisaab.incentives": "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಇನ್ಸೆಂಟಿವ್‌ಗಳು",
  "hisaab.subscriptionDeduction": "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ",
  "hisaab.vehicleRent": "ವಾಹನ ಬಾಡಿಗೆ",
  "hisaab.dailyMaintenance": "ದೈನಂದಿನ ನಿರ್ವಹಣೆ ಶುಲ್ಕ",
  "hisaab.prevAdjustments": "ಇತರ ಬಾಕಿ ಮತ್ತು ಹೊಂದಾಣಿಕೆಗಳು",
  "hisaab.tds": "ಟಿಡಿಎಸ್ ಕಡಿತ (1%)",
  "hisaab.paidDeposit": "ಪಾವತಿಸಿದ ಡೆಪಾಸಿಟ್",
  "hisaab.pendingDeposit": "ಬಾಕಿ ಡೆಪಾಸಿಟ್",
  "hisaab.joiningFeePaid": "ಸೇರ್ಪಡೆ ಶುಲ್ಕ ಪಾವತಿಸಲಾಗಿದೆ",
  "hisaab.pendingJoiningFee": "ಬಾಕಿ ಸೇರ್ಪಡೆ ಶುಲ್ಕ",
  "hisaab.previousOutstanding": "ಹಿಂದಿನ ಬಾಕಿ",
  "hisaab.gpsRefreshedAt": "ಕೊನೆಯ ಅಪ್‌ಡೇಟ್ ಸಮಯ",
  "hisaab.disputeNotice": "ಲೆಕ್ಕಾಚಾರದ ದೂರುಗಳನ್ನು ಸೋಮ-ಗುರುವಾರದೊಳಗೆ ನಮೂದಿಸಿ.",
  "settle.title": "ವಾರದ ಲೆಕ್ಕಾಚಾರ ಪೂರ್ಣಗೊಳಿಸಿ",
  "settle.forWeek": "ಅವಧಿ:",
  "settle.copy": "ಯುಪಿಐ ಐಡಿ ಕಾಪಿ ಮಾಡಿ",
  "settle.iHavePaid": "ನಾನು ಪಾವತಿಸಿದ್ದೇನೆ",
  "settle.backToHisaab": "ಲೆಕ್ಕಾಚಾರಕ್ಕೆ ಹಿಂತಿರುಗಿ",
  "vehicle.title": "ವಾಹನ ಮತ್ತು ದಾಖಲೆಗಳ ವಿವರ",
  "vehicle.subtitle": "ವಿವರಣೆ, ಸಿಂಧುತ್ವ ಮತ್ತು ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಅನುಮತಿ",
  "vehicle.lastUpdated": "ಕೊನೆಯ ಅಪ್‌ಡೇಟ್ ದಿನಾಂಕ",
  "support.title": "ಸಹಾಯ ಕೇಂದ್ರ",
  "support.subtitle": "ಮ್ಯಾನೇಜರ್ ಸಂಪರ್ಕಿಸಿ ಅಥವಾ ಟಿಕೆಟ್ ನಮೂದಿಸಿ",
  "support.manager": "ನಿಯೋಜಿತ ಚಾಲಕ ಮ್ಯಾನೇಜರ್",
  "support.newTicket": "ಹೊಸ ಟಿಕೆಟ್ ನಮೂದಿಸಿ",
  "profile.title": "ಬಳಕೆದಾರರ ಪ್ರೊಫೈಲ್",
  "profile.subtitle": "ಗುರುತಿನ ವಿವರಗಳು ಮತ್ತು ತುರ್ತು ಮಾಹಿತಿ",
  "profile.edit": "ಪ್ರೊಫೈಲ್ ಎಡಿಟ್ ಮಾಡಿ",
  "profile.editDetails": "ವಿವರಗಳನ್ನು ಸಂಪಾದಿಸಿ",
  "profile.saveChanges": "ಬದಲಾವಣೆ ಉಳಿಸಿ",
  "profile.identityTitle": "ಗುರುತಿನ ವಿವರಗಳು",
  "profile.registeredPhone": "ನೋಂದಾಯಿತ ಫೋನ್",
  "profile.aadharNumber": "ಆಧಾರ್ ಸಂಖ್ಯೆ",
  "profile.drivingLicense": "ಚಾಲನಾ ಪರವಾನಗಿ",
  "profile.dlExpiry": "ಪರವಾನಗಿ ಮುಕ್ತಾಯ",
  "profile.emergencyTitle": "ತುರ್ತು ಸಂಪರ್ಕ",
  "profile.emergencyPerson": "ಸಂಪರ್ಕಿಸಬೇಕಾದ ವ್ಯಕ್ತಿ",
  "profile.emergencyRelation": "ಸಂಬಂಧ",
  "profile.emergencyPhone": "ತುರ್ತು ಮೊಬೈಲ್",
  "profile.bloodGroup": "ರಕ್ತದ ಗುಂಪು",
  "profile.dob": "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
  "profile.address": "ವಾಸಸ್ಥಳದ ವಿಳಾಸ",
  "relation.spouse": "ಪತಿ / ಪತ್ನಿ",
  "relation.father": "ತಂದೆ",
  "relation.mother": "ತಾಯಿ",
  "relation.brother": "ಸಹೋದರ",
  "relation.sister": "ಸಹೋದರಿ",
  "relation.relative": "ಸಂಬಂಧಿ / ಸ್ನೇಹಿತ",
  "profile.saved": "ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ಅಪ್‌ಡೇಟ್ ಆಗಿದೆ!",
  "profile.savedSuccess": "ಮಾಹಿತಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ!",
  "refer.title": "ಚಾಲಕರನ್ನು ರೆಫರ್ ಮಾಡಿ ₹1,000 ಗಳಿಸಿ",
  "refer.subtitle": "ಲೆಟ್ಜ್ರೈಡ್‌ಗೆ ಸೇರುವ ಇವಿ ಚಾಲಕರಿಗೆ ಲಿಂಕ್ ಕಳುಹಿಸಿ.",
  "nav.home": "ಹೋಮ್",
  "nav.hisaab": "ಲೆಕ್ಕಾಚಾರ",
  "nav.settle": "ಸೆಟಲ್",
  "nav.vehicle": "ವಾಹನ",
  "nav.fleet": "ಫ್ಲೀಟ್",
  "nav.support": "ಸಹಾಯ",
  "home.vehicle": "ವಾಹನ",
  "home.week": "ವಾರ",
  "home.vsLastWeek": "ಕಳೆದ ವಾರಕ್ಕೆ ಹೋಲಿಸಿದರೆ",
  "home.bonus": "ಬೋನಸ್",
  "home.tripsRemaining": "ಟ್ರಿಪ್‌ಗಳು ಬಾಕಿ ಇವೆ",
  "home.toUnlockBonus": "₹1,500 ಬೋನಸ್ ಪಡೆಯಲು",
  "home.paid": "ಪಾವತಿಸಿದ:",
  "home.pending": "ಪಾಕಿ:",
  "home.settlement": "ಸೆಟಲ್ಮೆಂಟ್",
  "home.balanceDue": "ಉಳಿದ ಬಾಕಿ",
  "home.paidToLetzryd": "ಲೆಟ್ಜ್‌ರೈಡ್‌ಗೆ ಪಾವತಿಸಲಾಗಿದೆ",
  "home.paidToBank": "ಬ್ಯಾಂಕ್‌ಗೆ ಪಾವತಿಸಲಾಗಿದೆ",
  "home.totalOutstandingDue": "ಒಟ್ಟು ಬಾಕಿ",
  "home.due": "ಬಾಕಿ",
  "home.supportDeskSub": "ಸಹಾಯ & ಟಿಕೆಟ್‌ಗಳು",
  "home.earnBonusSub": "ಬೋನಸ್ ಗಳಿಸಿ",
  "hisaab.completed": "ಪೂರ್ಣಗೊಂಡಿದೆ",
  "hisaab.netPayout": "ಚಾಲಕನ ನಿವ್ವಳ ಪಾವತಿ",
  "hisaab.netDue": "ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ",
  "hisaab.breakdownTitle": "ಲೆಕ್ಕಾಚಾರ ವಿವರಗಳು",
  "hisaab.driverHoldsFares": "ಚಾಲಕನ ಬಳಿ ಇರುವ ಹಣ",
  "hisaab.rides": "ರೈಡ್‌ಗಳು",
  "hisaab.toDate": "ರಿಂದ",
  "hisaab.othersTitle": "ಇತರ",
  "hisaab.gpsDeadMiles": "ಜಿಪಿಎಸ್ ಡೆಡ್ ಮೈಲಿಗಳು",
  "hisaab.totalGpsTracked": "ಒಟ್ಟು ಜಿಪಿಎಸ್ ಕಿಲೋಮೀಟರ್",
  "hisaab.idealTripKm": "ಸೂಕ್ತ ಟ್ರಿಪ್ ಕಿಲೋಮೀಟರ್",
  "hisaab.excessDeadMiles": "ಹೆಚ್ಚುವರಿ ಡೆಡ್ ಮೈಲಿಗಳು",
  "hisaab.deadMilePenalty": "ಡೆಡ್ ಮೈಲ್ ದಂಡ ಬಾಕಿ",
  "vehicle.specificationsTitle": "ವಿವರಣೆ",
  "vehicle.brand": "ಬ್ರ್ಯಾಂಡ್",
  "vehicle.model": "ಮಾಡೆಲ್",
  "vehicle.variant": "ವೇರಿಯೆಂಟ್",
  "vehicle.regYear": "ನೋಂದಣಿ ವರ್ಷ",
  "vehicle.updated": "ಅಪ್‌ಡೇಟ್ ಆಗಿದೆ",
  "vehicle.rc": "ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರ (RC)",
  "vehicle.insurance": "ವಿಮೆ",
  "vehicle.permit": "ಪರ್ಮಿಟ್",
  "vehicle.fc": "ಫಿಟ್ನೆಸ್ ಪ್ರಮಾಣಪತ್ರ (FC)",
  "vehicle.expires": "ಸಿಂಧುತ್ವ ಮುಕ್ತಾಯ",
  "support.open": "ತೆರೆದಿದೆ",
  "support.resolved": "ಪರಿಹರಿಸಲಾಗಿದೆ",
  "support.dispute": "ಲೆಕ್ಕಾಚಾರ ದೂರು",
  "support.maintenance": "ವಾಹನ ನಿರ್ವಹಣೆ",
  "operator.operatorId": "ಆಪರೇಟರ್ ಐಡಿ:",
  "operator.totalCars": "ಒಟ್ಟು ಕಾರುಗಳು:",
  "operator.active": "ಸಕ್ರಿಯ",
  "operator.toPay": "ಪಾವತಿಸಬೇಕಾದ",
  "operator.toCollect": "ಸಂಗ್ರಹಿಸಬೇಕಾದ",
  "operator.cars": "ಕಾರುಗಳು",
  "operator.drivers": "ಚಾಲಕರು",
  "operator.vehicles": "ವಾಹನಗಳು",
  "operator.fleetDeposit": "ಫ್ಲೀಟ್ ಸೆಕ್ಯೂರಿಟಿ ಡೆಪಾಸಿಟ್",
  "operator.toPayDriver": "ಚಾಲಕನಿಗೆ ಪಾವತಿಸಬೇಕಾದ:",
  "operator.driverOwes": "ಚಾಲಕ ಬಾಕಿ ಇರುವುದು:",
  "settle.selectOption": "ಪಾವತಿ ಆಯ್ಕೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "settle.full": "ಪೂರ್ಣ",
  "settle.partPay": "ಭಾಗಶಃ ಪಾವತಿ",
  "settle.advance": "ಅಡ್ವಾನ್ಸ್",
  "settle.amountToPay": "ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ (₹)",
  "settle.payBtn": "ಪಾವತಿಸಿ",
  "name.Rajesh": "ರಾಜೇಶ್",
  "name.Suresh": "ಸುರೇಶ್",
  "name.Vikram": "ವಿಕ್ರಮ್",
  "name.Mohammed": "ಮೊಹಮ್ಮದ್",
  "name.Anil": "ಅನಿಲ್",
  "name.RK": "ಆರ್‌ಕೆ ಟ್ರಾನ್ಸ್‌ಪೋರ್ಟ್",
  "name.Ramesh": "ರಮೇಶ್",
  "vehicle.specifications": "ವಿವರಣೆ",
  "vehicle.documents": "ದಾಖಲೆಗಳು",
  "hisaab.daysAt": "ದಿನಗಳು @",
  "platform.uber": "ಉಬರ್",
  "platform.ola": "ಓಲಾ",
  "platform.rapido": "ರ್ಯಾಪಿಡೋ",
  "platform.others": "ಇತರ",
  "refer.yourCode": "ನಿಮ್ಮ ರೆಫರಲ್ ಕೋಡ್",
  "refer.copyCode": "ಕೋಡ್ ಕಾಪಿ ಮಾಡಿ",
  "refer.rewardInfo": "ನಿಮ್ಮ ರೆಫರ್ ಮಾಡಿದ ಚಾಲಕ 50 ರೈಡ್‌ಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿದಾಗ ನಿಮ್ಮ ಮುಂದಿನ ವಾರದ ಲೆಕ್ಕಾಚಾರದಲ್ಲಿ ನೇರವಾಗಿ ₹1,000 ಪಡೆಯಿರಿ.",
  "support.activeTickets": "ಸಕ್ರಿಯ ಟಿಕೆಟ್‌ಗಳು",
  "support.closedTickets": "ಮುಚ್ಚಿದ ಟಿಕೆಟ್‌ಗಳು",
  "support.allTickets": "ಎಲ್ಲಾ ಟಿಕೆಟ್‌ಗಳು",
  "support.ticketCategory": "ಟಿಕೆಟ್ ವರ್ಗ",
  "support.issueSubject": "ಸಮಸ್ಯೆಯ ವಿಷಯ",
  "support.subjectPlaceholder": "ಸಮಸ್ಯೆಯ ಸಂಕ್ಷಿಪ್ತ ವಿವರ...",
  "support.detailedDescription": "ಸಂಪೂರ್ಣ ವಿವರಣೆ",
  "support.descriptionPlaceholder": "ನಡೆದ ಘಟನೆ ಅಥವಾ ವಾಹನದ ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ...",
  "support.submitTicket": "ಟಿಕೆಟ್ ಸಲ್ಲಿಸಿ",
  "support.cancel": "ರದ್ದು ಮಾಡಿ",
  "ticketCategory.Vehicle Maintenance": "ವಾಹನ ನಿರ್ವಹಣೆ",
  "ticketCategory.App / Platform Issue": "ಆ್ಯಪ್ / ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಸಮಸ್ಯೆ",
  "ticketCategory.Challan Dispute": "ಚಲನ್ ವಿವಾದ",
  "ticketCategory.Other": "ಇತರ ಸಮಸ್ಯೆ",
  "ticketDetail.issueDetails": "ಸಮಸ್ಯೆಯ ವಿವರಗಳು",
  "ticketDetail.resolutionTitle": "ಲೆಟ್ಜ್ರೈಡ್ ಬೆಂಬಲ ಪರಿಹಾರ",
  "ticketDetail.closeBtn": "ಮುಚ್ಚಿ",
  "refer.programReward": "ಬಹುಮಾನದ ವಿವರ",
  "refer.codeLabel": "ನೋಂದಾಯಿತ ಮೊಬೈಲ್ / ಕೋಡ್",
  "refer.referredDriversTitle": "ನೀವು ರೆಫರ್ ಮಾಡಿದ ಚಾಲಕರು",
  "refer.rides": "ರೈಡ್‌ಗಳು",
  "refer.pending": "ಬಾಕಿ ಇದೆ",
  "settle.instantPay": "ತತ್ಕ್ಷಣ ಪಾವತಿ",
  "settle.weeklyHisaabDue": "ವಾರದ ಲೆಕ್ಕಾಚಾರದ ಬಾಕಿ:",
  "settle.challansAndPenalties": "ಚಲನ್‌ಗಳು ಮತ್ತು ದಂಡಗಳು:",
  "settle.connectingGateway": "ಗೇಟ್‌ವೇಗೆ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...",
  "settle.toDate": "ರಿಂದ",
  "home.vehicleNumber": "ವಾಹನದ ಸಂಖ್ಯೆ",
  "vehicle.number": "ವಾಹನದ ಸಂಖ್ಯೆ",
  "support.ticketsTitle": "ಬೆಂಬಲ ಟಿಕೆಟ್‌ಗಳು",
  "home.settleDuesTitle": "ಬಾಕಿ ಚುಕ್ತಾ ಮಾಡಿ",
  "home.settleDuesSub": "ಪಾವತಿ ಮಾಡಿ",
  "home.myVehicleTitle": "ನನ್ನ ವಾಹನ",
  "home.myVehicleSub": "ವಿವರಗಳು & ದಾಖಲೆಗಳು",
  "home.supportDeskTitle": "ಬೆಂಬಲ ಡೆಸ್ಕ್",
  "home.referDriverTitle": "ಚಾಲಕನನ್ನು ರೆಫರ್ ಮಾಡಿ",
  "home.referDriverSub": "ಗಳಿಸಿ ₹1,000",
  "hisaab.challanPenalty": "ಟ್ರಾಫಿಕ್ ಚಲನ್ ಮತ್ತು ದಂಡ",
  "hisaab.gpsDeadMilesTitle": "ಜಿಪಿಎಸ್ ಡೆಡ್ ಮೈಲಿಗಳು",
  "hisaab.standingBalancesTitle": "ಖಾತೆ ಬಾಕಿ ವಿವರಗಳು",
  "hisaab.contractTerms": "ಒಪ್ಪಂದದ ನಿಯಮಗಳು",
  "hisaab.depositTitle": "ಭದ್ರತಾ ಠೇವಣಿ",
  "hisaab.joiningFeeTitle": "ಜಾಯಿನ್ನಿಂಗ್ ಶುಲ್ಕ",
  "hisaab.agreed": "ಒಪ್ಪಿಕೊಂಡದ್ದು:",
  "hisaab.paid": "ಪಾವತಿಸಿದ್ದು:",
  "hisaab.pending": "ಬಾಕಿ:",
  "refer.perDriver": "ಚಾಲಕ",
  "refer.namePlaceholder": "ಉದಾ. ರಮೇಶ್ ವರ್ಮಾ",
  "refer.phonePlaceholder": "10-ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
  "refer.submitLeadTitle": "ಡೈರೆಕ್ಟ್ ಲೀಡ್ ರೆಫರಲ್",
  "refer.leadName": "ಚಾಲಕನ ಹೆಸರು",
  "refer.leadPhone": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
  "refer.submitBtn": "ಲೀಡ್ ಸಲ್ಲಿಸಿ & ₹1,000 ಗಳಿಸಿ",
  "refer.referredBadge": "ರೆಫರ್ ಮಾಡಲಾಗಿದೆ",
  "notif.title": "ಅಧಿಸೂಚನೆಗಳು",
  "notif.markAllRead": "ಎಲ್ಲವನ್ನೂ ಓದಿದಂತೆ ಗುರುತಿಸಿ",
  "notif.payoutTitle": "ವಾರದ ಪಾವತಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ",
  "notif.payoutMessage": "ಭಾನುವಾರದ ಪಾವತಿಗೆ ₹3,265.80 ಅಂದಾಜು ಮೊತ್ತ ಸಿದ್ಧವಾಗಿದೆ.",
  "notif.twoHoursAgo": "2 ಗಂಟೆಗಳ ಹಿಂದೆ",
  "notif.closeFeed": "ಮುಚ್ಚಿ",
  "notif.hisaabCreatedTitle": "ಲೆಕ್ಕಾಚಾರ ಸಿದ್ಧವಾಗಿದೆ",
  "notif.hisaabCreatedMessage": "ನಿಮ್ಮ ವಾರದ ಲೆಕ್ಕಾಚಾರದ ವಿವರಣೆ ಸಿದ್ಧವಾಗಿದೆ.",
  "notif.payHisaabTitle": "ಲೆಕ್ಕ ಚುಕ್ತಾ ಮಾಡಿ",
  "notif.payHisaabMessage": "ದಯವಿಟ್ಟು ನಿಮ್ಮ ವಾರದ ಬಾಕಿಯನ್ನು ಪಾವತಿಸಿ.",
  "support.active": "ಸಕ್ರಿಯ",
  "support.closed": "ಮುಚ್ಚಲಾಗಿದೆ",
  "hisaab.earningsTitle": "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಗಳಿಕೆ",
  "hisaab.deductionsTitle": "ಕಡಿತಗಳು & ಬಾಡಿಗೆ",
  "hisaab.uberEarnings": "ಉಬರ್ ಗಳಿಕೆ",
  "hisaab.olaEarnings": "ಓಲಾ ಗಳಿಕೆ",
  "hisaab.rapidoEarnings": "ರ‍್ಯಾಪಿಡೋ ಗಳಿಕೆ",
  "hisaab.summaryTitle": "ವಾರದ ಸಾರಾಂಶದ ಮುಖ್ಯಾಂಶಗಳು",
  "hisaab.totalRides": "ಒಟ್ಟು ರೈಡ್‌ಗಳು",
  "hisaab.grossEarnings": "ಒಟ್ಟು ಗಳಿಕೆ",
  "hisaab.totalFeesRent": "ಒಟ್ಟು ಶುಲ್ಕ ಮತ್ತು ಬಾಡಿಗೆ",
  "hisaab.totalPenalties": "ಒಟ್ಟು ದಂಡ",
  "hisaab.billTitle": "ವಾರದ ಲೆಕ್ಕಾಚಾರದ ಬಿಲ್",
  "hisaab.rentAndMaintenance": "ಬಾಡಿಗೆ ಮತ್ತು ನಿರ್ವಹಣೆ",
  "hisaab.totalEarnings": "ಒಟ್ಟು ಗಳಿಕೆ",
  "hisaab.weekLabel": "ವಾರ",
  "hisaab.ridesUnit": "ರೈಡ್‌ಗಳು",
  "profile.personalTitle": "ವೈಯಕ್ತಿಕ ಮತ್ತು ವೈದ್ಯಕೀಯ ಮಾಹಿತಿ",
  "profile.documentsTitle": "ದಾಖಲೆಗಳು ಮತ್ತು ವಿವರಗಳು"
};

